// <auto-generated/>
// StreamJsonRpc dispatch target for the GSharp language server. Marked auto-generated to opt
// out of StyleCop documentation/ordering rules; this is protocol plumbing, not product logic.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using GSharp.Core.CodeAnalysis.Diagnostics;
using GSharp.Core.CodeAnalysis.Symbols;
using GSharp.Core.CodeAnalysis.Syntax;
using GSharp.LanguageServer.Protocol;
using StreamJsonRpc;
using Range = GSharp.LanguageServer.Protocol.Range;

namespace GSharp.LanguageServer.Server;

/// <summary>
/// Hosts the LSP method handlers and dispatches them through StreamJsonRpc. Concurrency
/// follows Roslyn's RequestExecutionQueue model: mutating ("write") requests
/// (didOpen/didChange/didSave/didClose/watchedFiles) hold a single gate for their brief
/// body so the mutation is fully applied before later requests snapshot, while non-mutating
/// ("read") requests only take the gate to capture an ordered, immutable document snapshot
/// and then run their computation off the gate on the thread pool. This keeps reads fully
/// concurrent and ensures a slow read (e.g. the first cold workspace bind) never blocks
/// other reads or editing.
/// </summary>
public sealed class LspServer
{
    private readonly DocumentContentService documentContentService;
    private readonly WorkspaceState workspaceState;
    private readonly ILogger logger;
    private readonly SemaphoreSlim gate = new SemaphoreSlim(1, 1);
    private readonly TaskCompletionSource<int> exitSource = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
    private readonly object refreshLock = new object();

    private JsonRpc rpc;
    private bool shutdownRequested;
    private bool clientSupportsPullDiagnostics;
    private bool clientSupportsDiagnosticRefresh;
    private Timer refreshTimer;
    private string defaultFormattingIndent = "  ";

    public LspServer(DocumentContentService documentContentService, WorkspaceState workspaceState, ILogger logger = null)
    {
        this.documentContentService = documentContentService;
        this.workspaceState = workspaceState;
        this.logger = logger ?? NullLogger.Instance;
    }

    /// <summary>Gets a task that completes when the client sends the <c>exit</c> notification.</summary>
    public Task<int> WaitForExit => this.exitSource.Task;

    /// <summary>Associates the JsonRpc connection used to send notifications to the client.</summary>
    /// <param name="connection">The active <see cref="JsonRpc"/> connection.</param>
    public void Attach(JsonRpc connection)
    {
        this.rpc = connection;
        connection.Disconnected += (_, _) => this.exitSource.TrySetResult(this.shutdownRequested ? 0 : 1);
    }

    [JsonRpcMethod("initialize", UseSingleObjectParameterDeserialization = true)]
    public Task<InitializeResult> InitializeAsync(InitializeParams request)
    {
        var rootPath = request?.RootPath ?? request?.RootUri?.GetFileSystemPath();
        this.DetectClientDiagnosticCapabilities(request?.Capabilities ?? default);
        this.defaultFormattingIndent = ResolveDefaultFormattingIndent(request?.InitializationOptions ?? default);
        try
        {
            WorkspaceInitializer.Initialize(this.workspaceState, rootPath);
        }
        catch
        {
            // Workspace discovery is best-effort; single-file editing still works without it.
        }

        return Task.FromResult(new InitializeResult
        {
            Capabilities = ServerCapabilitiesFactory.Create(),
            ServerInfo = new ServerInfo { Name = "GSharp Language Server", Version = "1.0.0" },
        });
    }

    [JsonRpcMethod("initialized")]
    public void Initialized(JsonElement @params)
    {
        // No-op: capabilities are advertised statically in the initialize result.
    }

    [JsonRpcMethod("shutdown")]
    public object Shutdown()
    {
        this.shutdownRequested = true;
        return null;
    }

    [JsonRpcMethod("exit")]
    public void Exit()
    {
        this.exitSource.TrySetResult(this.shutdownRequested ? 0 : 1);
    }

    [JsonRpcMethod("textDocument/didOpen", UseSingleObjectParameterDeserialization = true)]
    public Task DidOpenAsync(DidOpenTextDocumentParams request)
    {
        var text = request.TextDocument?.Text;
        var uri = request.TextDocument?.Uri;
        if (uri == null || string.IsNullOrEmpty(text))
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            this.UpdateDocument(uri, text);
            this.PublishDiagnosticsIfPushMode(uri, text, skipBinding: true);
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/didChange", UseSingleObjectParameterDeserialization = true)]
    public Task DidChangeAsync(DidChangeTextDocumentParams request)
    {
        var text = request.ContentChanges?.LastOrDefault()?.Text;
        var uri = request.TextDocument?.Uri;
        if (uri == null || text == null)
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            this.UpdateDocument(uri, text);
            this.PublishDiagnosticsIfPushMode(uri, text, skipBinding: true);

            // Inter-file edits can change diagnostics in other open documents; ask the
            // client to re-pull them. Debounced so a burst of keystrokes coalesces.
            this.RequestDiagnosticRefresh(uri);
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/didSave", UseSingleObjectParameterDeserialization = true)]
    public Task DidSaveAsync(DidSaveTextDocumentParams request)
    {
        var text = request.Text;
        var uri = request.TextDocument?.Uri;
        if (uri == null || string.IsNullOrEmpty(text))
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            this.UpdateDocument(uri, text);

            // Pull clients already receive live binding diagnostics; only push clients need
            // the full pipeline run here.
            this.PublishDiagnosticsIfPushMode(uri, text, skipBinding: false);
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/didClose", UseSingleObjectParameterDeserialization = true)]
    public Task DidCloseAsync(DidCloseTextDocumentParams request)
    {
        var uri = request.TextDocument?.Uri;
        if (uri == null)
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            this.documentContentService.TryRemove(uri.ToString());
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/diagnostic", UseSingleObjectParameterDeserialization = true)]
    public async Task<object> DocumentDiagnosticAsync(DocumentDiagnosticParams request, CancellationToken cancellationToken)
    {
        var uri = request?.TextDocument?.Uri;
        if (uri == null)
        {
            return new FullDocumentDiagnosticReport { Items = Array.Empty<Diagnostic>() };
        }

        // Snapshot the current text and owning project under the gate, then run the (potentially
        // expensive) full binding pass off the gate so interactive requests are not blocked.
        string text = null;
        string filePath = null;
        ProjectState project = null;
        await this.gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            filePath = uri.GetFileSystemPath();
            project = !string.IsNullOrEmpty(filePath) ? this.workspaceState.GetProjectForFile(filePath) : null;
            if (this.documentContentService.TryGet(uri.ToString(), out var content))
            {
                text = content.SyntaxTree.Text.ToString();
            }
        }
        finally
        {
            this.gate.Release();
        }

        if (text == null)
        {
            return new FullDocumentDiagnosticReport { Items = Array.Empty<Diagnostic>() };
        }

        cancellationToken.ThrowIfCancellationRequested();

        DiagnosticComputationResult result;
        try
        {
            result = DocumentSyncHandler.ComputeDiagnostics(text, skipBinding: false, project, filePath, this.workspaceState);
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            // Issue #816: a binder/parser crash on partially valid input used to surface as a
            // per-file "Object reference not set to an instance of an object" popup, blocking
            // every other LSP feature for the file. Degrade to "no diagnostics" instead.
            LogHandlerException(nameof(DocumentDiagnosticAsync), ex);
            return new FullDocumentDiagnosticReport { Items = Array.Empty<Diagnostic>() };
        }

        cancellationToken.ThrowIfCancellationRequested();

        var resultId = ComputeResultId(result.Diagnostics);
        if (request.PreviousResultId != null && string.Equals(request.PreviousResultId, resultId, StringComparison.Ordinal))
        {
            return new UnchangedDocumentDiagnosticReport { ResultId = resultId };
        }

        return new FullDocumentDiagnosticReport
        {
            ResultId = resultId,
            Items = result.Diagnostics.ToList(),
        };
    }

    [JsonRpcMethod("workspace/didChangeWatchedFiles", UseSingleObjectParameterDeserialization = true)]
    public Task DidChangeWatchedFilesAsync(DidChangeWatchedFilesParams request)
    {
        if (request?.Changes == null)
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            foreach (var change in request.Changes)
            {
                var filePath = change.Uri?.GetFileSystemPath();
                if (string.IsNullOrEmpty(filePath))
                {
                    continue;
                }

                if (filePath.EndsWith(".gsproj", StringComparison.OrdinalIgnoreCase))
                {
                    this.HandleProjectFileChange(filePath, change.Type);
                }
                else if (filePath.EndsWith(".gs", StringComparison.OrdinalIgnoreCase))
                {
                    this.HandleSourceFileChange(filePath, change.Type);
                }
            }

            // External file/project changes can alter diagnostics in open documents.
            this.RequestDiagnosticRefresh();
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/hover", UseSingleObjectParameterDeserialization = true)]
    public Task<Hover> HoverAsync(HoverParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => HoverComputer.ComputeHover(content, request.Position),
            null,
            cancellationToken);

    [JsonRpcMethod("textDocument/definition", UseSingleObjectParameterDeserialization = true)]
    public Task<Location> DefinitionAsync(DefinitionParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => DefinitionComputer.ComputeDefinition(request.TextDocument.Uri, content, request.Position),
            null,
            cancellationToken);

    [JsonRpcMethod("textDocument/references", UseSingleObjectParameterDeserialization = true)]
    public Task<Location[]> ReferencesAsync(ReferenceParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => ReferencesComputer.ComputeReferences(request.TextDocument.Uri, content, request.Position, request.Context?.IncludeDeclaration ?? false).ToArray(),
            Array.Empty<Location>(),
            cancellationToken);

    [JsonRpcMethod("textDocument/documentHighlight", UseSingleObjectParameterDeserialization = true)]
    public Task<DocumentHighlight[]> DocumentHighlightAsync(DocumentHighlightParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) =>
            {
                var tokens = ReferencesComputer.ComputeReferenceTokens(content, request.Position, includeDeclaration: true);
                return tokens.Select(t => new DocumentHighlight
                {
                    Range = SemanticLookup.ToRange(t),
                    Kind = DocumentHighlightKind.Text,
                }).ToArray();
            },
            Array.Empty<DocumentHighlight>(),
            cancellationToken);

    [JsonRpcMethod("textDocument/documentSymbol", UseSingleObjectParameterDeserialization = true)]
    public Task<SymbolInformationOrDocumentSymbol[]> DocumentSymbolAsync(DocumentSymbolParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => DocumentSymbolComputer.ComputeDocumentSymbols(content).ToArray(),
            Array.Empty<SymbolInformationOrDocumentSymbol>(),
            cancellationToken);

    [JsonRpcMethod("workspace/symbol", UseSingleObjectParameterDeserialization = true)]
    public Task<WorkspaceSymbol[]> WorkspaceSymbolAsync(WorkspaceSymbolParams request, CancellationToken cancellationToken = default)
        => this.ReadWorkspaceAsync(
            (docs, ct) =>
            {
                var query = request.Query ?? string.Empty;
                var results = new List<WorkspaceSymbol>();
                foreach (var pair in docs)
                {
                    ct.ThrowIfCancellationRequested();
                    WorkspaceSymbolHandler.CollectSymbols(results, pair.Key, pair.Value, query);
                }

                return results.ToArray();
            },
            Array.Empty<WorkspaceSymbol>(),
            cancellationToken);

    [JsonRpcMethod("textDocument/completion", UseSingleObjectParameterDeserialization = true)]
    public Task<CompletionList> CompletionAsync(CompletionParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => new CompletionList(CompletionComputer.ComputeCompletions(content, request.Position)),
            new CompletionList(),
            cancellationToken);

    [JsonRpcMethod("textDocument/signatureHelp", UseSingleObjectParameterDeserialization = true)]
    public Task<SignatureHelp> SignatureHelpAsync(SignatureHelpParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => SignatureHelpComputer.ComputeSignatureHelp(content, request.Position),
            null,
            cancellationToken);

    [JsonRpcMethod("textDocument/rename", UseSingleObjectParameterDeserialization = true)]
    public Task<WorkspaceEdit> RenameAsync(RenameParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => RenameComputer.ComputeRename(request.TextDocument.Uri, content, request.Position, request.NewName),
            null,
            cancellationToken);

    [JsonRpcMethod("textDocument/prepareRename", UseSingleObjectParameterDeserialization = true)]
    public Task<Range> PrepareRenameAsync(PrepareRenameParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => this.ComputePrepareRename(content, request),
            null,
            cancellationToken);

    [JsonRpcMethod("textDocument/codeAction", UseSingleObjectParameterDeserialization = true)]
    public Task<CommandOrCodeActionContainer> CodeActionAsync(CodeActionParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => CodeActionComputer.ComputeCodeActions(request.TextDocument.Uri, content, request.Range),
            new CommandOrCodeActionContainer(),
            cancellationToken);

    [JsonRpcMethod("textDocument/codeLens", UseSingleObjectParameterDeserialization = true)]
    public Task<CodeLens[]> CodeLensAsync(CodeLensParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => CodeLensComputer.ComputeLenses(content, request.TextDocument.Uri?.ToString()).ToArray(),
            Array.Empty<CodeLens>(),
            cancellationToken);

    [JsonRpcMethod("gsharp/discoverTests")]
    public Task<TestDiscoveryItem[]> DiscoverTestsAsync(CancellationToken cancellationToken = default)
        => this.ReadTestSnapshotAsync(
            (sources, ct) => GroupDiscoveredTests(sources, ct),
            Array.Empty<TestDiscoveryItem>(),
            cancellationToken);

    // Builds the Test Explorer tree: a top-level grouping node per project, labelled
    // "<project-name> (<tfm>)" (matching the C# Dev Kit presentation), whose children are
    // the class/function items discovered in that project's sources. Loose files that
    // belong to no project are emitted at the top level, ungrouped, preserving prior
    // behavior for single-file scenarios.
    private static TestDiscoveryItem[] GroupDiscoveredTests(IReadOnlyList<TestSource> sources, CancellationToken ct)
    {
        var results = new List<TestDiscoveryItem>();
        var grouped = new Dictionary<string, (string Label, string ProjectFile, List<TestDiscoveryItem> Children)>(StringComparer.OrdinalIgnoreCase);

        foreach (var source in sources)
        {
            ct.ThrowIfCancellationRequested();
            var items = TestDiscoveryComputer.ComputeTests(source.Uri, source.Tree);
            if (items.Count == 0)
            {
                continue;
            }

            if (string.IsNullOrEmpty(source.ProjectFile))
            {
                // Loose / project-less file: keep its items at the top level.
                results.AddRange(items);
                continue;
            }

            if (!grouped.TryGetValue(source.ProjectFile, out var bucket))
            {
                bucket = (source.ProjectLabel, source.ProjectFile, new List<TestDiscoveryItem>());
                grouped[source.ProjectFile] = bucket;
            }

            bucket.Children.AddRange(items);
        }

        foreach (var bucket in grouped.Values.OrderBy(b => b.Label, StringComparer.Ordinal))
        {
            results.Add(new TestDiscoveryItem
            {
                Id = "project:" + bucket.ProjectFile,
                Label = bucket.Label,
                Uri = DocumentUri.FromFileSystemPath(bucket.ProjectFile).ToString(),
                Line = 0,
                Filter = null,
                ProjectFile = bucket.ProjectFile,
                Children = bucket.Children.ToArray(),
            });
        }

        return results.ToArray();
    }

    [JsonRpcMethod("textDocument/inlayHint", UseSingleObjectParameterDeserialization = true)]
    public Task<InlayHint[]> InlayHintAsync(InlayHintParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => InlayHintComputer.ComputeHints(content).ToArray(),
            Array.Empty<InlayHint>(),
            cancellationToken);

    [JsonRpcMethod("textDocument/foldingRange", UseSingleObjectParameterDeserialization = true)]
    public Task<FoldingRange[]> FoldingRangeAsync(FoldingRangeParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => FoldingComputer.ComputeFoldings(content).ToArray(),
            Array.Empty<FoldingRange>(),
            cancellationToken);

    [JsonRpcMethod("textDocument/selectionRange", UseSingleObjectParameterDeserialization = true)]
    public Task<SelectionRange[]> SelectionRangeAsync(SelectionRangeParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => request.Positions == null
                ? Array.Empty<SelectionRange>()
                : request.Positions.Select(p => SelectionRangeComputer.ComputeSelectionRange(content, p)).ToArray(),
            Array.Empty<SelectionRange>(),
            cancellationToken);

    [JsonRpcMethod("textDocument/semanticTokens/full", UseSingleObjectParameterDeserialization = true)]
    public Task<SemanticTokens> SemanticTokensFullAsync(SemanticTokensParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => this.ComputeSemanticTokens(content),
            EmptySemanticTokens(),
            cancellationToken);

    [JsonRpcMethod("textDocument/semanticTokens/range", UseSingleObjectParameterDeserialization = true)]
    public Task<SemanticTokens> SemanticTokensRangeAsync(SemanticTokensRangeParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => this.ComputeSemanticTokens(content),
            EmptySemanticTokens(),
            cancellationToken);

    [JsonRpcMethod("textDocument/formatting", UseSingleObjectParameterDeserialization = true)]
    public Task<TextEdit[]> FormattingAsync(DocumentFormattingParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => this.FormatDocument(content, request.Options),
            Array.Empty<TextEdit>(),
            cancellationToken);

    // Range formatting and on-type formatting are not advertised in ServerCapabilitiesFactory
    // (see issue #1660): implementing correct partial-range formatting on top of the
    // whole-token-stream FormattingEngine would require re-deriving per-statement offsets and
    // splicing them back into an unrelated slice of the document, which is substantially more
    // risk than value for a formatter that already produces a correct, idempotent whole-document
    // result. These handlers are kept registered as safe no-ops in case a non-conformant client
    // invokes them despite the missing capability; they intentionally do not fall back to a
    // whole-document format, since that would reintroduce the whole-document mangling this fix
    // removes for the range/on-type case.
    [JsonRpcMethod("textDocument/rangeFormatting", UseSingleObjectParameterDeserialization = true)]
    public Task<TextEdit[]> RangeFormattingAsync(DocumentRangeFormattingParams request, CancellationToken cancellationToken = default)
        => Task.FromResult(Array.Empty<TextEdit>());

    [JsonRpcMethod("textDocument/onTypeFormatting", UseSingleObjectParameterDeserialization = true)]
    public Task<TextEdit[]> OnTypeFormattingAsync(DocumentOnTypeFormattingParams request, CancellationToken cancellationToken = default)
        => Task.FromResult(Array.Empty<TextEdit>());

    [JsonRpcMethod("textDocument/implementation", UseSingleObjectParameterDeserialization = true)]
    public Task<Location[]> ImplementationAsync(ImplementationParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => this.ComputeImplementation(content, request),
            Array.Empty<Location>(),
            cancellationToken);

    [JsonRpcMethod("textDocument/typeDefinition", UseSingleObjectParameterDeserialization = true)]
    public Task<Location[]> TypeDefinitionAsync(TypeDefinitionParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => this.ComputeTypeDefinition(content, request),
            Array.Empty<Location>(),
            cancellationToken);

    [JsonRpcMethod("textDocument/linkedEditingRange", UseSingleObjectParameterDeserialization = true)]
    public Task<LinkedEditingRanges> LinkedEditingRangeAsync(LinkedEditingRangeParams request, CancellationToken cancellationToken = default)
        => this.ReadDocumentAsync(
            request.TextDocument,
            (content, ct) => this.ComputeLinkedEditingRanges(content, request),
            null,
            cancellationToken);

    // Mutating ("write") path. Mirrors Roslyn's RequestExecutionQueue handling of
    // MutatesSolutionState=true requests: the gate is held for the whole (brief,
    // parse-only) body so the mutation is fully applied before any later request
    // captures its snapshot. didOpen/didChange/didSave/didClose/watchedFiles use this.
    private async Task<T> GuardAsync<T>(Func<T> body, [System.Runtime.CompilerServices.CallerMemberName] string caller = null)
    {
        await this.gate.WaitAsync().ConfigureAwait(false);
        try
        {
            try
            {
                return body();
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch (Exception ex)
            {
                // Issue #816: handler crashes (e.g., NRE deep in symbol resolution when
                // editing a file whose syntax outpaces the bundled LS) used to surface as
                // a per-request "Object reference not set to an instance of an object"
                // popup for every diagnostic / inlayHint / codeLens / semanticTokens pull
                // until the user restarted the editor. Swallow the exception, log it to
                // structured logging for diagnosis, and return a safe default (null for reference
                // types — LSP clients treat that as "no result" rather than an error).
                LogHandlerException(caller, ex);
                return default;
            }
        }
        finally
        {
            this.gate.Release();
        }
    }

    // Non-mutating ("read") path. Mirrors Roslyn's RequestExecutionQueue handling of
    // non-mutating requests: the request's snapshot (here, the immutable DocumentContent)
    // is captured serially under the gate so it reflects every prior mutation, and the
    // gate is held only for that O(1) capture. The actual computation then runs OFF the
    // gate on the thread pool via Task.Run so that:
    //   * concurrent read requests never serialize behind one another, and
    //   * a long-running read (e.g. the first cold full-workspace bind, ~17s on a large
    //     workspace) never blocks unrelated reads or, crucially, a didChange while typing.
    // Roslyn likewise dispatches non-mutating work via Task.Run "to enforce parallelizability".
    // CancellationToken is honored end-to-end: StreamJsonRpc maps the LSP $/cancelRequest
    // notification onto this token, so superseded hovers/highlights abort instead of
    // consuming a thread-pool thread to completion.
    private async Task<T> ReadDocumentAsync<T>(
        TextDocumentIdentifier identifier,
        Func<DocumentContent, CancellationToken, T> compute,
        T missing,
        CancellationToken cancellationToken,
        [System.Runtime.CompilerServices.CallerMemberName] string caller = null)
    {
        DocumentContent content;
        try
        {
            await this.gate.WaitAsync(cancellationToken).ConfigureAwait(false);
            try
            {
                if (!this.TryGet(identifier, out content) || content == null)
                {
                    return missing;
                }
            }
            finally
            {
                this.gate.Release();
            }
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            // Issue #816: even the snapshot lookup can throw (a faulted content service).
            // Degrade to "no result" rather than surfacing an error popup to the client.
            LogHandlerException(caller, ex);
            return missing;
        }

        return await Task.Run(
            () =>
            {
                try
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    return compute(content, cancellationToken);
                }
                catch (OperationCanceledException)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    LogHandlerException(caller, ex);
                    return missing;
                }
            },
            cancellationToken).ConfigureAwait(false);
    }

    // Non-mutating read over the whole open-document set (workspace symbols, test
    // discovery). The document list is snapshotted under the gate, then enumerated and
    // computed off the gate, identical in spirit to <see cref="ReadDocumentAsync{T}"/>.
    private async Task<T> ReadWorkspaceAsync<T>(
        Func<IReadOnlyList<KeyValuePair<string, DocumentContent>>, CancellationToken, T> compute,
        T missing,
        CancellationToken cancellationToken,
        [System.Runtime.CompilerServices.CallerMemberName] string caller = null)
    {
        IReadOnlyList<KeyValuePair<string, DocumentContent>> documents;
        try
        {
            await this.gate.WaitAsync(cancellationToken).ConfigureAwait(false);
            try
            {
                documents = this.documentContentService.AllDocuments.ToList();
            }
            finally
            {
                this.gate.Release();
            }
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            LogHandlerException(caller, ex);
            return missing;
        }

        return await Task.Run(
            () =>
            {
                try
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    return compute(documents, cancellationToken);
                }
                catch (OperationCanceledException)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    LogHandlerException(caller, ex);
                    return missing;
                }
            },
            cancellationToken).ConfigureAwait(false);
    }

    // Non-mutating read over the whole workspace's test-bearing source files (the
    // gsharp/discoverTests request). Unlike ReadWorkspaceAsync — which only sees
    // currently-open editor buffers — this snapshots every parsed source tree across
    // all discovered projects, then overlays open buffers so unsaved edits win. This
    // is what makes the Test Explorer reflect every test in the workspace (even in
    // files that have never been opened) after a build. The snapshot is captured under
    // the gate; the (immutable) syntax trees are walked off the gate on the thread pool.
    private async Task<T> ReadTestSnapshotAsync<T>(
        Func<IReadOnlyList<TestSource>, CancellationToken, T> compute,
        T missing,
        CancellationToken cancellationToken,
        [System.Runtime.CompilerServices.CallerMemberName] string caller = null)
    {
        IReadOnlyList<TestSource> sources;
        try
        {
            await this.gate.WaitAsync(cancellationToken).ConfigureAwait(false);
            try
            {
                sources = this.SnapshotTestSources_NoLock();
            }
            finally
            {
                this.gate.Release();
            }
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            LogHandlerException(caller, ex);
            return missing;
        }

        return await Task.Run(
            () =>
            {
                try
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    return compute(sources, cancellationToken);
                }
                catch (OperationCanceledException)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    LogHandlerException(caller, ex);
                    return missing;
                }
            },
            cancellationToken).ConfigureAwait(false);
    }

    // Builds the de-duplicated set of test sources used by discovery: every project
    // source tree keyed by absolute path (carrying its owning project's identity), with
    // open editor buffers overlaid on top so in-flight edits are reflected and loose
    // (project-less) open files are included.
    private IReadOnlyList<TestSource> SnapshotTestSources_NoLock()
    {
        var byPath = new Dictionary<string, TestSource>(StringComparer.OrdinalIgnoreCase);

        foreach (var project in this.workspaceState.Projects)
        {
            var projectFile = project.ProjectFilePath;
            var projectLabel = ProjectLabel(project);
            foreach (var file in project.SourceFiles)
            {
                if (project.TryGetSyntaxTree(file, out var tree) && tree != null)
                {
                    var path = PathKeyFor(tree, file);
                    byPath[path] = new TestSource(DocumentUri.FromFileSystemPath(file).ToString(), tree, projectFile, projectLabel);
                }
            }
        }

        foreach (var pair in this.documentContentService.AllDocuments)
        {
            var tree = pair.Value?.SyntaxTree;
            if (tree == null)
            {
                continue;
            }

            // Open buffers win over the on-disk project tree so the explorer reflects
            // unsaved edits; preserve the client's own URI string so run-at-cursor
            // matching stays byte-for-byte identical to the editor's document URI.
            var path = PathKeyFor(tree, pair.Key);

            // Reuse the project association captured above when the file is a known project
            // source; otherwise resolve it (e.g. a freshly created, not-yet-globbed file).
            string projectFile = null;
            string projectLabel = null;
            if (byPath.TryGetValue(path, out var existing))
            {
                projectFile = existing.ProjectFile;
                projectLabel = existing.ProjectLabel;
            }
            else
            {
                var owning = this.workspaceState.GetProjectForFile(path);
                if (owning != null)
                {
                    projectFile = owning.ProjectFilePath;
                    projectLabel = ProjectLabel(owning);
                }
            }

            byPath[path] = new TestSource(pair.Key, tree, projectFile, projectLabel);
        }

        return byPath.Values
            .OrderBy(s => s.Uri, StringComparer.Ordinal)
            .ToList();
    }

    private static string ProjectLabel(ProjectState project)
    {
        var name = Path.GetFileNameWithoutExtension(project.ProjectFilePath);
        var tfm = project.TargetFramework;
        return string.IsNullOrEmpty(tfm) ? name : $"{name} ({tfm})";
    }

    private static string PathKeyFor(SyntaxTree tree, string fallback)
    {
        var fileName = tree?.Text?.FileName;
        var candidate = !string.IsNullOrEmpty(fileName) ? fileName : fallback;
        try
        {
            return Path.GetFullPath(candidate);
        }
        catch (Exception)
        {
            return candidate ?? string.Empty;
        }
    }

    // A single test-bearing source: its emitted URI, parsed (immutable) tree, and the
    // identity of the owning project (null for loose files) used to build the grouping node.
    private readonly struct TestSource
    {
        public TestSource(string uri, SyntaxTree tree, string projectFile, string projectLabel)
        {
            Uri = uri;
            Tree = tree;
            ProjectFile = projectFile;
            ProjectLabel = projectLabel;
        }

        public string Uri { get; }

        public SyntaxTree Tree { get; }

        public string ProjectFile { get; }

        public string ProjectLabel { get; }
    }

    private static SemanticTokens EmptySemanticTokens()
        => new SemanticTokens { Data = System.Collections.Immutable.ImmutableArray<int>.Empty };

    private void LogHandlerException(string handler, Exception ex)
    {
        try
        {
            this.logger.LogError($"{handler ?? "handler"} failed: {ex.GetType().FullName}: {ex.Message}", ex);
        }
        catch
        {
            // Logging is best-effort; never let a logger failure tear down the server.
        }
    }

    private bool TryGet(TextDocumentIdentifier identifier, out DocumentContent content)
    {
        content = null;
        var uri = identifier?.Uri;
        return uri != null && this.documentContentService.TryGet(uri.ToString(), out content);
    }

    private void UpdateDocument(DocumentUri uri, string text)
    {
        var filePath = uri.GetFileSystemPath();
        var project = !string.IsNullOrEmpty(filePath) ? this.workspaceState.GetProjectForFile(filePath) : null;
        if (project != null)
        {
            project.UpdateFile(filePath, text);
        }

        // Parse-only content (no binding) feeds the content service used by other features;
        // diagnostics are produced on demand by the textDocument/diagnostic pull handler.
        var result = DocumentSyncHandler.ComputeDiagnostics(text, skipBinding: true, project, filePath, this.workspaceState);
        this.documentContentService.AddOrUpdate(uri.ToString(), result.Content);
    }

    private void PublishDiagnosticsIfPushMode(DocumentUri uri, string text, bool skipBinding)
    {
        // Clients advertising pull diagnostics request them via textDocument/diagnostic, so push
        // is suppressed to avoid double reporting. Older push-only clients still get notifications.
        if (this.clientSupportsPullDiagnostics)
        {
            return;
        }

        var filePath = uri.GetFileSystemPath();
        var project = !string.IsNullOrEmpty(filePath) ? this.workspaceState.GetProjectForFile(filePath) : null;
        var result = DocumentSyncHandler.ComputeDiagnostics(text, skipBinding, project, filePath, this.workspaceState);

        this.rpc?.NotifyWithParameterObjectAsync(
            "textDocument/publishDiagnostics",
            new PublishDiagnosticsParams { Uri = uri, Diagnostics = result.Diagnostics });
    }

    private void DetectClientDiagnosticCapabilities(JsonElement capabilities)
    {
        try
        {
            if (capabilities.ValueKind == JsonValueKind.Object)
            {
                if (capabilities.TryGetProperty("textDocument", out var textDocument)
                    && textDocument.ValueKind == JsonValueKind.Object
                    && textDocument.TryGetProperty("diagnostic", out var diagnostic)
                    && diagnostic.ValueKind == JsonValueKind.Object)
                {
                    this.clientSupportsPullDiagnostics = true;
                }

                if (capabilities.TryGetProperty("workspace", out var workspace)
                    && workspace.ValueKind == JsonValueKind.Object
                    && workspace.TryGetProperty("diagnostics", out var wsDiagnostics)
                    && wsDiagnostics.ValueKind == JsonValueKind.Object
                    && wsDiagnostics.TryGetProperty("refreshSupport", out var refreshSupport)
                    && refreshSupport.ValueKind == JsonValueKind.True)
                {
                    this.clientSupportsDiagnosticRefresh = true;
                }
            }
        }
        catch
        {
            // Capability probing is best-effort; absence of pull support falls back to push.
        }
    }

    /// <summary>
    /// Reads the extension's <c>formattingIndentSize</c>/<c>formattingUseTabs</c> initialization
    /// options (see serverManager.ts) to compute the indent unit used when a formatting request
    /// does not itself supply <see cref="FormattingOptions"/>.
    /// </summary>
    private static string ResolveDefaultFormattingIndent(JsonElement initializationOptions)
    {
        const string fallback = "  ";
        try
        {
            if (initializationOptions.ValueKind != JsonValueKind.Object)
            {
                return fallback;
            }

            var useTabs = initializationOptions.TryGetProperty("formattingUseTabs", out var useTabsElement)
                && useTabsElement.ValueKind == JsonValueKind.True;

            if (useTabs)
            {
                return "\t";
            }

            if (initializationOptions.TryGetProperty("formattingIndentSize", out var sizeElement)
                && sizeElement.ValueKind == JsonValueKind.Number
                && sizeElement.TryGetInt32(out var size)
                && size > 0)
            {
                return new string(' ', size);
            }

            return fallback;
        }
        catch
        {
            // Initialization option parsing is best-effort; fall back to the two-space default.
            return fallback;
        }
    }

    private void RequestDiagnosticRefresh(DocumentUri changedUri)
    {
        if (!this.clientSupportsPullDiagnostics || !this.clientSupportsDiagnosticRefresh)
        {
            return;
        }

        // Single-file edits do not affect other documents, so skip refreshes for documents that
        // are not part of a multi-file project.
        var filePath = changedUri.GetFileSystemPath();
        var project = !string.IsNullOrEmpty(filePath) ? this.workspaceState.GetProjectForFile(filePath) : null;
        if (project == null || project.SourceFiles.Count <= 1)
        {
            return;
        }

        this.RequestDiagnosticRefresh();
    }

    private void RequestDiagnosticRefresh()
    {
        if (!this.clientSupportsDiagnosticRefresh)
        {
            return;
        }

        // Debounce: coalesce bursts of changes into a single workspace/diagnostic/refresh request.
        lock (this.refreshLock)
        {
            this.refreshTimer ??= new Timer(_ => this.SendDiagnosticRefresh(), null, Timeout.Infinite, Timeout.Infinite);
            this.refreshTimer.Change(500, Timeout.Infinite);
        }
    }

    private void SendDiagnosticRefresh()
    {
        try
        {
            this.rpc?.InvokeAsync("workspace/diagnostic/refresh");
        }
        catch
        {
            // The client may have disconnected; refresh is best-effort.
        }
    }

    private static string ComputeResultId(IReadOnlyList<Diagnostic> diagnostics)
    {
        var builder = new StringBuilder();
        foreach (var d in diagnostics)
        {
            builder.Append((int)d.Severity).Append('|');
            if (d.Range != null)
            {
                builder.Append(d.Range.Start?.Line).Append(',').Append(d.Range.Start?.Character).Append('-')
                    .Append(d.Range.End?.Line).Append(',').Append(d.Range.End?.Character);
            }

            builder.Append('|').Append(d.Code?.Value).Append('|').Append(d.Message).Append('\n');
        }

        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(builder.ToString()));
        return Convert.ToHexString(bytes);
    }

    private SemanticTokens ComputeSemanticTokens(DocumentContent content)
    {
        var document = new SemanticTokensDocument(SemanticTokensHandler.Legend);
        var builder = document.Create();
        SemanticTokensComputer.Tokenize(builder, content);
        builder.Commit();
        return document.GetSemanticTokens();
    }

    private TextEdit[] FormatDocument(DocumentContent content, FormattingOptions options)
    {
        var sourceText = content.SyntaxTree.Text;
        var originalText = sourceText.ToString();
        var indent = ResolveIndent(options, this.defaultFormattingIndent);
        var formatted = FormattingEngine.Format(originalText, indent);
        if (formatted == originalText)
        {
            return Array.Empty<TextEdit>();
        }

        var lastLine = sourceText.Lines.Length - 1;
        var lastChar = sourceText.Lines[lastLine].Length;
        return new[]
        {
            new TextEdit
            {
                Range = new Range(new Position(0, 0), new Position(lastLine, lastChar)),
                NewText = formatted,
            },
        };
    }

    /// <summary>
    /// Resolves the indent unit for a formatting request: the request's own
    /// <see cref="FormattingOptions"/> (tabSize/insertSpaces, as sent by the editor per the LSP
    /// spec) take precedence, falling back to the server-wide default derived from the
    /// extension's initialization options when the request supplies none.
    /// </summary>
    private static string ResolveIndent(FormattingOptions options, string fallback)
    {
        if (options == null || options.TabSize <= 0)
        {
            return fallback;
        }

        return options.InsertSpaces ? new string(' ', options.TabSize) : "\t";
    }

    private Range ComputePrepareRename(DocumentContent content, PrepareRenameParams request)
    {
        var offset = SemanticLookup.ToOffset(content, request.Position);
        var token = SemanticLookup.FindTokenAt(content.SyntaxTree, offset);
        if (token == null || token.Kind != SyntaxKind.IdentifierToken)
        {
            return null;
        }

        var compilation = TryGetCompilation(content);
        if (compilation == null)
        {
            return null;
        }

        var symbol = SemanticLookup.ResolveSymbol(compilation, token);
        return SemanticLookup.CanRename(symbol) ? SemanticLookup.ToRange(token) : null;
    }

    private Location[] ComputeImplementation(DocumentContent content, ImplementationParams request)
    {
        var offset = SemanticLookup.ToOffset(content, request.Position);
        var token = SemanticLookup.FindTokenAt(content.SyntaxTree, offset);
        if (token == null || token.Kind != SyntaxKind.IdentifierToken)
        {
            return Array.Empty<Location>();
        }

        var compilation = TryGetCompilation(content);
        if (compilation == null)
        {
            return Array.Empty<Location>();
        }

        var symbol = SemanticLookup.ResolveSymbol(compilation, token);
        if (symbol is not InterfaceSymbol iface)
        {
            return Array.Empty<Location>();
        }

        var locations = new List<Location>();
        foreach (var structSym in compilation.GlobalScope.Structs)
        {
            if (structSym.Interfaces.Contains(iface) && structSym.Declaration != null)
            {
                locations.Add(new Location
                {
                    Uri = request.TextDocument.Uri,
                    Range = SemanticLookup.ToRange(structSym.Declaration.Identifier),
                });
            }
        }

        return locations.ToArray();
    }

    private Location[] ComputeTypeDefinition(DocumentContent content, TypeDefinitionParams request)
    {
        var offset = SemanticLookup.ToOffset(content, request.Position);
        var token = SemanticLookup.FindTokenAt(content.SyntaxTree, offset);
        if (token == null || token.Kind != SyntaxKind.IdentifierToken)
        {
            return Array.Empty<Location>();
        }

        var compilation = TryGetCompilation(content);
        if (compilation == null)
        {
            return Array.Empty<Location>();
        }

        var symbol = SemanticLookup.ResolveSymbol(compilation, token);
        TypeSymbol typeSymbol = symbol switch
        {
            ParameterSymbol ps => ps.Type,
            VariableSymbol vs => vs.Type,
            FunctionSymbol fs => fs.Type,
            _ => null,
        };

        if (typeSymbol == null)
        {
            return Array.Empty<Location>();
        }

        var firstRef = SemanticLookup.FindReferences(compilation, typeSymbol).FirstOrDefault();
        if (firstRef == null)
        {
            return Array.Empty<Location>();
        }

        return new[]
        {
            new Location
            {
                Uri = request.TextDocument.Uri,
                Range = SemanticLookup.ToRange(firstRef),
            },
        };
    }

    private LinkedEditingRanges ComputeLinkedEditingRanges(DocumentContent content, LinkedEditingRangeParams request)
    {
        var tree = content.SyntaxTree;
        var offset = SemanticLookup.ToOffset(content, request.Position);
        var token = SemanticLookup.FindTokenAt(tree, offset);
        if (token == null || token.Kind != SyntaxKind.IdentifierToken)
        {
            return null;
        }

        var compilation = TryGetCompilation(content);
        if (compilation == null)
        {
            return null;
        }

        var symbol = SemanticLookup.ResolveSymbol(compilation, token);
        if (!SemanticLookup.CanRename(symbol))
        {
            return null;
        }

        var references = SemanticLookup.FindReferences(compilation, symbol).ToList();
        if (references.Count == 0)
        {
            return null;
        }

        return new LinkedEditingRanges
        {
            Ranges = references.Select(SemanticLookup.ToRange).ToList(),
            WordPattern = @"[a-zA-Z_]\w*",
        };
    }

    private void HandleProjectFileChange(string filePath, FileChangeType changeType)
    {
        switch (changeType)
        {
            case FileChangeType.Created:
                var discovered = ProjectDiscovery.DiscoverProject(filePath);
                if (discovered != null)
                {
                    var project = this.workspaceState.AddProject(discovered.ProjectFilePath);
                    project.ProjectReferences = discovered.ProjectReferences;
                    project.ReferenceSourcePath = discovered.ReferenceSourcePath;
                    project.References = discovered.References;
                    foreach (var source in discovered.SourceFiles)
                    {
                        project.AddFileFromDisk(source);
                        this.workspaceState.RegisterFile(source, project);
                    }
                }

                break;

            case FileChangeType.Changed:
                var existing = this.workspaceState.GetProject(filePath);
                var rediscovered = existing != null ? ProjectDiscovery.DiscoverProject(filePath) : null;
                if (rediscovered != null)
                {
                    existing.ProjectReferences = rediscovered.ProjectReferences;
                    existing.ReferenceSourcePath = rediscovered.ReferenceSourcePath;
                    existing.References = rediscovered.References;
                    foreach (var source in rediscovered.SourceFiles)
                    {
                        if (!existing.ContainsFile(source))
                        {
                            existing.AddFileFromDisk(source);
                            this.workspaceState.RegisterFile(source, existing);
                        }
                    }

                    foreach (var oldFile in existing.SourceFiles.ToList())
                    {
                        if (!rediscovered.SourceFiles.Contains(oldFile))
                        {
                            existing.RemoveFile(oldFile);
                            this.workspaceState.UnregisterFile(oldFile);
                        }
                    }
                }

                break;

            case FileChangeType.Deleted:
                this.workspaceState.RemoveProject(filePath);
                break;
        }
    }

    private void HandleSourceFileChange(string filePath, FileChangeType changeType)
    {
        switch (changeType)
        {
            case FileChangeType.Created:
                var project = this.FindOwningProject(filePath);
                if (project != null)
                {
                    project.AddFileFromDisk(filePath);
                    this.workspaceState.RegisterFile(filePath, project);
                }

                break;

            case FileChangeType.Deleted:
                var owning = this.workspaceState.GetProjectForFile(filePath);
                if (owning != null)
                {
                    owning.RemoveFile(filePath);
                    this.workspaceState.UnregisterFile(filePath);
                }

                break;
        }
    }

    private ProjectState FindOwningProject(string filePath)
    {
        var fileDir = Path.GetDirectoryName(Path.GetFullPath(filePath));
        foreach (var project in this.workspaceState.Projects)
        {
            if (fileDir != null && fileDir.StartsWith(project.ProjectDirectory, StringComparison.OrdinalIgnoreCase))
            {
                return project;
            }
        }

        return this.workspaceState.GetOrCreateImplicitProject();
    }

    private static GSharp.Core.CodeAnalysis.Compilation.Compilation TryGetCompilation(DocumentContent content)
    {
        try
        {
            return content.Project?.GetCompilation()
                ?? new GSharp.Core.CodeAnalysis.Compilation.Compilation(content.SyntaxTree);
        }
        catch
        {
            return null;
        }
    }
}
