// <auto-generated/>
// StreamJsonRpc dispatch target for the GSharp language server. Marked auto-generated to opt
// out of StyleCop documentation/ordering rules; this is protocol plumbing, not product logic.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using GSharp.Core.CodeAnalysis.Symbols;
using GSharp.Core.CodeAnalysis.Syntax;
using GSharp.LanguageServer.Protocol;
using StreamJsonRpc;
using Range = GSharp.LanguageServer.Protocol.Range;

namespace GSharp.LanguageServer.Server;

/// <summary>
/// Hosts the LSP method handlers and dispatches them through StreamJsonRpc. All handlers are
/// serialized through a single gate so document mutations are applied before subsequent reads.
/// </summary>
public sealed class LspServer
{
    private readonly DocumentContentService documentContentService;
    private readonly WorkspaceState workspaceState;
    private readonly SemaphoreSlim gate = new SemaphoreSlim(1, 1);
    private readonly TaskCompletionSource<int> exitSource = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
    private readonly object refreshLock = new object();

    private JsonRpc rpc;
    private bool shutdownRequested;
    private bool clientSupportsPullDiagnostics;
    private bool clientSupportsDiagnosticRefresh;
    private Timer refreshTimer;

    public LspServer(DocumentContentService documentContentService, WorkspaceState workspaceState)
    {
        this.documentContentService = documentContentService;
        this.workspaceState = workspaceState;
    }

    /// <summary>Gets a task that completes when the client sends the <c>exit</c> notification.</summary>
    public Task<int> WaitForExit => this.exitSource.Task;

    /// <summary>Associates the JsonRpc connection used to send notifications to the client.</summary>
    /// <param name="connection">The active <see cref="JsonRpc"/> connection.</param>
    public void Attach(JsonRpc connection)
    {
        this.rpc = connection;
        connection.Disconnected += (_, _) => this.exitSource.TrySetResult(this.shutdownRequested ? 0 : 1);
    }

    [JsonRpcMethod("initialize", UseSingleObjectParameterDeserialization = true)]
    public Task<InitializeResult> InitializeAsync(InitializeParams request)
    {
        var rootPath = request?.RootPath ?? request?.RootUri?.GetFileSystemPath();
        this.DetectClientDiagnosticCapabilities(request?.Capabilities ?? default);
        try
        {
            WorkspaceInitializer.Initialize(this.workspaceState, rootPath);
        }
        catch
        {
            // Workspace discovery is best-effort; single-file editing still works without it.
        }

        return Task.FromResult(new InitializeResult
        {
            Capabilities = ServerCapabilitiesFactory.Create(),
            ServerInfo = new ServerInfo { Name = "GSharp Language Server", Version = "1.0.0" },
        });
    }

    [JsonRpcMethod("initialized")]
    public void Initialized(JsonElement @params)
    {
        // No-op: capabilities are advertised statically in the initialize result.
    }

    [JsonRpcMethod("shutdown")]
    public object Shutdown()
    {
        this.shutdownRequested = true;
        return null;
    }

    [JsonRpcMethod("exit")]
    public void Exit()
    {
        this.exitSource.TrySetResult(this.shutdownRequested ? 0 : 1);
    }

    [JsonRpcMethod("textDocument/didOpen", UseSingleObjectParameterDeserialization = true)]
    public Task DidOpenAsync(DidOpenTextDocumentParams request)
    {
        var text = request.TextDocument?.Text;
        var uri = request.TextDocument?.Uri;
        if (uri == null || string.IsNullOrEmpty(text))
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            this.UpdateDocument(uri, text);
            this.PublishDiagnosticsIfPushMode(uri, text, skipBinding: true);
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/didChange", UseSingleObjectParameterDeserialization = true)]
    public Task DidChangeAsync(DidChangeTextDocumentParams request)
    {
        var text = request.ContentChanges?.LastOrDefault()?.Text;
        var uri = request.TextDocument?.Uri;
        if (uri == null || text == null)
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            this.UpdateDocument(uri, text);
            this.PublishDiagnosticsIfPushMode(uri, text, skipBinding: true);

            // Inter-file edits can change diagnostics in other open documents; ask the
            // client to re-pull them. Debounced so a burst of keystrokes coalesces.
            this.RequestDiagnosticRefresh(uri);
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/didSave", UseSingleObjectParameterDeserialization = true)]
    public Task DidSaveAsync(DidSaveTextDocumentParams request)
    {
        var text = request.Text;
        var uri = request.TextDocument?.Uri;
        if (uri == null || string.IsNullOrEmpty(text))
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            this.UpdateDocument(uri, text);

            // Pull clients already receive live binding diagnostics; only push clients need
            // the full pipeline run here.
            this.PublishDiagnosticsIfPushMode(uri, text, skipBinding: false);
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/didClose", UseSingleObjectParameterDeserialization = true)]
    public Task DidCloseAsync(DidCloseTextDocumentParams request)
    {
        var uri = request.TextDocument?.Uri;
        if (uri == null)
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            this.documentContentService.TryRemove(uri.ToString());
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/diagnostic", UseSingleObjectParameterDeserialization = true)]
    public async Task<object> DocumentDiagnosticAsync(DocumentDiagnosticParams request, CancellationToken cancellationToken)
    {
        var uri = request?.TextDocument?.Uri;
        if (uri == null)
        {
            return new FullDocumentDiagnosticReport { Items = Array.Empty<Diagnostic>() };
        }

        // Snapshot the current text and owning project under the gate, then run the (potentially
        // expensive) full binding pass off the gate so interactive requests are not blocked.
        string text = null;
        string filePath = null;
        ProjectState project = null;
        await this.gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            filePath = uri.GetFileSystemPath();
            project = !string.IsNullOrEmpty(filePath) ? this.workspaceState.GetProjectForFile(filePath) : null;
            if (this.documentContentService.TryGet(uri.ToString(), out var content))
            {
                text = content.SyntaxTree.Text.ToString();
            }
        }
        finally
        {
            this.gate.Release();
        }

        if (text == null)
        {
            return new FullDocumentDiagnosticReport { Items = Array.Empty<Diagnostic>() };
        }

        cancellationToken.ThrowIfCancellationRequested();
        var result = DocumentSyncHandler.ComputeDiagnostics(text, skipBinding: false, project, filePath);
        cancellationToken.ThrowIfCancellationRequested();

        var resultId = ComputeResultId(result.Diagnostics);
        if (request.PreviousResultId != null && string.Equals(request.PreviousResultId, resultId, StringComparison.Ordinal))
        {
            return new UnchangedDocumentDiagnosticReport { ResultId = resultId };
        }

        return new FullDocumentDiagnosticReport
        {
            ResultId = resultId,
            Items = result.Diagnostics.ToList(),
        };
    }

    [JsonRpcMethod("workspace/didChangeWatchedFiles", UseSingleObjectParameterDeserialization = true)]
    public Task DidChangeWatchedFilesAsync(DidChangeWatchedFilesParams request)
    {
        if (request?.Changes == null)
        {
            return Task.CompletedTask;
        }

        return this.GuardAsync(() =>
        {
            foreach (var change in request.Changes)
            {
                var filePath = change.Uri?.GetFileSystemPath();
                if (string.IsNullOrEmpty(filePath))
                {
                    continue;
                }

                if (filePath.EndsWith(".gsproj", StringComparison.OrdinalIgnoreCase))
                {
                    this.HandleProjectFileChange(filePath, change.Type);
                }
                else if (filePath.EndsWith(".gs", StringComparison.OrdinalIgnoreCase))
                {
                    this.HandleSourceFileChange(filePath, change.Type);
                }
            }

            // External file/project changes can alter diagnostics in open documents.
            this.RequestDiagnosticRefresh();
            return 0;
        });
    }

    [JsonRpcMethod("textDocument/hover", UseSingleObjectParameterDeserialization = true)]
    public Task<Hover> HoverAsync(HoverParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? HoverComputer.ComputeHover(content, request.Position)
            : null);

    [JsonRpcMethod("textDocument/definition", UseSingleObjectParameterDeserialization = true)]
    public Task<Location> DefinitionAsync(DefinitionParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? DefinitionComputer.ComputeDefinition(request.TextDocument.Uri, content, request.Position)
            : null);

    [JsonRpcMethod("textDocument/references", UseSingleObjectParameterDeserialization = true)]
    public Task<Location[]> ReferencesAsync(ReferenceParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? ReferencesComputer.ComputeReferences(request.TextDocument.Uri, content, request.Position, request.Context?.IncludeDeclaration ?? false).ToArray()
            : Array.Empty<Location>());

    [JsonRpcMethod("textDocument/documentHighlight", UseSingleObjectParameterDeserialization = true)]
    public Task<DocumentHighlight[]> DocumentHighlightAsync(DocumentHighlightParams request)
        => this.GuardAsync(() =>
        {
            if (!this.TryGet(request.TextDocument, out var content))
            {
                return Array.Empty<DocumentHighlight>();
            }

            var tokens = ReferencesComputer.ComputeReferenceTokens(content, request.Position, includeDeclaration: true);
            return tokens.Select(t => new DocumentHighlight
            {
                Range = SemanticLookup.ToRange(t),
                Kind = DocumentHighlightKind.Text,
            }).ToArray();
        });

    [JsonRpcMethod("textDocument/documentSymbol", UseSingleObjectParameterDeserialization = true)]
    public Task<SymbolInformationOrDocumentSymbol[]> DocumentSymbolAsync(DocumentSymbolParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? DocumentSymbolComputer.ComputeDocumentSymbols(content).ToArray()
            : Array.Empty<SymbolInformationOrDocumentSymbol>());

    [JsonRpcMethod("workspace/symbol", UseSingleObjectParameterDeserialization = true)]
    public Task<WorkspaceSymbol[]> WorkspaceSymbolAsync(WorkspaceSymbolParams request)
        => this.GuardAsync(() =>
        {
            var query = request.Query ?? string.Empty;
            var results = new List<WorkspaceSymbol>();
            foreach (var pair in this.documentContentService.AllDocuments)
            {
                WorkspaceSymbolHandler.CollectSymbols(results, pair.Key, pair.Value, query);
            }

            return results.ToArray();
        });

    [JsonRpcMethod("textDocument/completion", UseSingleObjectParameterDeserialization = true)]
    public Task<CompletionList> CompletionAsync(CompletionParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? new CompletionList(CompletionComputer.ComputeCompletions(content, request.Position))
            : new CompletionList());

    [JsonRpcMethod("textDocument/signatureHelp", UseSingleObjectParameterDeserialization = true)]
    public Task<SignatureHelp> SignatureHelpAsync(SignatureHelpParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? SignatureHelpComputer.ComputeSignatureHelp(content, request.Position)
            : null);

    [JsonRpcMethod("textDocument/rename", UseSingleObjectParameterDeserialization = true)]
    public Task<WorkspaceEdit> RenameAsync(RenameParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? RenameComputer.ComputeRename(request.TextDocument.Uri, content, request.Position, request.NewName)
            : null);

    [JsonRpcMethod("textDocument/prepareRename", UseSingleObjectParameterDeserialization = true)]
    public Task<Range> PrepareRenameAsync(PrepareRenameParams request)
        => this.GuardAsync(() => this.ComputePrepareRename(request));

    [JsonRpcMethod("textDocument/codeAction", UseSingleObjectParameterDeserialization = true)]
    public Task<CommandOrCodeActionContainer> CodeActionAsync(CodeActionParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? CodeActionComputer.ComputeCodeActions(request.TextDocument.Uri, content, request.Range)
            : new CommandOrCodeActionContainer());

    [JsonRpcMethod("textDocument/codeLens", UseSingleObjectParameterDeserialization = true)]
    public Task<CodeLens[]> CodeLensAsync(CodeLensParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? CodeLensComputer.ComputeLenses(content, request.TextDocument.Uri?.ToString()).ToArray()
            : Array.Empty<CodeLens>());

    [JsonRpcMethod("gsharp/discoverTests")]
    public Task<TestDiscoveryItem[]> DiscoverTestsAsync()
        => this.GuardAsync(() =>
        {
            var results = new List<TestDiscoveryItem>();
            foreach (var pair in this.documentContentService.AllDocuments)
            {
                results.AddRange(TestDiscoveryComputer.ComputeTests(pair.Key, pair.Value));
            }

            return results.ToArray();
        });

    [JsonRpcMethod("textDocument/inlayHint", UseSingleObjectParameterDeserialization = true)]
    public Task<InlayHint[]> InlayHintAsync(InlayHintParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? InlayHintComputer.ComputeHints(content).ToArray()
            : Array.Empty<InlayHint>());

    [JsonRpcMethod("textDocument/foldingRange", UseSingleObjectParameterDeserialization = true)]
    public Task<FoldingRange[]> FoldingRangeAsync(FoldingRangeParams request)
        => this.GuardAsync(() => this.TryGet(request.TextDocument, out var content)
            ? FoldingComputer.ComputeFoldings(content).ToArray()
            : Array.Empty<FoldingRange>());

    [JsonRpcMethod("textDocument/selectionRange", UseSingleObjectParameterDeserialization = true)]
    public Task<SelectionRange[]> SelectionRangeAsync(SelectionRangeParams request)
        => this.GuardAsync(() =>
        {
            if (!this.TryGet(request.TextDocument, out var content) || request.Positions == null)
            {
                return Array.Empty<SelectionRange>();
            }

            return request.Positions.Select(p => SelectionRangeComputer.ComputeSelectionRange(content, p)).ToArray();
        });

    [JsonRpcMethod("textDocument/semanticTokens/full", UseSingleObjectParameterDeserialization = true)]
    public Task<SemanticTokens> SemanticTokensFullAsync(SemanticTokensParams request)
        => this.GuardAsync(() => this.ComputeSemanticTokens(request.TextDocument));

    [JsonRpcMethod("textDocument/semanticTokens/range", UseSingleObjectParameterDeserialization = true)]
    public Task<SemanticTokens> SemanticTokensRangeAsync(SemanticTokensRangeParams request)
        => this.GuardAsync(() => this.ComputeSemanticTokens(request.TextDocument));

    [JsonRpcMethod("textDocument/formatting", UseSingleObjectParameterDeserialization = true)]
    public Task<TextEdit[]> FormattingAsync(DocumentFormattingParams request)
        => this.GuardAsync(() => this.FormatDocument(request.TextDocument));

    [JsonRpcMethod("textDocument/rangeFormatting", UseSingleObjectParameterDeserialization = true)]
    public Task<TextEdit[]> RangeFormattingAsync(DocumentRangeFormattingParams request)
        => this.GuardAsync(() => this.FormatDocument(request.TextDocument));

    [JsonRpcMethod("textDocument/onTypeFormatting", UseSingleObjectParameterDeserialization = true)]
    public Task<TextEdit[]> OnTypeFormattingAsync(DocumentOnTypeFormattingParams request)
        => this.GuardAsync(() => this.FormatDocument(request.TextDocument));

    [JsonRpcMethod("textDocument/implementation", UseSingleObjectParameterDeserialization = true)]
    public Task<Location[]> ImplementationAsync(ImplementationParams request)
        => this.GuardAsync(() => this.ComputeImplementation(request));

    [JsonRpcMethod("textDocument/typeDefinition", UseSingleObjectParameterDeserialization = true)]
    public Task<Location[]> TypeDefinitionAsync(TypeDefinitionParams request)
        => this.GuardAsync(() => this.ComputeTypeDefinition(request));

    [JsonRpcMethod("textDocument/linkedEditingRange", UseSingleObjectParameterDeserialization = true)]
    public Task<LinkedEditingRanges> LinkedEditingRangeAsync(LinkedEditingRangeParams request)
        => this.GuardAsync(() => this.ComputeLinkedEditingRanges(request));

    private async Task<T> GuardAsync<T>(Func<T> body)
    {
        await this.gate.WaitAsync().ConfigureAwait(false);
        try
        {
            return body();
        }
        finally
        {
            this.gate.Release();
        }
    }

    private bool TryGet(TextDocumentIdentifier identifier, out DocumentContent content)
    {
        content = null;
        var uri = identifier?.Uri;
        return uri != null && this.documentContentService.TryGet(uri.ToString(), out content);
    }

    private void UpdateDocument(DocumentUri uri, string text)
    {
        var filePath = uri.GetFileSystemPath();
        var project = !string.IsNullOrEmpty(filePath) ? this.workspaceState.GetProjectForFile(filePath) : null;
        if (project != null)
        {
            project.UpdateFile(filePath, text);
        }

        // Parse-only content (no binding) feeds the content service used by other features;
        // diagnostics are produced on demand by the textDocument/diagnostic pull handler.
        var result = DocumentSyncHandler.ComputeDiagnostics(text, skipBinding: true, project, filePath);
        this.documentContentService.AddOrUpdate(uri.ToString(), result.Content);
    }

    private void PublishDiagnosticsIfPushMode(DocumentUri uri, string text, bool skipBinding)
    {
        // Clients advertising pull diagnostics request them via textDocument/diagnostic, so push
        // is suppressed to avoid double reporting. Older push-only clients still get notifications.
        if (this.clientSupportsPullDiagnostics)
        {
            return;
        }

        var filePath = uri.GetFileSystemPath();
        var project = !string.IsNullOrEmpty(filePath) ? this.workspaceState.GetProjectForFile(filePath) : null;
        var result = DocumentSyncHandler.ComputeDiagnostics(text, skipBinding, project, filePath);

        this.rpc?.NotifyWithParameterObjectAsync(
            "textDocument/publishDiagnostics",
            new PublishDiagnosticsParams { Uri = uri, Diagnostics = result.Diagnostics });
    }

    private void DetectClientDiagnosticCapabilities(JsonElement capabilities)
    {
        try
        {
            if (capabilities.ValueKind == JsonValueKind.Object)
            {
                if (capabilities.TryGetProperty("textDocument", out var textDocument)
                    && textDocument.ValueKind == JsonValueKind.Object
                    && textDocument.TryGetProperty("diagnostic", out var diagnostic)
                    && diagnostic.ValueKind == JsonValueKind.Object)
                {
                    this.clientSupportsPullDiagnostics = true;
                }

                if (capabilities.TryGetProperty("workspace", out var workspace)
                    && workspace.ValueKind == JsonValueKind.Object
                    && workspace.TryGetProperty("diagnostics", out var wsDiagnostics)
                    && wsDiagnostics.ValueKind == JsonValueKind.Object
                    && wsDiagnostics.TryGetProperty("refreshSupport", out var refreshSupport)
                    && refreshSupport.ValueKind == JsonValueKind.True)
                {
                    this.clientSupportsDiagnosticRefresh = true;
                }
            }
        }
        catch
        {
            // Capability probing is best-effort; absence of pull support falls back to push.
        }
    }

    private void RequestDiagnosticRefresh(DocumentUri changedUri)
    {
        if (!this.clientSupportsPullDiagnostics || !this.clientSupportsDiagnosticRefresh)
        {
            return;
        }

        // Single-file edits do not affect other documents, so skip refreshes for documents that
        // are not part of a multi-file project.
        var filePath = changedUri.GetFileSystemPath();
        var project = !string.IsNullOrEmpty(filePath) ? this.workspaceState.GetProjectForFile(filePath) : null;
        if (project == null || project.SourceFiles.Count <= 1)
        {
            return;
        }

        this.RequestDiagnosticRefresh();
    }

    private void RequestDiagnosticRefresh()
    {
        if (!this.clientSupportsDiagnosticRefresh)
        {
            return;
        }

        // Debounce: coalesce bursts of changes into a single workspace/diagnostic/refresh request.
        lock (this.refreshLock)
        {
            this.refreshTimer ??= new Timer(_ => this.SendDiagnosticRefresh(), null, Timeout.Infinite, Timeout.Infinite);
            this.refreshTimer.Change(500, Timeout.Infinite);
        }
    }

    private void SendDiagnosticRefresh()
    {
        try
        {
            this.rpc?.InvokeAsync("workspace/diagnostic/refresh");
        }
        catch
        {
            // The client may have disconnected; refresh is best-effort.
        }
    }

    private static string ComputeResultId(IReadOnlyList<Diagnostic> diagnostics)
    {
        var builder = new StringBuilder();
        foreach (var d in diagnostics)
        {
            builder.Append((int)d.Severity).Append('|');
            if (d.Range != null)
            {
                builder.Append(d.Range.Start?.Line).Append(',').Append(d.Range.Start?.Character).Append('-')
                    .Append(d.Range.End?.Line).Append(',').Append(d.Range.End?.Character);
            }

            builder.Append('|').Append(d.Code?.Value).Append('|').Append(d.Message).Append('\n');
        }

        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(builder.ToString()));
        return Convert.ToHexString(bytes);
    }

    private SemanticTokens ComputeSemanticTokens(TextDocumentIdentifier identifier)
    {
        if (!this.TryGet(identifier, out var content))
        {
            return new SemanticTokens { Data = System.Collections.Immutable.ImmutableArray<int>.Empty };
        }

        var document = new SemanticTokensDocument(SemanticTokensHandler.Legend);
        var builder = document.Create();
        SemanticTokensComputer.Tokenize(builder, content);
        builder.Commit();
        return document.GetSemanticTokens();
    }

    private TextEdit[] FormatDocument(TextDocumentIdentifier identifier)
    {
        if (!this.TryGet(identifier, out var content))
        {
            return Array.Empty<TextEdit>();
        }

        var sourceText = content.SyntaxTree.Text;
        var originalText = sourceText.ToString();
        var formatted = FormattingEngine.Format(originalText);
        if (formatted == originalText)
        {
            return Array.Empty<TextEdit>();
        }

        var lastLine = sourceText.Lines.Length - 1;
        var lastChar = sourceText.Lines[lastLine].Length;
        return new[]
        {
            new TextEdit
            {
                Range = new Range(new Position(0, 0), new Position(lastLine, lastChar)),
                NewText = formatted,
            },
        };
    }

    private Range ComputePrepareRename(PrepareRenameParams request)
    {
        if (!this.TryGet(request.TextDocument, out var content))
        {
            return null;
        }

        var offset = SemanticLookup.ToOffset(content, request.Position);
        var token = SemanticLookup.FindTokenAt(content.SyntaxTree, offset);
        if (token == null || token.Kind != SyntaxKind.IdentifierToken)
        {
            return null;
        }

        var compilation = TryGetCompilation(content);
        if (compilation == null)
        {
            return null;
        }

        var symbol = SemanticLookup.ResolveSymbol(compilation, token);
        return SemanticLookup.CanRename(symbol) ? SemanticLookup.ToRange(token) : null;
    }

    private Location[] ComputeImplementation(ImplementationParams request)
    {
        if (!this.TryGet(request.TextDocument, out var content))
        {
            return Array.Empty<Location>();
        }

        var offset = SemanticLookup.ToOffset(content, request.Position);
        var token = SemanticLookup.FindTokenAt(content.SyntaxTree, offset);
        if (token == null || token.Kind != SyntaxKind.IdentifierToken)
        {
            return Array.Empty<Location>();
        }

        var compilation = TryGetCompilation(content);
        if (compilation == null)
        {
            return Array.Empty<Location>();
        }

        var symbol = SemanticLookup.ResolveSymbol(compilation, token);
        if (symbol is not InterfaceSymbol iface)
        {
            return Array.Empty<Location>();
        }

        var locations = new List<Location>();
        foreach (var structSym in compilation.GlobalScope.Structs)
        {
            if (structSym.Interfaces.Contains(iface) && structSym.Declaration != null)
            {
                locations.Add(new Location
                {
                    Uri = request.TextDocument.Uri,
                    Range = SemanticLookup.ToRange(structSym.Declaration.Identifier),
                });
            }
        }

        return locations.ToArray();
    }

    private Location[] ComputeTypeDefinition(TypeDefinitionParams request)
    {
        if (!this.TryGet(request.TextDocument, out var content))
        {
            return Array.Empty<Location>();
        }

        var offset = SemanticLookup.ToOffset(content, request.Position);
        var token = SemanticLookup.FindTokenAt(content.SyntaxTree, offset);
        if (token == null || token.Kind != SyntaxKind.IdentifierToken)
        {
            return Array.Empty<Location>();
        }

        var compilation = TryGetCompilation(content);
        if (compilation == null)
        {
            return Array.Empty<Location>();
        }

        var symbol = SemanticLookup.ResolveSymbol(compilation, token);
        TypeSymbol typeSymbol = symbol switch
        {
            ParameterSymbol ps => ps.Type,
            VariableSymbol vs => vs.Type,
            FunctionSymbol fs => fs.Type,
            _ => null,
        };

        if (typeSymbol == null)
        {
            return Array.Empty<Location>();
        }

        var firstRef = SemanticLookup.FindReferences(compilation, typeSymbol).FirstOrDefault();
        if (firstRef == null)
        {
            return Array.Empty<Location>();
        }

        return new[]
        {
            new Location
            {
                Uri = request.TextDocument.Uri,
                Range = SemanticLookup.ToRange(firstRef),
            },
        };
    }

    private LinkedEditingRanges ComputeLinkedEditingRanges(LinkedEditingRangeParams request)
    {
        if (!this.TryGet(request.TextDocument, out var content))
        {
            return null;
        }

        var tree = content.SyntaxTree;
        var offset = SemanticLookup.ToOffset(content, request.Position);
        var token = SemanticLookup.FindTokenAt(tree, offset);
        if (token == null || token.Kind != SyntaxKind.IdentifierToken)
        {
            return null;
        }

        var compilation = TryGetCompilation(content);
        if (compilation == null)
        {
            return null;
        }

        var symbol = SemanticLookup.ResolveSymbol(compilation, token);
        if (!SemanticLookup.CanRename(symbol))
        {
            return null;
        }

        var references = SemanticLookup.FindReferences(compilation, symbol).ToList();
        if (references.Count == 0)
        {
            return null;
        }

        return new LinkedEditingRanges
        {
            Ranges = references.Select(SemanticLookup.ToRange).ToList(),
            WordPattern = @"[a-zA-Z_]\w*",
        };
    }

    private void HandleProjectFileChange(string filePath, FileChangeType changeType)
    {
        switch (changeType)
        {
            case FileChangeType.Created:
                var discovered = ProjectDiscovery.DiscoverProject(filePath);
                if (discovered != null)
                {
                    var project = this.workspaceState.AddProject(discovered.ProjectFilePath);
                    project.ProjectReferences = discovered.ProjectReferences;
                    project.ReferenceSourcePath = discovered.ReferenceSourcePath;
                    project.References = discovered.References;
                    foreach (var source in discovered.SourceFiles)
                    {
                        project.AddFileFromDisk(source);
                        this.workspaceState.RegisterFile(source, project);
                    }
                }

                break;

            case FileChangeType.Changed:
                var existing = this.workspaceState.GetProject(filePath);
                var rediscovered = existing != null ? ProjectDiscovery.DiscoverProject(filePath) : null;
                if (rediscovered != null)
                {
                    existing.ProjectReferences = rediscovered.ProjectReferences;
                    existing.ReferenceSourcePath = rediscovered.ReferenceSourcePath;
                    existing.References = rediscovered.References;
                    foreach (var source in rediscovered.SourceFiles)
                    {
                        if (!existing.ContainsFile(source))
                        {
                            existing.AddFileFromDisk(source);
                            this.workspaceState.RegisterFile(source, existing);
                        }
                    }

                    foreach (var oldFile in existing.SourceFiles.ToList())
                    {
                        if (!rediscovered.SourceFiles.Contains(oldFile))
                        {
                            existing.RemoveFile(oldFile);
                            this.workspaceState.UnregisterFile(oldFile);
                        }
                    }
                }

                break;

            case FileChangeType.Deleted:
                this.workspaceState.RemoveProject(filePath);
                break;
        }
    }

    private void HandleSourceFileChange(string filePath, FileChangeType changeType)
    {
        switch (changeType)
        {
            case FileChangeType.Created:
                var project = this.FindOwningProject(filePath);
                if (project != null)
                {
                    project.AddFileFromDisk(filePath);
                    this.workspaceState.RegisterFile(filePath, project);
                }

                break;

            case FileChangeType.Deleted:
                var owning = this.workspaceState.GetProjectForFile(filePath);
                if (owning != null)
                {
                    owning.RemoveFile(filePath);
                    this.workspaceState.UnregisterFile(filePath);
                }

                break;
        }
    }

    private ProjectState FindOwningProject(string filePath)
    {
        var fileDir = Path.GetDirectoryName(Path.GetFullPath(filePath));
        foreach (var project in this.workspaceState.Projects)
        {
            if (fileDir != null && fileDir.StartsWith(project.ProjectDirectory, StringComparison.OrdinalIgnoreCase))
            {
                return project;
            }
        }

        return this.workspaceState.GetOrCreateImplicitProject();
    }

    private static GSharp.Core.CodeAnalysis.Compilation.Compilation TryGetCompilation(DocumentContent content)
    {
        try
        {
            return content.Project?.GetCompilation()
                ?? new GSharp.Core.CodeAnalysis.Compilation.Compilation(content.SyntaxTree);
        }
        catch
        {
            return null;
        }
    }
}
