// <auto-generated/>
// Static server capability advertisement for the GSharp language server. Marked auto-generated
// to opt out of StyleCop documentation/ordering rules; this is protocol plumbing.

using GSharp.LanguageServer.Protocol;

namespace GSharp.LanguageServer.Server;

/// <summary>
/// Builds the static <see cref="ServerCapabilities"/> advertised in the initialize result.
/// The vscode client strips dynamic registration, so every feature is declared statically here.
/// </summary>
public static class ServerCapabilitiesFactory
{
    public static ServerCapabilities Create(LanguageServerInitializationOptions options = null)
    {
        options ??= new LanguageServerInitializationOptions();
        return new ServerCapabilities
        {
            TextDocumentSync = new TextDocumentSyncOptions
            {
                OpenClose = true,
                Change = 1, // Full
                Save = new SaveOptions { IncludeText = true },
            },
            HoverProvider = true,
            DefinitionProvider = true,
            TypeDefinitionProvider = true,
            ImplementationProvider = true,
            ReferencesProvider = true,
            DocumentHighlightProvider = true,
            DocumentSymbolProvider = true,
            WorkspaceSymbolProvider = true,
            DocumentFormattingProvider = true,
            FoldingRangeProvider = true,
            SelectionRangeProvider = true,
            LinkedEditingRangeProvider = true,
            CompletionProvider = new CompletionOptions
            {
                TriggerCharacters = options.CompletionTriggerOnDot ? new[] { "." } : System.Array.Empty<string>(),
                ResolveProvider = false,
            },
            SignatureHelpProvider = new SignatureHelpOptions
            {
                TriggerCharacters = new[] { "(", "," },
                RetriggerCharacters = new[] { "," },
            },
            RenameProvider = new RenameOptions { PrepareProvider = true },
            CodeActionProvider = new CodeActionOptions
            {
                CodeActionKinds = new[] { CodeActionKind.QuickFix, CodeActionKind.RefactorRewrite },
            },
            CodeLensProvider = options.ReferenceCodeLens
                ? new CodeLensOptions { ResolveProvider = false }
                : null,

            // Range formatting and on-type formatting are intentionally not advertised (see
            // issue #1660): FormattingEngine only produces a correct whole-document result, and
            // advertising a partial-range capability that silently rewrites the whole document
            // on every "}"/";"/newline keystroke is worse than not offering it. Whole-document
            // formatting (DocumentFormattingProvider above) remains fully supported.
            SemanticTokensProvider = new SemanticTokensOptions
            {
                Legend = SemanticTokensHandler.Legend,
                Full = new SemanticTokensServerFull { Delta = false },
                Range = true,
            },
            InlayHintProvider = options.ParameterNameInlayHints || options.TypeInlayHints
                ? new InlayHintOptions { ResolveProvider = false }
                : null,
            DiagnosticProvider = new DiagnosticOptions
            {
                Identifier = Constants.LanguageId,
                InterFileDependencies = true,
                WorkspaceDiagnostics = false,
            },
        };
    }
}
