// <auto-generated/>
// Static server capability advertisement for the GSharp language server. Marked auto-generated
// to opt out of StyleCop documentation/ordering rules; this is protocol plumbing.

using GSharp.LanguageServer.Protocol;

namespace GSharp.LanguageServer.Server;

/// <summary>
/// Builds the static <see cref="ServerCapabilities"/> advertised in the initialize result.
/// The vscode client strips dynamic registration, so every feature is declared statically here.
/// </summary>
internal static class ServerCapabilitiesFactory
{
    public static ServerCapabilities Create()
    {
        return new ServerCapabilities
        {
            TextDocumentSync = new TextDocumentSyncOptions
            {
                OpenClose = true,
                Change = 1, // Full
                Save = new SaveOptions { IncludeText = true },
            },
            HoverProvider = true,
            DefinitionProvider = true,
            TypeDefinitionProvider = true,
            ImplementationProvider = true,
            ReferencesProvider = true,
            DocumentHighlightProvider = true,
            DocumentSymbolProvider = true,
            WorkspaceSymbolProvider = true,
            DocumentFormattingProvider = true,
            DocumentRangeFormattingProvider = true,
            FoldingRangeProvider = true,
            SelectionRangeProvider = true,
            LinkedEditingRangeProvider = true,
            CompletionProvider = new CompletionOptions
            {
                TriggerCharacters = new[] { "." },
                ResolveProvider = false,
            },
            SignatureHelpProvider = new SignatureHelpOptions
            {
                TriggerCharacters = new[] { "(", "," },
                RetriggerCharacters = new[] { "," },
            },
            RenameProvider = new RenameOptions { PrepareProvider = true },
            CodeActionProvider = new CodeActionOptions
            {
                CodeActionKinds = new[] { CodeActionKind.RefactorRewrite },
            },
            CodeLensProvider = new CodeLensOptions { ResolveProvider = false },
            DocumentOnTypeFormattingProvider = new DocumentOnTypeFormattingOptions
            {
                FirstTriggerCharacter = "}",
                MoreTriggerCharacter = new[] { ";", "\n" },
            },
            SemanticTokensProvider = new SemanticTokensOptions
            {
                Legend = SemanticTokensHandler.Legend,
                Full = new SemanticTokensServerFull { Delta = false },
                Range = true,
            },
            InlayHintProvider = new InlayHintOptions { ResolveProvider = false },
        };
    }
}
