// <copyright file="Adr0192GeneratedImplementingPartTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Cs2Gs.CodeModel.Ast;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Cs2Gs.Tests;

/// <summary>
/// ADR-0192 follow-on 2, step 3: the source-generator host (gsgen) binds the
/// C# stub rendered from the user's G# together with the generator output and
/// back-translates ONLY the generator output. A generated partial method
/// implementation whose definition is in the stub (the user's G# declaring
/// part, e.g. <c>@GeneratedRegex(...) private partial func Digits() Regex;</c>)
/// must come out as a G# implementing part — <c>partial func</c> with its body —
/// so it pairs with that declaring part at build time. The mode is opt-in
/// (<c>emitGeneratedImplementingParts</c>); every other caller keeps the
/// ordinary-method shape.
/// </summary>
public class Adr0192GeneratedImplementingPartTests
{
    private const string StubPath = "GsgenStubs.cs";

    private const string ComputeStub = @"#nullable enable
namespace Demo
{
    public partial class C
    {
        private partial int Compute(int x);
        public int Use() => throw null!;
    }
}";

    private const string ComputeGenerated = @"// <auto-generated/>
#nullable enable
namespace Demo
{
    partial class C
    {
        private partial int Compute(int x)
        {
            return x + 1;
        }
    }
}";

    private const string RegexStub = @"#nullable enable
namespace App
{
    public partial class P
    {
        [global::System.Text.RegularExpressions.GeneratedRegexAttribute(""\\d+"")]
        private static partial global::System.Text.RegularExpressions.Regex Digits();
        public static bool Test(string s) => throw null!;
    }
}";

    [Fact]
    public void OptionOn_ImplementationOfStubDefinition_IsAnImplementingPartWithItsBody()
    {
        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = TranslateGenerated(
            ComputeStub,
            ("C.g.cs", ComputeGenerated),
            emitGeneratedImplementingParts: true);

        Assert.DoesNotContain(diagnostics, d => d.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("private partial func Compute(x int32) int32 {", printed, StringComparison.Ordinal);
        Assert.Contains("return x + 1", printed, StringComparison.Ordinal);
        Assert.DoesNotContain("Compute(x int32) int32;", printed, StringComparison.Ordinal);

        // It pairs with the user's hand-written G# declaring part.
        const string userPart = @"package Demo

partial class C {
    private partial func Compute(x int32) int32;
    public func Use() int32 -> Compute(1)
}
";
        TranslationTestValidation.AssertBinds(userPart, printed);
    }

    [Fact]
    public void OptionOff_ImplementationOfStubDefinition_StaysAnOrdinaryMethod()
    {
        (string printed, _) = TranslateGenerated(
            ComputeStub,
            ("C.g.cs", ComputeGenerated),
            emitGeneratedImplementingParts: false);

        Assert.Contains("private func Compute(x int32) int32 {", printed, StringComparison.Ordinal);
        Assert.DoesNotContain("partial func", printed, StringComparison.Ordinal);
    }

    [Fact]
    public void OptionOn_BothPartsInTranslatedGeneratedTrees_KeepsTheSingleImplementationShape()
    {
        // A generator emitting both halves: the definition is in a tree this
        // run translates, so the pair follows ADR-0143 with pairs off — the
        // definition is dropped (and not reported: its implementation is
        // translated) and the implementation is an ordinary method.
        const string definition = @"// <auto-generated/>
namespace Demo
{
    public partial class C
    {
        private partial int Compute(int x);
        public int Use() => Compute(1);
    }
}";
        (IReadOnlyList<string> printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = TranslateGeneratedFiles(
            "// no user declarations\n",
            new[] { ("C.Def.g.cs", definition), ("C.g.cs", ComputeGenerated) },
            emitGeneratedImplementingParts: true);

        Assert.DoesNotContain(diagnostics, d => d.Severity == TranslationSeverity.Unsupported);
        Assert.DoesNotContain("partial func", printed[0], StringComparison.Ordinal);
        Assert.DoesNotContain("func Compute", printed[0], StringComparison.Ordinal);
        Assert.Contains("private func Compute(x int32) int32 {", printed[1], StringComparison.Ordinal);
        Assert.DoesNotContain("partial func", printed[1], StringComparison.Ordinal);
        TranslationTestValidation.AssertBinds(printed.ToArray());
    }

    [Theory]
    [InlineData("Digits.RegexGenerator.g.cs.txt")]
    [InlineData("Backtracking.RegexGenerator.g.cs.txt")]
    public void OptionOn_RealGeneratedRegexOutput_EmitsTheImplementingPart(string fixture)
    {
        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = TranslateGenerated(
            RegexStub,
            ("RegexGenerator.g.cs", ReadFixture(fixture)),
            emitGeneratedImplementingParts: true);

        Assert.DoesNotContain(diagnostics, d => d.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("private partial func Digits() Regex -> Digits_0.Instance", printed, StringComparison.Ordinal);

        // A static implementing part lives in the type's `shared { }` block,
        // like the user's static declaring part.
        int shared = printed.IndexOf("shared {", StringComparison.Ordinal);
        Assert.True(shared >= 0 && shared < printed.IndexOf("partial func Digits", StringComparison.Ordinal), printed);
    }

    [Fact]
    public void OptionOff_RealGeneratedRegexOutput_StaysAnOrdinaryMethod()
    {
        (string printed, _) = TranslateGenerated(
            RegexStub,
            ("RegexGenerator.g.cs", ReadFixture("Digits.RegexGenerator.g.cs.txt")),
            emitGeneratedImplementingParts: false);

        Assert.Contains("private func Digits() Regex -> Digits_0.Instance", printed, StringComparison.Ordinal);
        Assert.DoesNotContain("partial func", printed, StringComparison.Ordinal);
    }

    private static string ReadFixture(string name) =>
        File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Fixtures", "Adr0192GeneratedRegex", name));

    private static (string Printed, IReadOnlyList<TranslationDiagnostic> Diagnostics) TranslateGenerated(
        string stub,
        (string Path, string Source) generated,
        bool emitGeneratedImplementingParts)
    {
        (IReadOnlyList<string> printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = TranslateGeneratedFiles(
            stub,
            new[] { generated },
            emitGeneratedImplementingParts);
        return (printed[0], diagnostics);
    }

    // Mirrors GeneratedDocTranslator: stub + generated trees bound in one
    // compilation, only the generated trees translated, each with its own
    // translator instance.
    private static (IReadOnlyList<string> Printed, IReadOnlyList<TranslationDiagnostic> Diagnostics) TranslateGeneratedFiles(
        string stub,
        IReadOnlyList<(string Path, string Source)> generated,
        bool emitGeneratedImplementingParts)
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.Latest);
        var trees = new List<SyntaxTree> { CSharpSyntaxTree.ParseText(stub, parseOptions, path: StubPath) };
        trees.AddRange(generated.Select(file => CSharpSyntaxTree.ParseText(file.Source, parseOptions, path: file.Path)));
        var compilation = CSharpCompilation.Create(
            "GsgenBackTranslate",
            trees,
            CSharpProjectLoader.RuntimeReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                .WithNullableContextOptions(NullableContextOptions.Enable)
                .WithAllowUnsafe(true));
        Diagnostic[] errors = compilation.GetDiagnostics()
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        Assert.True(errors.Length == 0, string.Join(Environment.NewLine, errors.Select(error => error.ToString())));

        string[] translatedFilePaths = generated.Select(file => file.Path).ToArray();
        var printed = new List<string>();
        var diagnostics = new List<TranslationDiagnostic>();
        foreach (SyntaxTree tree in trees.Skip(1))
        {
            SemanticModel model = compilation.GetSemanticModel(tree);
            var context = new TranslationContext(compilation, model, tree.FilePath);
            CompilationUnit unit = new CSharpToGSharpTranslator(
                preservePartialParts: true,
                widenObliviousReferenceFields: true,
                translatedFilePaths: translatedFilePaths,
                emitGeneratedImplementingParts: emitGeneratedImplementingParts)
                .TranslateDocument(new LoadedDocument(tree.FilePath, tree, model), context);
            printed.Add(GSharpPrinter.Print(unit));
            diagnostics.AddRange(context.Diagnostics);
        }

        return (printed, diagnostics);
    }
}
