// <copyright file="CSharpProjectLoaderDiagnosticsTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Cs2Gs.Translator.Loading;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Cs2Gs.Tests;

/// <summary>
/// Regression tests for issue #1742: <see cref="CSharpProjectLoader"/> must not
/// silently swallow MSBuild workspace load failures, and must not exclude a
/// hand-written source file merely because its name matches a generated-file
/// pattern (it must check for an actual generated marker instead).
/// </summary>
public class CSharpProjectLoaderDiagnosticsTests
{
    /// <summary>
    /// A project whose <c>ProjectReference</c> points at a file that does not
    /// exist is a classic MSBuild "soft fail": <c>OpenProjectAsync</c> does not
    /// throw, but the workspace records a <see cref="WorkspaceDiagnosticKind.Failure"/>
    /// diagnostic. That failure must be surfaced as an <see cref="DiagnosticSeverity.Error"/>
    /// in <see cref="LoadedCSharpProject.LoadDiagnostics"/> (and therefore fail
    /// <see cref="LoadedCSharpProject.BoundWithoutErrors"/>) instead of being
    /// dropped on the floor.
    /// </summary>
    [Fact]
    public async Task LoadProjectAsync_SurfacesMSBuildWorkspaceLoadFailure()
    {
        string projectDir = NewScratchDir("load-failure");
        File.WriteAllText(Path.Combine(projectDir, "Directory.Build.props"), "<Project></Project>");
        string projectPath = Path.Combine(projectDir, "Broken.csproj");
        File.WriteAllText(projectPath, @"<Project Sdk=""Microsoft.NET.Sdk"">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include=""..\DoesNotExist\DoesNotExist.csproj"" />
  </ItemGroup>
</Project>
");
        File.WriteAllText(Path.Combine(projectDir, "Program.cs"), "public class Program { public static void Main() { } }");

        LoadedCSharpProject project = await CSharpProjectLoader.LoadProjectAsync(projectPath);

        Assert.NotEmpty(project.LoadDiagnostics);
        Assert.Contains(project.LoadDiagnostics, d => d.Severity == DiagnosticSeverity.Error);
        Assert.False(
            project.BoundWithoutErrors,
            "A project with an unresolvable ProjectReference must not report BoundWithoutErrors=true.");
    }

    /// <summary>
    /// A hand-written file whose NAME matches a generated-file pattern
    /// (<c>*.Designer.cs</c>) but carries no <c>&lt;auto-generated&gt;</c> marker
    /// must still be translated — filename alone is not a generated-code signal.
    /// </summary>
    [Fact]
    public void LoadInMemory_IncludesHandWrittenFileNamedLikeGenerated()
    {
        const string handWritten = @"
namespace Sample
{
    public class Foo
    {
        public int Bar() => 42;
    }
}
";
        LoadedCSharpProject project = CSharpProjectLoader.LoadInMemory(
            new[] { ("Foo.Designer.cs", handWritten) });

        LoadedDocument document = Assert.Single(project.Documents);
        Assert.Equal("Foo.Designer.cs", document.FilePath);
        Assert.DoesNotContain(
            project.LoadDiagnostics,
            d => d.Descriptor.Id == "CS2GS0002");
    }

    /// <summary>
    /// A file carrying the standard <c>// &lt;auto-generated&gt;</c> header is a
    /// genuinely generated file and must still be excluded from translation,
    /// with an informational diagnostic recorded (not silent).
    /// </summary>
    [Fact]
    public void LoadInMemory_ExcludesGenuinelyGeneratedFile()
    {
        const string generated = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sample
{
    public class Foo
    {
        public int Bar() => 42;
    }
}
";
        LoadedCSharpProject project = CSharpProjectLoader.LoadInMemory(
            new[] { ("Foo.Designer.cs", generated) });

        Assert.Empty(project.Documents);
        Assert.Contains(
            project.LoadDiagnostics,
            d => d.Descriptor.Id == "CS2GS0002" && d.Severity == DiagnosticSeverity.Info);
    }

    /// <summary>
    /// N1/S2 (issue #1742 review follow-up): the project-directory-relative
    /// obj/bin exclusion in <c>IsGeneratedSource</c> is a path-boundary check —
    /// a file physically under <c>&lt;projDir&gt;/obj/</c> is excluded, but a
    /// hand-written file merely living in a folder whose name happens to START
    /// WITH <c>obj</c> (e.g. <c>src/obji/Foo.cs</c>, NOT the <c>obj</c> output
    /// dir) is not. The explicit <c>&lt;Compile Include&gt;</c> items below
    /// force both files into the compilation, bypassing the SDK's own default
    /// glob exclude for <c>obj/</c>/<c>bin/</c> so the loader's own boundary
    /// check is what is actually exercised.
    /// </summary>
    [Fact]
    public async Task LoadProjectAsync_ObjBinExclusion_IsPathBoundaryNotPrefixMatch()
    {
        string projectDir = NewScratchDir("obj-boundary");
        File.WriteAllText(Path.Combine(projectDir, "Directory.Build.props"), "<Project></Project>");

        Directory.CreateDirectory(Path.Combine(projectDir, "obj"));
        File.WriteAllText(
            Path.Combine(projectDir, "obj", "Manual.cs"),
            "public class ManualUnderObj { public int Bar() => 1; }");

        Directory.CreateDirectory(Path.Combine(projectDir, "src", "obji"));
        File.WriteAllText(
            Path.Combine(projectDir, "src", "obji", "Foo.cs"),
            "public class HandWrittenInObjiFolder { public int Bar() => 2; }");

        string projectPath = Path.Combine(projectDir, "ObjBoundary.csproj");
        File.WriteAllText(projectPath, @"<Project Sdk=""Microsoft.NET.Sdk"">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove=""obj/**/*.cs"" />
    <Compile Include=""obj/Manual.cs"" />
    <Compile Include=""src/obji/Foo.cs"" />
  </ItemGroup>
</Project>
");

        LoadedCSharpProject project = await CSharpProjectLoader.LoadProjectAsync(projectPath);

        Assert.DoesNotContain(project.Documents, d => d.FilePath.Replace('\\', '/').EndsWith("obj/Manual.cs", StringComparison.Ordinal));
        Assert.Contains(project.Documents, d => d.FilePath.Replace('\\', '/').EndsWith("src/obji/Foo.cs", StringComparison.Ordinal));
    }

    private static string NewScratchDir(string label)
    {
        string root = Path.Combine(AppContext.BaseDirectory, "loader-tests", label, Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        return root;
    }
}
