// <copyright file="Issue3676GeneratedCodeNullabilityTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Cs2Gs.CodeModel.Ast;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.CodeModel.RoundTrip;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Cs2Gs.Tests;

/// <summary>
/// Translator-fidelity tests for issue #3676 — the five GS0155 walls that kept
/// migrated <c>src/LanguageServer</c> (and, through it, <c>Repl</c>,
/// <c>LanguageServer.Tests</c> and <c>Compiler.Tests</c>) from binding.
///
/// <para>
/// Four of them share one cause: the C# compiler SUPPRESSES its nullable
/// diagnostics inside a file marked <c>&lt;auto-generated/&gt;</c>. The LSP
/// protocol plumbing carries that header to opt out of StyleCop
/// documentation/ordering rules — not because the files are machine-written —
/// so a nullable-ENABLED project's generated files hold reference annotations
/// the compiler never checked, and the surrounding code freely contradicts
/// them (<c>return null;</c> from a <c>string</c> method, <c>Filter = null</c>
/// into a <c>string Filter</c>). Face-value translation emits non-null G#
/// declarations and gsc, which has no such suppression, rejects the
/// <c>nil</c>. Those declarations are therefore decided by #2113's
/// whole-program taint evidence, exactly as an oblivious compilation's are.
/// </para>
///
/// <para>
/// Issue #3907 extends the fifth to assignment and argument position; the
/// discrimination witness is the pair of "keeps nullable" tests, which fail if
/// the rewrite ever stops consulting the DECLARED type and simply strips every
/// <c>?</c> off a <c>default</c>.
///
/// The fifth is unrelated to generated code: a bare <c>default</c> literal
/// target-typed to an unconstrained type parameter picks up Roslyn's
/// FLOW-derived <c>T?</c> ("maybe default") rather than the declared bare
/// <c>T</c>, and cs2gs emitted <c>default(T?)</c> into a <c>T</c> slot.
/// </para>
/// </summary>
public class Issue3676GeneratedCodeNullabilityTests
{
    // The `Protocol/TestModels.cs` + `TestDiscoveryComputer.cs` pair: the model
    // is marked generated and declares non-null `string Filter` /
    // `Item[] Children`, while the hand-authored computer writes `null` into
    // both from an object initializer in a DIFFERENT file. `Label` is the
    // control — same file, same shape, never assigned null.
    private const string GeneratedModelSource = @"// <auto-generated/>
namespace Demo
{
    public sealed class Item
    {
        public string Label { get; set; }

        public string Filter { get; set; }

        public Item[] Children { get; set; }
    }
}";

    /// <summary>
    /// TestDiscoveryComputer.gs:55 (`GS0155 nil -> string`). A generated file's
    /// non-null `string` property that a hand-authored file assigns `null`
    /// renders `string?`. The `= null` lives outside the declaring type's own
    /// syntax, so only the whole-program taint fixpoint can see it — the local
    /// `IsUsedAsNullable` fallback scopes a property to its declaring type.
    /// </summary>
    [Fact]
    public void GeneratedFileProperty_AssignedNullFromAnotherFile_PromotesDeclaration()
    {
        string[] printed = TranslateEnabled(
            ("Model.cs", GeneratedModelSource),
            ("Computer.cs", @"
namespace Demo
{
    public static class Computer
    {
        public static Item Group(string label)
        {
            return new Item { Label = label, Filter = null, Children = null };
        }
    }
}"));

        Assert.Contains("Filter string?", printed[0]);
        Assert.Contains("Filter: nil", printed[1]);
    }

    /// <summary>
    /// TestDiscoveryComputer.gs:88 (`GS0155 nil -> []TestDiscoveryItem`). The
    /// same promotion applies to an ARRAY-typed generated property, so the
    /// emitted element type is `[]Item?` rather than a non-null `[]Item`.
    /// </summary>
    [Fact]
    public void GeneratedFileArrayProperty_AssignedNullFromAnotherFile_PromotesDeclaration()
    {
        string[] printed = TranslateEnabled(
            ("Model.cs", GeneratedModelSource),
            ("Computer.cs", @"
namespace Demo
{
    public static class Computer
    {
        public static Item Leaf(string label)
        {
            return new Item { Label = label, Filter = label, Children = null };
        }
    }
}"));

        // Issue #1212: an ARRAY's own nullability is spelled `[]?T`; `[]T?`
        // would instead be an array of nullable elements.
        Assert.Contains("Children []?Item", printed[0]);
    }

    /// <summary>
    /// Promotion is EVIDENCE-driven, not a blanket widening of every generated
    /// file's reference members: `Label` is declared in the same generated file
    /// with the same `string` shape but is never assigned null, so it stays
    /// non-null. Without this the fix would trade five walls for a use-site
    /// explosion of `!!` on declarations the C# really does keep non-null.
    /// </summary>
    [Fact]
    public void GeneratedFileProperty_NeverAssignedNull_StaysNonNullable()
    {
        string[] printed = TranslateEnabled(
            ("Model.cs", GeneratedModelSource),
            ("Computer.cs", @"
namespace Demo
{
    public static class Computer
    {
        public static Item Group(string label)
        {
            return new Item { Label = label, Filter = null, Children = null };
        }
    }
}"));

        Assert.Contains("Label string", printed[0]);
        Assert.DoesNotContain("Label string?", printed[0]);
    }

    /// <summary>
    /// Models.gs:20 (`GS0155 nil -> string`). A generated file's method
    /// declared to return a non-null `string` while its own body does
    /// `return null;` — CS8603, silenced by the header — renders `string?`.
    /// Method returns never reach the local usage fallback at all (it is
    /// explicitly `symbol is not IMethodSymbol`), so this shape depends
    /// entirely on the taint path being reachable for generated declarations.
    /// </summary>
    [Fact]
    public void GeneratedFileMethod_ReturningNull_PromotesReturnType()
    {
        string[] printed = TranslateEnabled(
            ("Uri.cs", @"// <auto-generated/>
namespace Demo
{
    public sealed class DocumentUri
    {
        private readonly string uri;

        public DocumentUri(string uri) => this.uri = uri;

        public string GetFileSystemPath()
        {
            if (string.IsNullOrEmpty(this.uri))
            {
                return null;
            }

            return this.uri;
        }
    }
}"));

        Assert.Contains("func GetFileSystemPath() string?", printed[0]);
    }

    /// <summary>
    /// The negative control for the generated-code gate itself: the IDENTICAL
    /// class WITHOUT the header is a file whose annotations the C# compiler did
    /// check (it reports CS8603 here), so its declared `string` return is a
    /// real contract and must survive translation unpromoted. Only the
    /// suppression makes an annotation untrustworthy.
    /// </summary>
    [Fact]
    public void HandAuthoredMethod_ReturningNull_KeepsDeclaredNonNullReturn()
    {
        string[] printed = TranslateEnabled(
            roundTripOnlyReason: "hand-authored `return null` from a non-null `string` is the C# warning (CS8603) this fix deliberately does NOT rewrite",
            sources: ("Uri.cs", @"
namespace Demo
{
    public sealed class DocumentUri
    {
        private readonly string uri;

        public DocumentUri(string uri) => this.uri = uri;

        public string GetFileSystemPath()
        {
            if (string.IsNullOrEmpty(this.uri))
            {
                return null;
            }

            return this.uri;
        }
    }
}"));

        Assert.Contains("func GetFileSystemPath() string", printed[0]);
        Assert.DoesNotContain("func GetFileSystemPath() string?", printed[0]);
    }

    /// <summary>
    /// Promotion and forgiveness must stay symmetric — and issue #3848 changed
    /// which way the symmetry resolves for a GENERATED sink.
    ///
    /// <para>This test used to assert the opposite: `Location { Uri = … }` kept
    /// its non-null target and the promoted call was bridged with `!!`. That
    /// bridge is a RUNTIME throw in G#, and `Location.Uri` is itself generated
    /// — a declaration whose annotation the C# compiler stopped checking — so
    /// the `!!` fired on exactly the null the C# accepted. It was ten of the
    /// twenty-four migrated `LanguageServer.Tests` failures. The owner's
    /// decision on #3848 is that a promoted generated value written into a
    /// generated sink promotes THAT sink instead, which is the only rendering
    /// that matches the C#'s runtime behaviour.</para>
    ///
    /// <para>The symmetry the original test was protecting has not gone away,
    /// it has moved to where the compiler really did check the write: a
    /// HAND-AUTHORED, nullable-enabled sink still keeps its non-null contract
    /// and still gets its `!!`. Both halves are asserted here.</para>
    /// </summary>
    [Fact]
    public void PromotedGeneratedReturn_WidensAGeneratedSink_ButNotAHandAuthoredOne()
    {
        string[] printed = TranslateEnabled(
            ("Model.cs", @"// <auto-generated/>
namespace Demo
{
    public sealed class DocumentUri
    {
        public static DocumentUri FromFileSystemPath(string path)
        {
            if (string.IsNullOrEmpty(path))
            {
                return null;
            }

            return new DocumentUri();
        }
    }

    public sealed class Location
    {
        public DocumentUri Uri { get; set; }
    }
}"),
            ("Resolver.cs", @"
namespace Demo
{
    public sealed class Bookmark
    {
        public DocumentUri Target { get; set; } = new DocumentUri();
    }

    public static class Resolver
    {
        public static Location Resolve(string filePath)
        {
            return new Location { Uri = DocumentUri.FromFileSystemPath(filePath) };
        }

        public static Bookmark Mark(string filePath)
        {
            return new Bookmark { Target = DocumentUri.FromFileSystemPath(filePath) };
        }
    }
}"));

        Assert.Contains("func FromFileSystemPath(path string) DocumentUri?", printed[0]);

        // The GENERATED sink widens with the value it receives, and the runtime
        // assertion that used to throw here is gone.
        Assert.Contains("Uri DocumentUri?", printed[0]);
        Assert.Contains("Uri: DocumentUri.FromFileSystemPath(filePath)", printed[1]);
        Assert.DoesNotContain("Uri: DocumentUri.FromFileSystemPath(filePath)!!", printed[1]);

        // The HAND-AUTHORED sink does not. The C# compiler checked that write,
        // so its annotation stands and the bridge stays.
        Assert.Contains("Target: DocumentUri.FromFileSystemPath(filePath)!!", printed[1]);
    }

    /// <summary>
    /// Promotion needs DIRECT null evidence, not #2113's transitive taint
    /// fixpoint. That fixpoint reasons about a compilation where every
    /// annotation is oblivious and has nothing else to go on; over an annotated
    /// graph its forwarding edges over-promote. This is the `LspJson.Options`
    /// shape it got wrong — a generated static property initialized from a
    /// factory that only ever returns a freshly constructed value — which then
    /// failed to bind at the non-null StreamJsonRpc formatter property that
    /// consumes it.
    /// </summary>
    [Fact]
    public void GeneratedFileProperty_InitializedFromNonNullFactory_StaysNonNullable()
    {
        string[] printed = TranslateEnabled(
            ("Json.cs", @"// <auto-generated/>
namespace Demo
{
    public sealed class Settings
    {
        public string Name { get; set; }
    }

    public static class Defaults
    {
        public static Settings Options { get; } = Create();

        private static Settings Create()
        {
            var options = new Settings { Name = ""default"" };
            return options;
        }
    }
}"),
            ("Consumer.cs", @"
namespace Demo
{
    public sealed class Formatter
    {
        public Settings Options { get; set; } = Defaults.Options;
    }
}"));

        Assert.Contains("prop Options Settings", printed[0]);
        Assert.DoesNotContain("prop Options Settings?", printed[0]);
        Assert.DoesNotContain("func Create() Settings?", printed[0]);
    }

    /// <summary>
    /// A generated-code member that OVERRIDES another declaration does not own
    /// its signature: its parameter and return types are fixed by the base, so
    /// promoting one produces an override that no longer matches what it
    /// overrides. This is how the `<auto-generated/>` LSP
    /// `JsonConverter&lt;T&gt;` subclasses first broke — a whole family of
    /// GS0185/GS0386/GS0387 — even though `return null;` really does flow
    /// there. Such members keep their declared types and rely on the ordinary
    /// use-site forgiveness pass instead.
    /// </summary>
    [Fact]
    public void GeneratedFileOverride_ReturningNull_KeepsBaseSignature()
    {
        string[] printed = TranslateEnabled(
            ("Base.cs", @"
namespace Demo
{
    public sealed class Payload
    {
    }

    public abstract class Converter
    {
        public abstract Payload Read(string text);
    }
}"),
            ("Derived.cs", @"// <auto-generated/>
namespace Demo
{
    public sealed class PayloadConverter : Converter
    {
        public override Payload Read(string text)
        {
            return null;
        }
    }
}"));

        Assert.Contains("override func Read(text string) Payload", printed[1]);
        Assert.DoesNotContain("override func Read(text string) Payload?", printed[1]);
    }

    /// <summary>
    /// LspServer.gs:609 (`GS0155 T? -> T`). The `GuardAsync&lt;T&gt;` shape: a
    /// bare `default` returned from a method whose DECLARED return type is an
    /// unconstrained `T`. Roslyn's `ConvertedType` there is `T?` purely as a
    /// flow state, but G#'s `T?` on an unconstrained parameter is a different
    /// TYPE, so the honest emission is `default(T)` — which is also exactly
    /// what C# `default` compiles to.
    /// </summary>
    [Fact]
    public void BareDefault_UnconstrainedTypeParameterReturn_EmitsDefaultOfBareT()
    {
        string[] printed = TranslateEnabled(
            ("Guard.cs", @"
using System;

namespace Demo
{
    public static class Guard
    {
        public static T Run<T>(Func<T> body)
        {
            try
            {
                return body();
            }
            catch (Exception)
            {
                return default;
            }
        }
    }
}"));

        Assert.Contains("default(T)", printed[0]);
        Assert.DoesNotContain("default(T?)", printed[0]);
    }

    /// <summary>
    /// The rewrite reads the DECLARED return type, so an explicitly authored
    /// `T?` result is untouched: both the declaration and its `default` keep
    /// the `?` that the C# author actually wrote.
    /// </summary>
    [Fact]
    public void BareDefault_DeclaredNullableTypeParameterReturn_KeepsNullableDeclaration()
    {
        string[] printed = TranslateEnabled(
            ("Guard.cs", @"
namespace Demo
{
    public static class Guard
    {
        public static T? Missing<T>()
            where T : class
        {
            return default;
        }
    }
}"));

        Assert.Contains("func Missing[T class]() T?", printed[0]);
        Assert.Contains("return default(T?)", printed[0]);
    }

    /// <summary>
    /// Issue #3907: the same flow-vs-declared confusion in ASSIGNMENT position.
    /// <c>Gsharp.Runtime.Channels</c> is built on
    /// <c>[MaybeNullWhen(false)] out T value</c> parameters whose bodies say
    /// <c>value = default;</c> — the attribute makes Roslyn's flow state
    /// maybe-null while the DECLARED parameter type stays a bare <c>T</c>, so
    /// the return-only rewrite left <c>default(T?)</c> in a <c>T</c> slot.
    /// </summary>
    [Fact]
    public void BareDefault_AssignedToMaybeNullWhenOutParameter_EmitsDefaultOfBareT()
    {
        string[] printed = TranslateEnabled(
            ("Node.cs", @"
using System.Diagnostics.CodeAnalysis;

namespace Demo
{
    public class Node<T>
    {
        public bool TryTake([MaybeNullWhen(false)] out T value)
        {
            value = default;
            return false;
        }
    }
}"));

        Assert.Contains("value = default(T)", printed[0]);
        Assert.DoesNotContain("default(T?)", printed[0]);
    }

    /// <summary>
    /// Issue #3907: a field the author DECLARED <c>T?</c> keeps its <c>?</c>.
    /// The rewrite reads the declaration, so it must not follow the assignment
    /// blindly — this is the assignment-position counterpart of the
    /// <c>T?</c>-return test above.
    /// </summary>
    [Fact]
    public void BareDefault_AssignedToDeclaredNullableField_KeepsNullable()
    {
        string[] printed = TranslateEnabled(
            ("Node.cs", @"
namespace Demo
{
    public class Node<T>
    {
        private T? slot;

        public void Clear()
        {
            slot = default;
        }
    }
}"));

        Assert.Contains("slot = default(T?)", printed[0]);
    }

    /// <summary>
    /// Issue #3907: ARGUMENT position, read off the SUBSTITUTED parameter type.
    /// <c>ReceiveResult[T](default, false)</c> passes a bare <c>T</c> slot and
    /// must drop the flow <c>?</c>; issue #2500's <c>Same&lt;T?&gt;(default)</c>
    /// resolves to a parameter of type <c>T?</c> and must keep it. Both are
    /// asserted here so neither can regress without the other noticing.
    /// </summary>
    [Fact]
    public void BareDefault_AsArgument_FollowsTheSubstitutedParameterType()
    {
        string[] printed = TranslateEnabled(
            ("Result.cs", @"
namespace Demo
{
    public readonly struct Result<T>
    {
        public Result(T value, bool ok)
        {
            this.Value = value;
            this.Ok = ok;
        }

        public T Value { get; }

        public bool Ok { get; }

        public static Result<T> Empty => new Result<T>(default, false);
    }

    public static class Same
    {
        public static T Of<T>(T value) => value;

        public static T? Nullable<T>()
            where T : class
            => Of<T?>(default);
    }
}"));

        Assert.Contains("Result[T](default(T), false)", printed[0]);
        Assert.Contains("Of[T?](default(T?))", printed[0]);
    }

    private static string[] TranslateEnabled(params (string Path, string Source)[] sources)
        => TranslateEnabled(roundTripOnlyReason: null, sources);

    private static string[] TranslateEnabled(
        string roundTripOnlyReason,
        params (string Path, string Source)[] sources)
    {
        SyntaxTree[] trees = sources
            .Select(source => CSharpSyntaxTree.ParseText(
                source.Source,
                new CSharpParseOptions(LanguageVersion.Latest),
                path: source.Path))
            .ToArray();

        CSharpCompilation compilation = CSharpCompilation.Create(
            "Snippet",
            trees,
            CSharpProjectLoader.RuntimeReferences().ToImmutableArray(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                .WithNullableContextOptions(NullableContextOptions.Enable));

        Assert.DoesNotContain(
            compilation.GetDiagnostics(),
            diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);

        var documents = trees
            .Select(tree => new LoadedDocument(
                tree.FilePath,
                tree,
                compilation.GetSemanticModel(tree)))
            .ToArray();

        var printed = new List<string>();
        foreach (LoadedDocument document in documents)
        {
            var context = new TranslationContext(
                compilation,
                document.SemanticModel,
                document.FilePath,
                new[] { compilation });
            CompilationUnit unit = new CSharpToGSharpTranslator().TranslateDocument(document, context);
            printed.Add(GSharpPrinter.Print(unit));
        }

        RoundTripResult result = roundTripOnlyReason is null
            ? TranslationTestValidation.AssertBinds(printed.ToArray())
            : TranslationTestValidation.ValidateRoundTripOnly(printed[0], roundTripOnlyReason);
        Assert.True(
            result.Success,
            "Translated G# must bind. Errors:\n" +
                string.Join("\n", result.Errors) +
                "\n\nPrinted:\n" + string.Join("\n----\n", printed));
        return printed.ToArray();
    }
}
