// <copyright file="Issue4370LibraryImportTranslationTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.Loader;
using Cs2Gs.CodeModel.Ast;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Xunit;
using GSharpCompilation = GSharp.Core.CodeAnalysis.Compilation.Compilation;
using GSharpSourceText = GSharp.Core.CodeAnalysis.Text.SourceText;
using GSharpSyntaxTree = GSharp.Core.CodeAnalysis.Syntax.SyntaxTree;

namespace Cs2Gs.Tests;

/// <summary>
/// Issue #4370: a C# <c>[LibraryImport]</c> partial method translates to the
/// native body-less G# <c>@LibraryImport</c> declaration (gsc builds the
/// marshalling wrapper itself, ADR-0092) instead of disappearing because its
/// implementation is LibraryImportGenerator output; marshalling surface gsc
/// does not honour is reported; and any other partial member implemented by
/// untranslated generated code is reported rather than silently dropped.
/// </summary>
/// <remarks>
/// The fixtures model the generator output as a second
/// <c>// &lt;auto-generated/&gt;</c> document holding the implementation part —
/// the shape a real build hands cs2gs (the loader drops that document, the
/// compilation still sees it).
/// </remarks>
public class Issue4370LibraryImportTranslationTests
{
    private const string IssueRepro = @"
using System.Runtime.InteropServices;

public static partial class Native
{
    [LibraryImport(""libc"", EntryPoint = ""getpid"")]
    public static partial int GetPid();

    public static int Call() => GetPid();
}";

    private const string IssueReproGenerated = @"// <auto-generated/>
public static partial class Native
{
    public static partial int GetPid() => 0;
}";

    [Fact]
    public void IssueRepro_TranslatesToNativeLibraryImport_BindsCompilesAndRuns()
    {
        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Native.cs", IssueRepro),
            ("Native.g.cs", IssueReproGenerated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("@LibraryImport(\"libc\", EntryPoint: \"getpid\")", printed, StringComparison.Ordinal);
        Assert.Contains("func GetPid() int32;", printed, StringComparison.Ordinal);
        Assert.DoesNotContain("partial func", printed, StringComparison.Ordinal);
        Assert.Contains("func Call() int32 -> GetPid()", printed, StringComparison.Ordinal);

        // The import is a static member of the type (inside `shared`), not a
        // top-level function: C# callers reach it as Native.GetPid.
        int shared = printed.IndexOf("shared {", StringComparison.Ordinal);
        Assert.True(shared >= 0 && shared < printed.IndexOf("func GetPid", StringComparison.Ordinal), printed);

        TranslationTestValidation.AssertBinds(printed);
        Assembly assembly = CompileInProcess(printed);
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux) || RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
        {
            Type native = assembly.GetTypes().Single(type => type.Name == "Native");
            object pid = native.GetMethod("Call", BindingFlags.Public | BindingFlags.Static).Invoke(null, null);
            Assert.Equal(Environment.ProcessId, (int)pid);
        }
    }

    [Fact]
    public void AttributeArguments_AreMappedFromTheirConstantValues()
    {
        const string source = @"
using System.Runtime.InteropServices;

namespace Demo
{
    internal static partial class Libc
    {
        private const string LibName = ""libc"";

        [LibraryImport(LibName, EntryPoint = ""strlen"", StringMarshalling = StringMarshalling.Utf8, SetLastError = true)]
        internal static partial nint StrLen(string text);

        [LibraryImport(LibName, EntryPoint = ""time"")]
        private static partial long Time(ref long t);

        [LibraryImport(LibName, EntryPoint = ""time"")]
        private static partial long TimeOut(out long t);

        [LibraryImport(LibName)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static partial bool isatty([MarshalAs(UnmanagedType.I4)] int fd);

        public static long Now()
        {
            long t = 0;
            Time(ref t);
            TimeOut(out long u);
            return isatty(0) ? t : u + StrLen(""x"");
        }
    }
}";
        const string generated = @"// <auto-generated/>
namespace Demo
{
    internal static partial class Libc
    {
        internal static partial nint StrLen(string text) => 0;
        private static partial long Time(ref long t) => t = 0;
        private static partial long TimeOut(out long t) => t = 0;
        private static partial bool isatty(int fd) => false;
    }
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Libc.cs", source),
            ("Libc.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);

        // The const library name reaches gsc as the string literal its
        // P/Invoke binder requires; the enum argument keeps its member name.
        Assert.Contains(
            "@LibraryImport(\"libc\", EntryPoint: \"strlen\", StringMarshalling: StringMarshalling.Utf8, SetLastError: true)",
            printed,
            StringComparison.Ordinal);
        Assert.Contains("internal func StrLen(text string) nint;", printed, StringComparison.Ordinal);
        Assert.Contains("private func Time(ref t int64) int64;", printed, StringComparison.Ordinal);
        Assert.Contains("private func TimeOut(out t int64) int64;", printed, StringComparison.Ordinal);
        Assert.Contains("@return:MarshalAs(UnmanagedType.Bool)", printed, StringComparison.Ordinal);
        Assert.Contains("isatty(@MarshalAs(UnmanagedType.I4) fd int32) bool;", printed, StringComparison.Ordinal);
        Assert.DoesNotContain("@LibraryImport(LibName", printed, StringComparison.Ordinal);

        TranslationTestValidation.AssertBinds(printed);
        CompileInProcess(printed);
    }

    [Fact]
    public void UnimplementedLibraryImportDefinition_IsStillEmittedAndItsCallSiteKept()
    {
        // No generator output at all: a private void partial definition is
        // legal C# on its own, and would otherwise be elided WITH its call
        // site as an unimplemented partial method.
        const string source = @"
using System.Runtime.InteropServices;

public static partial class Native
{
    [LibraryImport(""libc"", EntryPoint = ""sync"")]
    static partial void Sync();

    public static void Flush()
    {
        Sync();
    }
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(("Native.cs", source));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("func Sync();", printed, StringComparison.Ordinal);
        Assert.Contains("Sync()\n", printed.Replace("\r\n", "\n", StringComparison.Ordinal), StringComparison.Ordinal);
        TranslationTestValidation.AssertBinds(printed);
    }

    [Theory]
    [InlineData(
        "[LibraryImport(\"libc\", StringMarshallingCustomType = typeof(Marshaller))] public static partial int F(int x);",
        "StringMarshallingCustomType")]
    [InlineData(
        "[LibraryImport(\"libc\")] public static partial int F([MarshalUsing(typeof(Marshaller))] int x);",
        "[MarshalUsing]")]
    [InlineData(
        "[LibraryImport(\"libc\")] [UnmanagedCallConv(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })] public static partial int F(int x);",
        "[UnmanagedCallConv]")]
    [InlineData(
        "[LibraryImport(\"libc\")] [return: MarshalAs(UnmanagedType.U1)] public static partial bool F(int x);",
        "[return: MarshalAs]")]
    [InlineData(
        "[LibraryImport(\"libc\")] public static partial int F(Handle x);",
        "[NativeMarshalling]")]
    public void UnsupportedMarshallingSurface_IsReported(string declaration, string expectedFragment)
    {
        string source = @"
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

public sealed class Marshaller
{
}

[NativeMarshalling(typeof(Marshaller))]
public struct Handle
{
    public int Value;
}

public static partial class Native
{
    " + declaration + @"
}";
        string implementationParameter = declaration.Contains("Handle x", StringComparison.Ordinal) ? "Handle x" : "int x";
        string implementationReturn = declaration.Contains("partial bool", StringComparison.Ordinal) ? "bool" : "int";
        string generated = "// <auto-generated/>\npublic static partial class Native\n{\n    public static partial "
            + implementationReturn + " F(" + implementationParameter + ") => default;\n}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Native.cs", source),
            ("Native.g.cs", generated));

        TranslationDiagnostic unsupported = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains(expectedFragment, unsupported.Message, StringComparison.Ordinal);
        Assert.Contains("'F'", unsupported.Message, StringComparison.Ordinal);

        // The import is still emitted so the rest of the type translates.
        Assert.Contains("func F(", printed, StringComparison.Ordinal);
    }

    [Fact]
    public void CdeclUnmanagedCallConv_TranslatesWithWarning()
    {
        // The Raylib-cs shape: a const library name plus CallConvCdecl, which
        // is gsc's platform default everywhere but 32-bit Windows.
        const string source = @"
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

public static unsafe partial class Raylib
{
    public const string NativeLibName = ""libc"";

    [LibraryImport(NativeLibName, EntryPoint = ""getpid"")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int GetPid();

    [LibraryImport(NativeLibName, EntryPoint = ""strlen"")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial nint StrLen(sbyte* text);
}";
        const string generated = @"// <auto-generated/>
public static unsafe partial class Raylib
{
    public static partial int GetPid() => 0;
    public static partial nint StrLen(sbyte* text) => 0;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Raylib.cs", source),
            ("Raylib.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Equal(
            2,
            diagnostics.Count(diagnostic =>
                diagnostic.Severity == TranslationSeverity.Warning
                && diagnostic.Message.Contains("CallConvCdecl", StringComparison.Ordinal)));
        Assert.Contains("@LibraryImport(\"libc\", EntryPoint: \"strlen\")", printed, StringComparison.Ordinal);
        Assert.Contains("func StrLen(text *int8) nint;", printed, StringComparison.Ordinal);

        TranslationTestValidation.AssertBinds(printed);
        Assembly assembly = CompileInProcess(printed);
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux) || RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
        {
            Type raylib = assembly.GetTypes().Single(type => type.Name == "Raylib");
            object pid = raylib.GetMethod("GetPid", BindingFlags.Public | BindingFlags.Static).Invoke(null, null);
            Assert.Equal(Environment.ProcessId, (int)pid);
        }
    }

    [Fact]
    public void StringReturn_ReportsOwnershipWarning()
    {
        const string source = @"
using System.Runtime.InteropServices;

public static partial class Native
{
    [LibraryImport(""libc"", EntryPoint = ""getenv"", StringMarshalling = StringMarshalling.Utf8)]
    public static partial string GetEnv(string name);
}";
        const string generated = @"// <auto-generated/>
public static partial class Native
{
    public static partial string GetEnv(string name) => null;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Native.cs", source),
            ("Native.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        TranslationDiagnostic warning = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Warning && diagnostic.Message.Contains("GetEnv", StringComparison.Ordinal));
        Assert.Contains("FreeCoTaskMem", warning.Message, StringComparison.Ordinal);
        TranslationTestValidation.AssertBinds(printed);
    }

    [Fact]
    public void PartialMethodImplementedOnlyByGeneratedCode_IsReportedNotSilentlyDropped()
    {
        // An unknown generator: the user declares the partial method, the
        // generator implements it, and cs2gs translates neither the generator
        // output nor (without its partner) the definition.
        const string source = @"
public static partial class Registry
{
    public static partial int Count();

    public static int Twice() => Count() * 2;
}";
        const string generated = @"// <auto-generated/>
public static partial class Registry
{
    public static partial int Count() => 21;
}";

        (_, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Registry.cs", source),
            ("Registry.Generated.g.cs", generated));

        TranslationDiagnostic unsupported = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("Registry.Count", unsupported.Message, StringComparison.Ordinal);
        Assert.Contains("Registry.Generated.g.cs", unsupported.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void PartialPropertyImplementedOnlyByGeneratedCode_IsReportedNotSilentlyDropped()
    {
        const string source = @"
public partial class Settings
{
    public partial string Theme { get; set; }
}";
        const string generated = @"// <auto-generated/>
public partial class Settings
{
    private string theme;

    public partial string Theme { get => theme; set => theme = value; }
}";

        (_, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Settings.cs", source),
            ("Settings.g.cs", generated));

        TranslationDiagnostic unsupported = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("Settings.Theme", unsupported.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void GeneratedImplementationThisRunTranslates_IsNotReported()
    {
        // A repository-layout migration also TRANSLATES a git-tracked
        // `<auto-generated>` file. When it is in the run's translated set,
        // its implementation reaches the G# output, so the definition's
        // omission is the ordinary partial rule, not a gap.
        const string source = @"
public static partial class Registry
{
    public static partial int Count();

    public static partial string Name { get; }

    public static string Show() => (Count() * 2).ToString() + Name;
}";
        const string generated = @"// <auto-generated/>
public static partial class Registry
{
    public static partial int Count() => 21;

    public static partial string Name => ""x"";
}";

        LoadedCSharpProject project = CSharpProjectLoader.LoadInMemory(new[]
        {
            ("Registry.cs", source),
            ("Registry.Generated.cs", generated),
        });
        Assert.True(project.BoundWithoutErrors, string.Join(Environment.NewLine, project.ErrorDiagnostics));
        var documents = project.Compilation.SyntaxTrees
            .Select(tree => new LoadedDocument(tree.FilePath, tree, project.Compilation.GetSemanticModel(tree)))
            .ToList();
        var translator = new CSharpToGSharpTranslator(
            translatedFilePaths: documents.Select(document => document.FilePath).ToList());

        var diagnostics = new List<TranslationDiagnostic>();
        var printed = new List<string>();
        foreach (LoadedDocument document in documents)
        {
            var context = new TranslationContext(project.Compilation, document.SemanticModel, document.FilePath);
            printed.Add(GSharpPrinter.Print(translator.TranslateDocument(document, context)));
            diagnostics.AddRange(context.Diagnostics);
        }

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("func Count() int32 -> 21", printed[1], StringComparison.Ordinal);
        TranslationTestValidation.AssertBinds(printed.ToArray());
    }

    [Fact]
    public void GeneratedRegexPartialProperty_IsReportedNotSilentlyDropped()
    {
        // TryTranslateGeneratedRegex rewrites partial METHODS only; the
        // property form would otherwise vanish (GS0157 at its uses).
        const string source = @"
using System.Text.RegularExpressions;

public static partial class Rx
{
    [GeneratedRegex(""a+b"")]
    private static partial Regex AbProp { get; }

    public static bool Test(string s) => AbProp.IsMatch(s);
}";
        const string generated = @"// <auto-generated/>
using System.Text.RegularExpressions;

public static partial class Rx
{
    private static partial Regex AbProp => new Regex(""a+b"");
}";

        (_, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Rx.cs", source),
            ("Rx.g.cs", generated));

        TranslationDiagnostic unsupported = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("Rx.AbProp", unsupported.Message, StringComparison.Ordinal);
        Assert.Contains("partial METHODS", unsupported.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void ObservablePartialProperty_ReportPointsAtTheFieldForm()
    {
        const string source = @"
namespace CommunityToolkit.Mvvm.ComponentModel
{
    [System.AttributeUsage(System.AttributeTargets.Field | System.AttributeTargets.Property)]
    public sealed class ObservablePropertyAttribute : System.Attribute
    {
    }
}

public partial class Vm
{
    [CommunityToolkit.Mvvm.ComponentModel.ObservableProperty]
    public partial string Title { get; set; }
}";
        const string generated = @"// <auto-generated/>
public partial class Vm
{
    private string title;

    public partial string Title { get => title; set => title = value; }
}";

        (_, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Vm.cs", source),
            ("Vm.g.cs", generated));

        TranslationDiagnostic unsupported = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("field form of [ObservableProperty]", unsupported.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void StringMarshalAs_Utf8OnEveryString_FoldsIntoStringMarshalling()
    {
        const string source = @"
using System.Runtime.InteropServices;

public static partial class Env
{
    [LibraryImport(""libc"", EntryPoint = ""getenv"")]
    [return: MarshalAs(UnmanagedType.LPUTF8Str)]
    public static partial string Get([MarshalAs(UnmanagedType.LPUTF8Str)] string name);

    [LibraryImport(""libc"", EntryPoint = ""strlen"")]
    public static partial nint Len([MarshalAs(UnmanagedType.LPUTF8Str)] string text);
}";
        const string generated = @"// <auto-generated/>
public static partial class Env
{
    public static partial string Get(string name) => null;
    public static partial nint Len(string text) => 0;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Env.cs", source),
            ("Env.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains(
            "@LibraryImport(\"libc\", EntryPoint: \"getenv\", StringMarshalling: StringMarshalling.Utf8)",
            printed,
            StringComparison.Ordinal);
        Assert.Contains(
            "@LibraryImport(\"libc\", EntryPoint: \"strlen\", StringMarshalling: StringMarshalling.Utf8)",
            printed,
            StringComparison.Ordinal);
        Assert.DoesNotContain("MarshalAs", printed, StringComparison.Ordinal);

        TranslationTestValidation.AssertBinds(printed);
        Assembly assembly = CompileInProcess(printed);
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux) || RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
        {
            Type env = assembly.GetTypes().Single(type => type.Name == "Env");
            object length = env.GetMethod("Len", BindingFlags.Public | BindingFlags.Static).Invoke(null, new object[] { "hello" });
            Assert.Equal((nint)5, (nint)length);
        }
    }

    [Theory]
    [InlineData(
        "[MarshalAs(UnmanagedType.LPUTF8Str)] string a, [MarshalAs(UnmanagedType.LPWStr)] string b",
        "string a, string b",
        "different encodings")]
    [InlineData(
        "[MarshalAs(UnmanagedType.LPStr)] string a",
        "string a",
        "UnmanagedType.LPStr")]
    [InlineData(
        "[MarshalAs(UnmanagedType.LPUTF8Str)] string a, string b",
        "string a, string b",
        "others have no encoding")]
    public void StringMarshalAs_GscCannotExpress_IsReported(string parameters, string implementationParameters, string expectedFragment)
    {
        string source = @"
using System.Runtime.InteropServices;

public static partial class Native
{
    [LibraryImport(""libc"")]
    public static partial int F(" + parameters + @");
}";
        string generated = "// <auto-generated/>\npublic static partial class Native\n{\n    public static partial int F("
            + implementationParameters + ") => 0;\n}";

        (_, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Native.cs", source),
            ("Native.g.cs", generated));

        TranslationDiagnostic unsupported = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains(expectedFragment, unsupported.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void AliasedMarshalAs_IsIdentifiedByType_FoldedAndRemoved()
    {
        // cs2gs keeps the alias spelling (`@MA`), so a rendered-name match
        // would fold the encoding yet leave `@MA` on the parameter (GS0360).
        const string source = @"
using System.Runtime.InteropServices;
using MA = System.Runtime.InteropServices.MarshalAsAttribute;

public static partial class Env
{
    [LibraryImport(""libc"", EntryPoint = ""strlen"")]
    public static partial nint Len([MA(UnmanagedType.LPUTF8Str)] string text);
}";
        const string generated = @"// <auto-generated/>
public static partial class Env
{
    public static partial nint Len(string text) => 0;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Env.cs", source),
            ("Env.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("StringMarshalling: StringMarshalling.Utf8", printed, StringComparison.Ordinal);
        Assert.DoesNotContain("@MA", printed, StringComparison.Ordinal);
        TranslationTestValidation.AssertBinds(printed);
        CompileInProcess(printed);
    }

    [Fact]
    public void UnrelatedMarshalAsAttribute_IsPreserved()
    {
        // A user attribute that merely shares the simple name is not
        // System.Runtime.InteropServices.MarshalAsAttribute: keep it.
        const string source = @"
using System.Runtime.InteropServices;

namespace MyNs
{
    [System.AttributeUsage(System.AttributeTargets.Parameter)]
    public sealed class MarshalAsAttribute : System.Attribute
    {
    }
}

public static partial class Env
{
    [LibraryImport(""libc"", EntryPoint = ""strlen"", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint Len([MyNs.MarshalAs] string text);
}";
        const string generated = @"// <auto-generated/>
public static partial class Env
{
    public static partial nint Len(string text) => 0;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Env.cs", source),
            ("Env.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("MarshalAs text string", printed.Replace("@MyNs.", "", StringComparison.Ordinal), StringComparison.Ordinal);
    }

    [Fact]
    public void AliasedLibraryImport_IsRecognizedAndItsArgumentsFolded()
    {
        const string source = @"
using LI = System.Runtime.InteropServices.LibraryImportAttribute;

public static partial class Native
{
    private const string Lib = ""libc"";

    [LI(Lib, EntryPoint = ""getpid"")]
    public static partial int GetPid();
}";
        const string generated = @"// <auto-generated/>
public static partial class Native
{
    public static partial int GetPid() => 0;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Native.cs", source),
            ("Native.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("(\"libc\", EntryPoint: \"getpid\")", printed, StringComparison.Ordinal);
        Assert.Contains("func GetPid() int32;", printed, StringComparison.Ordinal);
    }

    private static (string Printed, IReadOnlyList<TranslationDiagnostic> Diagnostics) Translate(
        params (string FileName, string Source)[] files)
    {
        LoadedCSharpProject project = CSharpProjectLoader.LoadInMemory(files);
        Assert.True(
            project.BoundWithoutErrors,
            "Snippet should bind with no C# errors: " +
                string.Join(Environment.NewLine, project.ErrorDiagnostics));

        // The loader drops the `<auto-generated>` generator output, as a real
        // build's loader does; only the hand-authored document translates.
        LoadedDocument document = Assert.Single(project.Documents);
        var context = new TranslationContext(project.Compilation, document.SemanticModel, document.FilePath);
        CompilationUnit unit = new CSharpToGSharpTranslator().TranslateDocument(document, context);
        return (GSharpPrinter.Print(unit), context.Diagnostics);
    }

    private static Assembly CompileInProcess(string source)
    {
        var compilation = new GSharpCompilation(GSharpSyntaxTree.Parse(GSharpSourceText.From(source)))
        {
            IsLibrary = true,
        };
        using var peStream = new MemoryStream();
        var result = compilation.Emit(peStream);
        Assert.True(
            result.Success,
            "Emit failed:\n" + string.Join("\n", result.Diagnostics.Select(d => d.ToString())) + "\n\n" + source);

        peStream.Position = 0;
        var loadContext = new AssemblyLoadContext("Issue4370-" + Guid.NewGuid().ToString("N"), isCollectible: true);
        return loadContext.LoadFromStream(peStream);
    }
}
