// <copyright file="Issue4645NoRootWorkspaceTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.IO;
using System.Threading.Tasks;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.Pipeline;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Xunit;

namespace Cs2Gs.Tests;

/// <summary>
/// The real LSP initialize/initialized path must pass an absent workspace root
/// to its null-tolerant initializer without a throwing migration bridge.
/// </summary>
public class Issue4645NoRootWorkspaceTests
{
    [Fact]
    public async Task LanguageServerSelfMigration_NoRootHasNoFailFastBridge()
    {
        string repoRoot = GsharpTestProjectRunner.FindRepoRoot();
        LoadedCSharpProject project = await CSharpProjectLoader.LoadProjectAsync(
            Path.Combine(repoRoot, "src", "LanguageServer", "LanguageServer.csproj"),
            includeAutoGenerated: true);
        Assert.True(
            project.BoundWithoutErrors,
            "LanguageServer should bind with no C# errors: "
                + string.Join(Environment.NewLine, project.ErrorDiagnostics));

        string server = Translate("LspServer.cs");
        Assert.Contains("func InitializeAsync(", server, StringComparison.Ordinal);
        Assert.Contains("func Initialized(", server, StringComparison.Ordinal);
        Assert.Contains("WorkspaceInitializer.Initialize(", server, StringComparison.Ordinal);
        Assert.DoesNotContain("rootPath!!", server, StringComparison.Ordinal);
        Assert.DoesNotContain("pendingWorkspaceRootPath!!", server, StringComparison.Ordinal);
        Assert.DoesNotContain("(request?.RootPath ?? request?.RootUri?.GetFileSystemPath())!!", server, StringComparison.Ordinal);

        string initializer = Translate("WorkspaceInitializer.cs");
        Assert.Contains("rootPath string?", initializer, StringComparison.Ordinal);

        string Translate(string name)
        {
            LoadedDocument document = Assert.Single(
                project.Documents,
                candidate => Path.GetFileName(candidate.FilePath) == name);
            var context = new TranslationContext(project.Compilation, document.SemanticModel, document.FilePath);
            return GSharpPrinter.Print(
                new CSharpToGSharpTranslator(preservePartialParts: true).TranslateDocument(document, context));
        }
    }
}
