// <copyright file="Issue3848PureForwardingPromotionTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using Cs2Gs.CodeModel.Ast;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.Pipeline;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Xunit;

namespace Cs2Gs.Tests;

/// <summary>
/// Issue #3848, family A — promotion along a PURE FORWARDING EDGE.
///
/// <para>#3676/#3851 promote a declaration in an <c>&lt;auto-generated/&gt;</c>
/// file to <c>T?</c> when the code writes null into it, because the C# compiler
/// suppressed its nullable diagnostics there and never checked the annotation.
/// The promotion stopped at that declaration. A hand-authored method that does
/// nothing but hand the value back — <c>CodeLensComputer.GetDocumentUri</c>,
/// whose two <c>return</c>s are <c>DocumentUri.FromFileSystemPath(…)</c> and
/// <c>DocumentUri.From(fallback)</c>, both generated and both already promoted —
/// lost it again, the use-site forgiveness pass bridged the gap with a
/// <c>!!</c>, and G#'s <c>!!</c> THREW on the null the C# happily returned. Ten
/// of the twenty-four <c>LanguageServer.Tests</c> parity failures were that one
/// <see cref="NullReferenceException"/>.</para>
///
/// <para><b>The rule.</b> Stated in full on
/// <c>ObliviousNullabilityAnalyzer.IsPromotedByPureForwarding</c>. In one
/// sentence: a method whose EVERY exit hands back, unchanged and directly, the
/// result of calling or reading an already-promoted declaration is promoted
/// with it; and such a forwarded value written into a GENERATED declaration
/// promotes that declaration too. Every chain is seeded by generated code and
/// bounded to four hops. Each clause below is pinned by a test, because each
/// exclusion is a place where the value could have stopped being the target's
/// value.</para>
///
/// <para><b>The boundary that keeps this safe</b> is the generated restriction
/// on the SINK half: a forwarded value written into a hand-authored,
/// nullable-ENABLED declaration promotes nothing and still gets its <c>!!</c>,
/// because there the compiler really did check the write. That is what
/// <see cref="ForwardedValue_WrittenToHandAuthoredSink_StillGetsItsAssertion"/>
/// and <see cref="TranslatedHandAuthoredSink_StillThrowsOnTheNull"/> hold down;
/// without them "promotion propagates everywhere" would pass this file.</para>
/// </summary>
public sealed class Issue3848PureForwardingPromotionTests
{
    // The `Protocol/Models.cs` shape: generated factories that really do return
    // null, and a generated model slot the forwarded value lands in.
    private const string GeneratedModelSource = """
        // <auto-generated/>
        namespace Repro
        {
            public sealed class Uri
            {
                private readonly string text;

                private Uri(string text) => this.text = text ?? string.Empty;

                public static Uri From(string value) => value == null ? null : new Uri(value);

                public static Uri FromPath(string path)
                {
                    if (string.IsNullOrEmpty(path))
                    {
                        return null;
                    }

                    return new Uri(path);
                }

                public static Uri Always() => new Uri("always");
            }

            public sealed class Location
            {
                public Uri Uri { get; set; }

                public int Line { get; set; }
            }
        }
        """;

    // The `CodeLensComputer` shape, hand-authored and nullable-ENABLED: a
    // two-exit forwarder over two promoted generated factories, whose result is
    // written into the generated `Location.Uri` slot.
    private const string ForwarderSource = """
        namespace Repro
        {
            public static class Computer
            {
                public static Location Make(string? path, string? fallback) => new Location
                {
                    Uri = GetUri(path, fallback),
                    Line = 1,
                };

                public static Uri Peek(string? fallback) => Uri.From(fallback);

                private static Uri GetUri(string? path, string? fallback)
                {
                    if (!string.IsNullOrEmpty(path))
                    {
                        return Uri.FromPath(path);
                    }

                    return Uri.From(fallback);
                }
            }
        }
        """;

    /// <summary>
    /// THE EXECUTING PROOF, and the shape #3848 family A actually is. gsc
    /// compiles the translated G# and a C# driver calls <c>Make(null, null)</c>.
    /// C# returns a <c>Location</c> whose <c>Uri</c> is <see langword="null"/>;
    /// before this change the migrated G# threw
    /// <see cref="NullReferenceException"/> out of the <c>!!</c> at
    /// <c>return Uri.From(fallback)</c>. A printed-shape assertion cannot tell
    /// these apart once someone "fixes" it by deleting the wrong <c>!!</c>, so
    /// the assertion is on the value the driver gets back.
    /// </summary>
    [Fact]
    public void TranslatedForwarderOverGeneratedNull_ReturnsNullInsteadOfThrowing()
    {
        Assert.Equal(
            DriverNullResult,
            RunDriver(
                nameof(TranslatedForwarderOverGeneratedNull_ReturnsNullInsteadOfThrowing),
                """
                namespace Repro
                {
                    public static class Driver
                    {
                        public static int Run()
                        {
                            try
                            {
                                var location = Computer.Make(null, null);
                                return location.Uri == null ? 1 : 2;
                            }
                            catch (System.NullReferenceException)
                            {
                                return 3;
                            }
                        }
                    }
                }
                """,
                ("Models.cs", GeneratedModelSource),
                ("Computer.cs", ForwarderSource)));
    }

    /// <summary>
    /// The same repro, read as shapes: the forwarder's return type is promoted,
    /// the generated sink it flows into is promoted with it (so the <c>!!</c>
    /// does not merely move one frame up), and no <c>!!</c> survives anywhere in
    /// the hand-authored file.
    ///
    /// <para>Also the MULTIPLE-TARGETS decision: <c>GetUri</c> forwards two
    /// DIFFERENT promoted callees, one per <c>return</c>. That is allowed —
    /// clause 6 is per-exit, and the union of two promoted value sets is
    /// promoted — and it is not a loosening chosen for convenience: the site
    /// this issue is about has exactly this shape.</para>
    /// </summary>
    [Fact]
    public void TwoExitForwarder_PromotesItselfAndItsGeneratedSink()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Computer.cs", ForwarderSource));

        Assert.Contains(
            "func GetUri(path string?, fallback string?) Uri?",
            printed["Computer.cs"],
            StringComparison.Ordinal);

        // Neither forwarded value is asserted any more — this is the `!!` whose
        // throw was ten of the twenty-four parity failures. (The surviving
        // `path!!` on the ARGUMENT is a different, harmless thing: gsc does not
        // narrow `path` from `!string.IsNullOrEmpty(path)` the way Roslyn does,
        // and the value provably is not null there.)
        Assert.Contains("return Uri.From(fallback)\n", printed["Computer.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("Uri.From(fallback)!!", printed["Computer.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain(")!!", printed["Computer.cs"], StringComparison.Ordinal);

        // The sink half: `Location.Uri` is a GENERATED declaration, so the
        // forwarded value is better evidence than its unchecked annotation.
        Assert.Contains("Uri Uri?", printed["Models.cs"], StringComparison.Ordinal);

        // ... and only that one. `Line` is written a non-null value and stays
        // non-null, so this is not "promote the whole generated file".
        Assert.Contains("Line int32", printed["Models.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("Line int32?", printed["Models.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// ANTI-VACUITY, the one that matters. A hand-authored, nullable-ENABLED
    /// sink is a write the C# compiler DID check, so its annotation stands and
    /// the genuinely-nullable forwarded value must STILL be asserted with
    /// <c>!!</c>. Delete the generated restriction on the sink half of the rule
    /// — i.e. let promotion propagate everywhere — and this test fails.
    /// </summary>
    [Fact]
    public void ForwardedValue_WrittenToHandAuthoredSink_StillGetsItsAssertion()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Computer.cs", ForwarderSource),
            ("Sink.cs", """
                namespace Repro
                {
                    public sealed class Bookmark
                    {
                        public Uri Target { get; set; } = Uri.Always();
                    }

                    public static class Bookmarks
                    {
                        public static Bookmark Create(string? fallback) => new Bookmark
                        {
                            Target = Computer.Peek(fallback),
                        };
                    }
                }
                """));

        // `Bookmark.Target` is hand-authored and non-null; the forwarded value
        // is `Uri?`; the bridge is the assertion, exactly as before.
        Assert.Contains("Target Uri", printed["Sink.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("Target Uri?", printed["Sink.cs"], StringComparison.Ordinal);
        Assert.Contains("!!", printed["Sink.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// The executing half of the anti-vacuity guard: the retained <c>!!</c> is a
    /// real runtime assertion, not decoration. A null really does arrive at the
    /// hand-authored sink and the migrated G# really does throw — which is what
    /// "the <c>!!</c> is still there" has to mean.
    /// </summary>
    [Fact]
    public void TranslatedHandAuthoredSink_StillThrowsOnTheNull()
    {
        Assert.Equal(
            DriverThrewResult,
            RunDriver(
                nameof(TranslatedHandAuthoredSink_StillThrowsOnTheNull),
                """
                namespace Repro
                {
                    public static class Driver
                    {
                        public static int Run()
                        {
                            try
                            {
                                var bookmark = Bookmarks.Create(null);
                                return bookmark.Target == null ? 1 : 2;
                            }
                            catch (System.NullReferenceException)
                            {
                                return 3;
                            }
                        }
                    }
                }
                """,
                ("Models.cs", GeneratedModelSource),
                ("Computer.cs", ForwarderSource),
                ("Sink.cs", """
                    namespace Repro
                    {
                        public sealed class Bookmark
                        {
                            public Uri Target { get; set; } = Uri.Always();
                        }

                        public static class Bookmarks
                        {
                            public static Bookmark Create(string? fallback) => new Bookmark
                            {
                                Target = Computer.Peek(fallback),
                            };
                        }
                    }
                    """)));
    }

    /// <summary>
    /// DECISION: a direct <c>return Target(x)</c> forwards; storing the result
    /// in a LOCAL first does not. The local is a different slot, and between the
    /// assignment and the <c>return</c> anything may happen to it — the
    /// commonest being the very normalisation <c>if (r == null) r = Default;</c>
    /// that makes the method non-null. Proving otherwise is a dataflow analysis
    /// this rule deliberately does not perform, so the conservative answer is
    /// "not pure", and the existing <c>!!</c> behaviour is unchanged there.
    /// </summary>
    [Fact]
    public void ForwardThroughLocal_IsNotPure()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Direct.cs", """
                namespace Repro
                {
                    public static class Direct
                    {
                        public static Uri Forward(string? value) => Uri.From(value);
                    }
                }
                """),
            ("ViaLocal.cs", """
                namespace Repro
                {
                    public static class ViaLocal
                    {
                        public static Uri Forward(string? value)
                        {
                            var result = Uri.From(value);
                            return result;
                        }
                    }
                }
                """));

        Assert.Contains("Uri?", printed["Direct.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("!!", printed["Direct.cs"], StringComparison.Ordinal);

        Assert.DoesNotContain("func Forward(value string?) Uri?", printed["ViaLocal.cs"], StringComparison.Ordinal);
        Assert.Contains("!!", printed["ViaLocal.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// DECISION: a conditional wrapper is NOT pure, and neither is <c>??</c>.
    /// Both deliberately substitute a value on one path, so the method's value
    /// set is not the target's — and in the <c>??</c> case it is the target's
    /// value set with the null REMOVED, so promoting it would make a provably
    /// non-null method nullable and cascade `T?` into every consumer, which is
    /// the over-promotion #3676 rejected.
    /// </summary>
    [Fact]
    public void ConditionalAndCoalesceWrappers_AreNotPure()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Wrappers.cs", """
                namespace Repro
                {
                    public static class Wrappers
                    {
                        public static Uri Guarded(string? value) =>
                            value is null ? Uri.Always() : Uri.From(value);

                        public static Uri Coalesced(string? value) =>
                            Uri.From(value) ?? Uri.Always();
                    }
                }
                """));

        Assert.DoesNotContain("func Guarded(value string?) Uri?", printed["Wrappers.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("func Coalesced(value string?) Uri?", printed["Wrappers.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// DECISION: promotion IS transitive across an overload chain — a forwarder
    /// forwarding a forwarder forwarding the real generated method — and it IS
    /// bounded. Four hops is the whole budget, so a chain long enough to exhaust
    /// it stops rather than running a whole-graph fixpoint. The bound is what
    /// separates this closure from #2113's, which #3676 rejected here.
    /// </summary>
    [Fact]
    public void OverloadChain_PropagatesTransitivelyButIsBounded()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Chain.cs", """
                namespace Repro
                {
                    public static class Chain
                    {
                        public static Uri Hop1(string? v) => Uri.From(v);

                        public static Uri Hop2(string? v) => Hop1(v);

                        public static Uri Hop3(string? v) => Hop2(v);

                        public static Uri Hop4(string? v) => Hop3(v);

                        public static Uri Hop5(string? v) => Hop4(v);

                        public static Uri Hop6(string? v) => Hop5(v);

                        public static Uri Hop7(string? v) => Hop6(v);
                    }
                }
                """));

        // Transitive: the links up to the hop budget really are promoted, so an
        // ordinary overload chain is not left half-migrated.
        Assert.Contains("func Hop2(v string?) Uri?", printed["Chain.cs"], StringComparison.Ordinal);
        Assert.Contains("func Hop3(v string?) Uri?", printed["Chain.cs"], StringComparison.Ordinal);
        Assert.Contains("func Hop4(v string?) Uri?", printed["Chain.cs"], StringComparison.Ordinal);

        // Bounded, and the bound is a PATH LENGTH, not an artefact of the order
        // the declarations happen to be visited in: each round is evaluated
        // against the previous round's snapshot, so exactly
        // `MaxForwardingHops` links propagate and the rest fall back to the
        // ordinary forgiveness pass.
        Assert.DoesNotContain("func Hop5(v string?) Uri?", printed["Chain.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("func Hop7(v string?) Uri?", printed["Chain.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// DECISION: whether the forwarder itself sits in a generated file is
    /// irrelevant — the evidence is the edge, and it is seeded by generated code
    /// either way. What IS disqualifying is not owning your own signature: an
    /// interface implementation's return type is fixed by the interface, and
    /// repainting one side alone desynchronises the two G# signatures (gsc
    /// GS0185/GS0386/GS0387), the same guard
    /// <c>IsEvidenceDecidedGeneratedDeclaration</c> already applies.
    /// </summary>
    [Fact]
    public void GeneratedForwarderPromotes_ButAnInterfaceImplementationDoesNot()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("GeneratedForwarder.cs", """
                // <auto-generated/>
                namespace Repro
                {
                    public static class GeneratedForwarder
                    {
                        public static Uri Forward(string value) => Uri.From(value);
                    }
                }
                """),
            ("Implementation.cs", """
                namespace Repro
                {
                    public interface IResolver
                    {
                        Uri Resolve(string? value);
                    }

                    public sealed class Resolver : IResolver
                    {
                        public Uri Resolve(string? value) => Uri.From(value);
                    }
                }
                """));

        Assert.Contains("Uri?", printed["GeneratedForwarder.cs"], StringComparison.Ordinal);

        // The interface member and its implementation both keep the declared
        // type and rely on the ordinary `!!`.
        Assert.DoesNotContain(
            "func Resolve(value string?) Uri?", printed["Implementation.cs"], StringComparison.Ordinal);
        Assert.Contains("!!", printed["Implementation.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// ANTI-VACUITY: nothing in a purely hand-authored graph can seed the
    /// closure. A method that forwards an ordinary, compiler-CHECKED non-null
    /// method keeps its non-null return — the rule only ever starts at a
    /// generated declaration the compiler stopped checking.
    /// </summary>
    [Fact]
    public void ForwarderOverACheckedNonNullTarget_IsNotPromoted()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Plain.cs", """
                namespace Repro
                {
                    public static class Plain
                    {
                        public static Uri Real() => Uri.Always();

                        public static Uri Forward() => Real();
                    }
                }
                """));

        Assert.DoesNotContain("func Real() Uri?", printed["Plain.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("func Forward() Uri?", printed["Plain.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// DECISION: only METHODS forward. A property getter that forwards another
    /// property keeps its declared type — the property-contract behaviour
    /// #1354/#2167 fixed, which the analyzer's own <c>SourceScope</c> remarks
    /// spell out — so the rule is not extended to accessors here.
    /// </summary>
    [Fact]
    public void PropertyGetterForwarding_IsOutOfScope()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Holder.cs", """
                namespace Repro
                {
                    public sealed class Holder
                    {
                        public Holder(string? seed) => this.Seed = seed;

                        public string? Seed { get; }

                        public Uri Current => Uri.From(this.Seed);
                    }
                }
                """));

        Assert.DoesNotContain("prop Current Uri?", printed["Holder.cs"], StringComparison.Ordinal);
    }

    private const int DriverNullResult = 1;

    private const int DriverThrewResult = 3;

    private static IReadOnlyDictionary<string, string> Translate(
        params (string Path, string Source)[] sources)
    {
        SyntaxTree[] trees = sources
            .Select(source => CSharpSyntaxTree.ParseText(
                source.Source,
                new CSharpParseOptions(LanguageVersion.Latest),
                path: source.Path))
            .ToArray();

        CSharpCompilation compilation = CSharpCompilation.Create(
            "Repro",
            trees,
            CSharpProjectLoader.RuntimeReferences().ToImmutableArray(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                .WithNullableContextOptions(NullableContextOptions.Enable));

        Assert.DoesNotContain(
            compilation.GetDiagnostics(),
            diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);

        var printed = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (SyntaxTree tree in trees)
        {
            var document = new LoadedDocument(tree.FilePath, tree, compilation.GetSemanticModel(tree));
            var context = new TranslationContext(
                compilation,
                document.SemanticModel,
                document.FilePath,
                new[] { compilation });
            CompilationUnit unit = new CSharpToGSharpTranslator().TranslateDocument(document, context);
            Assert.DoesNotContain(
                context.Diagnostics,
                diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
            printed[tree.FilePath] = GSharpPrinter.Print(unit);
        }

        return printed;
    }

    // Translates `sources`, compiles the result with gsc, compiles `driverSource`
    // as C# against the emitted assembly, and returns what `Repro.Driver.Run()`
    // answered. The whole point of this file is that only this can tell a
    // removed `!!` from a retained one at run time.
    private static int RunDriver(
        string name,
        string driverSource,
        params (string Path, string Source)[] sources)
    {
        string compiler = FindCompiler();
        Assert.True(compiler != null, "gsc.dll must be built for the runtime tests in this file.");

        IReadOnlyDictionary<string, string> printed = Translate(sources);
        string workDir = NewDirectory(name);
        var gsPaths = new List<string>();
        foreach ((string path, string _) in sources)
        {
            string gsPath = Path.Combine(workDir, Path.ChangeExtension(path, ".gs"));
            File.WriteAllText(gsPath, printed[path] + Environment.NewLine);
            gsPaths.Add(gsPath);
        }

        string libraryPath = Path.Combine(workDir, "Repro.dll");
        var arguments = new List<string> { compiler, "/target:library", "/out:" + libraryPath };
        arguments.AddRange(gsPaths);

        ProcessRunResult compile = ProcessRunner.Run("dotnet", arguments, workDir);
        Assert.True(
            compile.ExitCode == 0,
            "gsc must compile the translated forwarder. Output:\n" + compile.Output +
                "\nTranslated G#:\n" + string.Join("\n----\n", printed.Values));

        var loadContext = new AssemblyLoadContext(name, isCollectible: true);
        try
        {
            Assembly library = loadContext.LoadFromAssemblyPath(libraryPath);
            var references = new List<MetadataReference>(CSharpProjectLoader.RuntimeReferences())
            {
                MetadataReference.CreateFromFile(libraryPath),
            };

            CSharpCompilation driverCompilation = CSharpCompilation.Create(
                "Repro.Driver",
                new[]
                {
                    CSharpSyntaxTree.ParseText(
                        driverSource, new CSharpParseOptions(LanguageVersion.Latest)),
                },
                references,
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            string driverPath = Path.Combine(workDir, "Repro.Driver.dll");
            EmitResult emitted = driverCompilation.Emit(driverPath);
            Assert.True(
                emitted.Success,
                "The C# driver must compile against the gsc-emitted assembly. Diagnostics:\n" +
                    string.Join(Environment.NewLine, emitted.Diagnostics));

            Assembly driver = loadContext.LoadFromAssemblyPath(driverPath);
            object result = driver.GetType("Repro.Driver")!.GetMethod("Run")!.Invoke(null, null);
            _ = library;
            return Assert.IsType<int>(result);
        }
        finally
        {
            loadContext.Unload();
        }
    }

    private static string NewDirectory(string category)
    {
        string path = Path.Combine(
            AppContext.BaseDirectory,
            "issue-3848-pure-forwarding",
            category,
            Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(path);
        return path;
    }

    private static string FindCompiler()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            foreach (string config in new[] { "Release", "Debug" })
            {
                string candidate = Path.Combine(
                    dir.FullName, "out", "bin", config, "Compiler", "gsc.dll");
                if (File.Exists(candidate))
                {
                    return candidate;
                }
            }

            dir = dir.Parent;
        }

        return null;
    }
}
