// <copyright file="Issue2645NullableDefaultTargetTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using Cs2Gs.CodeModel.Ast;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Xunit;

namespace Cs2Gs.Tests;

public sealed class Issue2645NullableDefaultTargetTests
{
    [Fact]
    public void GeneratedTarget_PromotesBackingFieldForNullableReferenceDefaultOnly()
    {
        LoadedCSharpProject project = CSharpProjectLoader.LoadInMemory(new[]
        {
            ("MainWindowViewModel.cs", """
                namespace Oahu.Core.UI.Avalonia.ViewModels;

                public sealed class Bitmap { }

                public partial class MainWindowViewModel
                {
                    private Bitmap profileImage;

                    public void SetSignedInProfile(Bitmap profileImage = null)
                    {
                        ProfileImage = profileImage;
                    }

                    public void ClearSignedInProfile() => ProfileImage = null;

                    public static int? KeepCount(int? count = null) => count;
                }
                """),
            ("MainWindowViewModel.g.cs", """
                // <auto-generated/>
                #nullable enable
                namespace Oahu.Core.UI.Avalonia.ViewModels;

                public partial class MainWindowViewModel
                {
                    public Bitmap ProfileImage
                    {
                        get => profileImage;
                        set => profileImage = value;
                    }
                }
                """),
        });

        Assert.True(
            project.BoundWithoutErrors,
            "inline source should bind with no C# errors: " +
                string.Join(Environment.NewLine, project.ErrorDiagnostics));

        LoadedDocument document = Assert.Single(project.Documents);
        var context = new TranslationContext(project.Compilation, document.SemanticModel, document.FilePath);
        CompilationUnit unit = new CSharpToGSharpTranslator().TranslateDocument(document, context);
        string rendered = GSharpPrinter.Print(unit);

        Assert.Contains("profileImage Bitmap? = nil", rendered, StringComparison.Ordinal);
        Assert.Contains("private var profileImage Bitmap?", rendered, StringComparison.Ordinal);
        Assert.Contains("ProfileImage = profileImage", rendered, StringComparison.Ordinal);
        Assert.DoesNotContain("ProfileImage = profileImage!!", rendered, StringComparison.Ordinal);
        Assert.Contains("ProfileImage = nil", rendered, StringComparison.Ordinal);
        Assert.Contains("count int32? = nil", rendered, StringComparison.Ordinal);
        Assert.Contains("-> count", rendered, StringComparison.Ordinal);
        Assert.DoesNotContain("count!!", rendered, StringComparison.Ordinal);
    }
}
