// <copyright file="Issue3851MaybeNullWriteEvidenceTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Cs2Gs.CodeModel.Ast;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Cs2Gs.Tests;

/// <summary>
/// Issue #3851 — the runtime half of #3676. A declaration in an
/// <c>&lt;auto-generated/&gt;</c> file is OBLIVIOUS to the C# compiler, so a
/// hand-authored, nullable-ENABLED file may write a maybe-null value into it
/// with no CS8601 (verified empirically: adding the header to the declaring
/// file makes the warning at the WRITE site disappear). #3676 promoted such a
/// declaration only when some source spelled a literal <c>null</c>/<c>default</c>
/// into it, so the far commoner maybe-null shapes — a <c>T?</c> local, a
/// <c>?.</c>/<c>??</c> chain — still translated as non-null G# with a use-site
/// <c>!!</c>, which then THREW on the null the C# quietly accepted. That is how
/// migrated <c>LanguageServer.Tests</c> lost tests to
/// <see cref="System.NullReferenceException"/> at
/// <c>LspServer.InitializeAsync</c> and
/// <c>SelectionRangeComputer.ComputeSelectionRange</c> while the app compiled
/// and IL-verified clean.
/// </summary>
public class Issue3851MaybeNullWriteEvidenceTests
{
    // The `Protocol/Models.cs` shape: a generated model whose `Parent` really is
    // the null terminator of a chain. `Range` is the control — same file, same
    // shape, only ever written a non-null value.
    private const string GeneratedModelSource = @"// <auto-generated/>
namespace Demo
{
    public sealed class SelectionRange
    {
        public string Range { get; set; }

        public SelectionRange Parent { get; set; }
    }
}";

    /// <summary>
    /// SelectionRangeComputer.gs:23 (`Parent: current!!` → NRE). A generated
    /// file's non-null property that a hand-authored file writes a `T?` local
    /// into renders `T?`, and the write needs no `!!`.
    /// </summary>
    [Fact]
    public void GeneratedFileProperty_AssignedMaybeNullLocal_PromotesDeclaration()
    {
        string[] printed = TranslateEnabled(
            ("Models.cs", GeneratedModelSource),
            ("Computer.cs", @"
namespace Demo
{
    public static class Computer
    {
        public static SelectionRange Build(string[] ranges)
        {
            SelectionRange current = null;
            for (var i = ranges.Length - 1; i >= 0; i--)
            {
                current = new SelectionRange { Range = ranges[i], Parent = current };
            }

            return current;
        }
    }
}"));

        Assert.Contains("Parent SelectionRange?", printed[0]);
        Assert.Contains("Range string", printed[0]);
        Assert.DoesNotContain("Range string?", printed[0]);
        Assert.Contains("Parent: current", printed[1]);
        Assert.DoesNotContain("Parent: current!!", printed[1]);
    }

    /// <summary>
    /// LspServer.gs:81 (`(request?.RootPath ?? request?.RootUri?.Path())!!` →
    /// NRE when the client sends neither). A generated file's non-null FIELD
    /// assigned a `?.`/`??` chain renders `string?`, and the assignment needs
    /// no `!!`.
    /// </summary>
    [Fact]
    public void GeneratedFileField_AssignedNullConditionalChain_PromotesDeclaration()
    {
        string[] printed = TranslateEnabled(
            ("Server.cs", @"// <auto-generated/>
namespace Demo
{
    public sealed class Params
    {
        public string RootPath { get; set; }

        public Uri RootUri { get; set; }
    }

    public sealed class Uri
    {
        public string Path() => ""p"";
    }

    public sealed class Server
    {
        private string pendingRootPath;

        public string Initialize(Params request)
        {
            this.pendingRootPath = request?.RootPath ?? request?.RootUri?.Path();
            return this.pendingRootPath;
        }
    }
}"));

        Assert.Contains("pendingRootPath string?", printed[0]);
        Assert.DoesNotContain("!!", printed[0]);
    }

    /// <summary>
    /// Anti-over-promotion guard rail: #3676 deliberately refused the transitive
    /// taint fixpoint here because it over-promoted an enabled compilation's
    /// mostly-annotated graph. Flow state is per-write, so a generated
    /// declaration every write proves non-null keeps its non-null G# type.
    /// </summary>
    [Fact]
    public void GeneratedFileDeclaration_AssignedOnlyNonNullValues_StaysNonNull()
    {
        string[] printed = TranslateEnabled(
            ("Options.cs", @"// <auto-generated/>
namespace Demo
{
    public sealed class Options
    {
        public string Name { get; set; }
    }

    public static class OptionsFactory
    {
        public static Options Create() => new Options { Name = ""gsharp"" };
    }
}"),
            ("Consumer.cs", @"
namespace Demo
{
    public static class Consumer
    {
        public static Options Configure(string name)
        {
            var options = OptionsFactory.Create();
            options.Name = name ?? ""fallback"";
            return options;
        }
    }
}"));

        Assert.Contains("Name string", printed[0]);
        Assert.DoesNotContain("Name string?", printed[0]);
    }

    private static string[] TranslateEnabled(params (string Path, string Source)[] sources)
    {
        SyntaxTree[] trees = sources
            .Select(source => CSharpSyntaxTree.ParseText(
                source.Source,
                new CSharpParseOptions(LanguageVersion.Latest),
                path: source.Path))
            .ToArray();

        CSharpCompilation compilation = CSharpCompilation.Create(
            "Snippet",
            trees,
            CSharpProjectLoader.RuntimeReferences().ToImmutableArray(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                .WithNullableContextOptions(NullableContextOptions.Enable));

        Assert.DoesNotContain(
            compilation.GetDiagnostics(),
            diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);

        var printed = new List<string>();
        foreach (SyntaxTree tree in trees)
        {
            var document = new LoadedDocument(tree.FilePath, tree, compilation.GetSemanticModel(tree));
            var context = new TranslationContext(
                compilation,
                document.SemanticModel,
                document.FilePath,
                new[] { compilation });
            CompilationUnit unit = new CSharpToGSharpTranslator().TranslateDocument(document, context);
            printed.Add(GSharpPrinter.Print(unit));
        }

        return printed.ToArray();
    }
}
