// <copyright file="Issue3848GeneratedArrayElementPromotionTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using Cs2Gs.CodeModel.Ast;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.Pipeline;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Xunit;

namespace Cs2Gs.Tests;

/// <summary>
/// Issue #3848, family B — ELEMENT-level promotion of a generated array
/// declaration.
///
/// <para><b>The defect.</b> <c>Protocol/Models.cs</c> is
/// <c>&lt;auto-generated/&gt;</c> and declares <c>public object[] Arguments
/// { get; set; }</c>. Hand-authored, nullable-ENABLED
/// <c>CodeLensComputer.CreateReferenceLens</c> writes <c>Arguments = [uri,
/// range.Start]</c> with <c>uri</c> a <c>string?</c>. The C# compiler suppresses
/// its nullable diagnostics in generated code, so the CS8601 it would otherwise
/// raise for storing a maybe-null value into a non-null element slot never
/// appears and the write is accepted silently. cs2gs translated the annotation
/// at face value — <c>[]object</c> — and the use-site forgiveness pass bridged
/// the gap with <c>[]object{uri!!, …}</c>. G#'s <c>!!</c> is a RUNTIME
/// assertion, so the migrated LSP threw a <see cref="NullReferenceException"/>
/// on the null the C# stored quite happily.</para>
///
/// <para><b>This is #3676/#3851's rule at element granularity, NOT #3930's
/// forwarding rule.</b> Nothing forwards here: <c>uri</c> is an ordinary,
/// compiler-CHECKED <c>string?</c> parameter, which
/// <c>IsPromotedByPureForwarding</c> rejects outright (clause 6 admits only a
/// direct call or field/property read of an already-promoted symbol). Nor would
/// #3930's declaration-level promotion produce the right answer if it did fire:
/// it widens the DECLARATION, i.e. <c>object[]</c> → <c>[]?object</c>, the
/// nullable ARRAY. It is a value in the array that is null, not the array, so
/// the promotion this evidence licenses is <c>[]object?</c> — the
/// element-nullable spelling (issue #1212 / ADR-0132). The single fact both
/// rules do share is the safety boundary: the sink is generated, so the
/// compiler stopped checking it, so the write is better evidence than the
/// annotation.</para>
///
/// <para><b>The boundary.</b> A hand-authored <c>object[]</c> sink promotes
/// nothing and its element keeps its <c>!!</c>, because there the compiler
/// really did raise CS8601 and the author really did have to answer for it.
/// <see cref="HandAuthoredArraySink_KeepsItsElementAssertion"/> and its
/// executing twin
/// <see cref="TranslatedHandAuthoredArraySink_StillThrowsOnTheNullElement"/>
/// hold that down; without them "promote every array element" passes this
/// file.</para>
/// </summary>
public sealed class Issue3848GeneratedArrayElementPromotionTests
{
    // The `Protocol/Models.cs` shape: a generated protocol model with an
    // `object[]` slot whose annotation the C# compiler never checked, plus a
    // second array slot written only non-null values and a value-typed array,
    // so "promoted" can be told apart from "promoted everything".
    private const string GeneratedModelSource = """
        // <auto-generated/>
        namespace Repro
        {
            public sealed class Command
            {
                public string Title { get; set; }

                public object[] Arguments { get; set; }

                public string[] Tags { get; set; }

                public int[] Offsets { get; set; }
            }
        }
        """;

    // The `CodeLensComputer.CreateReferenceLens` shape, hand-authored and
    // nullable-ENABLED: a `string?` written as an ELEMENT of the generated
    // `object[]`.
    private const string LensSource = """
        namespace Repro
        {
            public static class Lens
            {
                public static Command Create(string? uri, int line) => new Command
                {
                    Title = "t",
                    Arguments = [uri, line],
                    Tags = ["a", "b"],
                    Offsets = [1, 2],
                };
            }
        }
        """;

    /// <summary>
    /// THE EXECUTING PROOF, and the shape family B actually is. gsc compiles the
    /// translated G# and a C# driver calls <c>Lens.Create(null, 1)</c>. The C#
    /// stores the null in <c>Arguments[0]</c> and returns; before this change the
    /// migrated G# threw <see cref="NullReferenceException"/> out of the
    /// <c>uri!!</c> inside the slice literal. No printed-shape assertion can
    /// tell those two apart once someone "fixes" it by deleting the wrong
    /// <c>!!</c>, so the assertion is on what the driver gets back.
    /// </summary>
    [Fact]
    public void TranslatedGeneratedArrayElement_HoldsTheNullInsteadOfThrowing()
    {
        Assert.Equal(
            DriverNullResult,
            RunDriver(
                nameof(TranslatedGeneratedArrayElement_HoldsTheNullInsteadOfThrowing),
                """
                namespace Repro
                {
                    public static class Driver
                    {
                        public static int Run()
                        {
                            try
                            {
                                var command = Lens.Create(null, 1);
                                return command.Arguments[0] == null ? 1 : 2;
                            }
                            catch (System.NullReferenceException)
                            {
                                return 3;
                            }
                        }
                    }
                }
                """,
                ("Models.cs", GeneratedModelSource),
                ("Lens.cs", LensSource)));
    }

    /// <summary>
    /// The same repro read as shapes, and the ADR-0132 axis decision. The
    /// generated slot renders <c>[]object?</c> — an array of nullable elements —
    /// and specifically NOT <c>[]?object</c>, the nullable array (issue #1212
    /// spells the two apart). cs2gs is right about that distinction and this
    /// change must not blur it: the array reference is not null here, one of the
    /// values in it is.
    ///
    /// <para>The literal at the write site widens with the slot and the element
    /// loses its <c>!!</c> — that <c>!!</c> is the throw this issue is about.
    /// </para>
    /// </summary>
    [Fact]
    public void GeneratedArrayElement_IsPromotedAtTheElement_NotAtTheArray()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Lens.cs", LensSource));

        Assert.Contains("Arguments []object?", printed["Models.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("Arguments []?object", printed["Models.cs"], StringComparison.Ordinal);

        Assert.Contains("Arguments: []object?{uri, line}", printed["Lens.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("!!", printed["Lens.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// ANTI-VACUITY, the "not everything" direction. Two other generated array
    /// slots in the very same generated class are written from the very same
    /// hand-authored method and are NOT promoted: <c>Tags</c> is a
    /// <c>string[]</c> written only non-null elements, and <c>Offsets</c> is an
    /// <c>int[]</c> whose value-typed elements can never receive a null at all.
    /// The evidence is the maybe-null WRITE, not "the declaration is generated"
    /// and not "the declaration is an array".
    /// </summary>
    [Fact]
    public void GeneratedArraysWithoutMaybeNullElements_AreNotPromoted()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Lens.cs", LensSource));

        Assert.Contains("Tags []string\n", printed["Models.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("Tags []string?", printed["Models.cs"], StringComparison.Ordinal);

        Assert.Contains("Offsets []int32\n", printed["Models.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("Offsets []int32?", printed["Models.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// ANTI-VACUITY IN THE DANGEROUS DIRECTION. An identical <c>object[]</c>
    /// slot in a HAND-AUTHORED, nullable-enabled file is a write the C# compiler
    /// really did check (CS8601), so its annotation stands, the element stays
    /// non-null, and the genuinely-null element must STILL be asserted. Delete
    /// the generated restriction — i.e. promote any array element written a
    /// maybe-null value — and this test fails.
    /// </summary>
    [Fact]
    public void HandAuthoredArraySink_KeepsItsElementAssertion()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Handwritten.cs", HandAuthoredModelSource),
            ("HandLens.cs", HandAuthoredLensSource));

        Assert.Contains("Payload []object\n", printed["Handwritten.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("Payload []object?", printed["Handwritten.cs"], StringComparison.Ordinal);

        Assert.Contains("uri!!", printed["HandLens.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// The executing half of that guard: the retained <c>!!</c> is a real
    /// runtime assertion and not decoration. A null genuinely arrives at the
    /// hand-authored element slot and the migrated G# genuinely throws — which
    /// is what "the element still gets its assertion" has to mean, and is the
    /// #3787/#3771 failure mode this rule must not reintroduce.
    /// </summary>
    [Fact]
    public void TranslatedHandAuthoredArraySink_StillThrowsOnTheNullElement()
    {
        Assert.Equal(
            DriverThrewResult,
            RunDriver(
                nameof(TranslatedHandAuthoredArraySink_StillThrowsOnTheNullElement),
                """
                namespace Repro
                {
                    public static class Driver
                    {
                        public static int Run()
                        {
                            try
                            {
                                var box = HandLens.Create(null);
                                return box.Payload[0] == null ? 1 : 2;
                            }
                            catch (System.NullReferenceException)
                            {
                                return 3;
                            }
                        }
                    }
                }
                """,
                ("Handwritten.cs", HandAuthoredModelSource),
                ("HandLens.cs", HandAuthoredLensSource)));
    }

    /// <summary>
    /// SYMMETRY, and the reason the write-site half is gated on the DECLARATION
    /// rather than on this literal's own elements. Once <c>Arguments</c> is
    /// <c>[]object?</c>, a SECOND write whose elements are all non-null must
    /// widen with it: a <c>[]object</c> literal does not convert to a
    /// <c>[]object?</c> slot (gsc GS0155), so leaving that literal narrow would
    /// promote the declaration and stop the project compiling — the same class
    /// of break #3930's conversion-operator regression was.
    /// </summary>
    [Fact]
    public void SecondWriteWithoutANullElement_WidensWithThePromotedSlot()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Lens.cs", LensSource),
            ("Other.cs", """
                namespace Repro
                {
                    public static class Other
                    {
                        public static Command Plain() => new Command
                        {
                            Title = "t",
                            Arguments = ["a", 1],
                            Tags = ["a"],
                            Offsets = [1],
                        };
                    }
                }
                """));

        Assert.Contains("Arguments: []object?{\"a\", 1}", printed["Other.cs"], StringComparison.Ordinal);

        // ... and only the slot the evidence names. `Tags` has no maybe-null
        // write anywhere in the run, so its literal stays narrow.
        Assert.Contains("Tags: []string{\"a\"}", printed["Other.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// The classic array-creation spelling reaches the same answer as the C# 12
    /// collection expression. The evidence is the maybe-null element written
    /// into the generated slot, not the syntax the literal happens to use, and
    /// both spellings translate to the same G# slice literal.
    /// </summary>
    [Fact]
    public void ExplicitArrayCreationWrite_PromotesTheSameSlot()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Classic.cs", """
                namespace Repro
                {
                    public static class Classic
                    {
                        public static Command Create(string? uri) => new Command
                        {
                            Title = "t",
                            Arguments = new object[] { uri, 1 },
                            Tags = new string[] { "a" },
                            Offsets = new int[] { 1 },
                        };
                    }
                }
                """));

        Assert.Contains("Arguments []object?", printed["Models.cs"], StringComparison.Ordinal);
        Assert.Contains("Arguments: []object?{uri, 1}", printed["Classic.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("!!", printed["Classic.cs"], StringComparison.Ordinal);
    }

    /// <summary>
    /// DECISION: a SPREAD element is no evidence. <c>[..values]</c> hides its
    /// elements behind an enumerable this rule does not walk, so the
    /// conservative answer is "no promotion" and the ordinary forgiveness
    /// behaviour is unchanged there. Recorded because the alternative — treating
    /// the spread's static element type as evidence — is a widening someone
    /// could reach for later, and it would promote on a source's ANNOTATION
    /// rather than on a write the compiler failed to check.
    /// </summary>
    [Fact]
    public void SpreadElement_IsNoEvidence()
    {
        IReadOnlyDictionary<string, string> printed = Translate(
            ("Models.cs", GeneratedModelSource),
            ("Spread.cs", """
                using System.Collections.Generic;

                namespace Repro
                {
                    public static class Spread
                    {
                        public static Command Create(IEnumerable<object> values) => new Command
                        {
                            Title = "t",
                            Arguments = [.. values],
                            Tags = ["a"],
                            Offsets = [1],
                        };
                    }
                }
                """));

        Assert.Contains("Arguments []object\n", printed["Models.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain("Arguments []object?", printed["Models.cs"], StringComparison.Ordinal);
    }

    // The hand-authored mirror of the generated model: byte-for-byte the same
    // declaration and the same write, differing ONLY in the
    // `<auto-generated/>` header. That is the whole safety boundary, so the two
    // sources are kept side by side.
    private const string HandAuthoredModelSource = """
        namespace Repro
        {
            public sealed class Box
            {
                public object[] Payload { get; set; }
            }
        }
        """;

    private const string HandAuthoredLensSource = """
        namespace Repro
        {
            public static class HandLens
            {
                public static Box Create(string? uri) => new Box
                {
                    Payload = [uri, 1],
                };
            }
        }
        """;

    private const int DriverNullResult = 1;

    private const int DriverThrewResult = 3;

    private static IReadOnlyDictionary<string, string> Translate(
        params (string Path, string Source)[] sources)
    {
        SyntaxTree[] trees = sources
            .Select(source => CSharpSyntaxTree.ParseText(
                source.Source,
                new CSharpParseOptions(LanguageVersion.Latest),
                path: source.Path))
            .ToArray();

        CSharpCompilation compilation = CSharpCompilation.Create(
            "Repro",
            trees,
            CSharpProjectLoader.RuntimeReferences().ToImmutableArray(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
                .WithNullableContextOptions(NullableContextOptions.Enable));

        Assert.DoesNotContain(
            compilation.GetDiagnostics(),
            diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);

        var printed = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (SyntaxTree tree in trees)
        {
            var document = new LoadedDocument(tree.FilePath, tree, compilation.GetSemanticModel(tree));
            var context = new TranslationContext(
                compilation,
                document.SemanticModel,
                document.FilePath,
                new[] { compilation });
            CompilationUnit unit = new CSharpToGSharpTranslator().TranslateDocument(document, context);
            Assert.DoesNotContain(
                context.Diagnostics,
                diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
            printed[tree.FilePath] = GSharpPrinter.Print(unit);
        }

        return printed;
    }

    // Translates `sources`, compiles the result with gsc, compiles `driverSource`
    // as C# against the emitted assembly, and returns what `Repro.Driver.Run()`
    // answered. Only this can tell a removed `!!` from a retained one at run
    // time, which is the entire subject of this file.
    private static int RunDriver(
        string name,
        string driverSource,
        params (string Path, string Source)[] sources)
    {
        string compiler = FindCompiler();
        Assert.True(compiler != null, "gsc.dll must be built for the runtime tests in this file.");

        IReadOnlyDictionary<string, string> printed = Translate(sources);
        string workDir = NewDirectory(name);
        var gsPaths = new List<string>();
        foreach ((string path, string _) in sources)
        {
            string gsPath = Path.Combine(workDir, Path.ChangeExtension(path, ".gs"));
            File.WriteAllText(gsPath, printed[path] + Environment.NewLine);
            gsPaths.Add(gsPath);
        }

        string libraryPath = Path.Combine(workDir, "Repro.dll");
        var arguments = new List<string> { compiler, "/target:library", "/out:" + libraryPath };
        arguments.AddRange(gsPaths);

        ProcessRunResult compile = ProcessRunner.Run("dotnet", arguments, workDir);
        Assert.True(
            compile.ExitCode == 0,
            "gsc must compile the translated model. Output:\n" + compile.Output +
                "\nTranslated G#:\n" + string.Join("\n----\n", printed.Values));

        var loadContext = new AssemblyLoadContext(name, isCollectible: true);
        try
        {
            Assembly library = loadContext.LoadFromAssemblyPath(libraryPath);
            var references = new List<MetadataReference>(CSharpProjectLoader.RuntimeReferences())
            {
                MetadataReference.CreateFromFile(libraryPath),
            };

            CSharpCompilation driverCompilation = CSharpCompilation.Create(
                "Repro.Driver",
                new[]
                {
                    CSharpSyntaxTree.ParseText(
                        driverSource, new CSharpParseOptions(LanguageVersion.Latest)),
                },
                references,
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            string driverPath = Path.Combine(workDir, "Repro.Driver.dll");
            EmitResult emitted = driverCompilation.Emit(driverPath);
            Assert.True(
                emitted.Success,
                "The C# driver must compile against the gsc-emitted assembly. Diagnostics:\n" +
                    string.Join(Environment.NewLine, emitted.Diagnostics));

            Assembly driver = loadContext.LoadFromAssemblyPath(driverPath);
            object result = driver.GetType("Repro.Driver")!.GetMethod("Run")!.Invoke(null, null);
            _ = library;
            return Assert.IsType<int>(result);
        }
        finally
        {
            loadContext.Unload();
        }
    }

    private static string NewDirectory(string category)
    {
        string path = Path.Combine(
            AppContext.BaseDirectory,
            "issue-3848-array-element",
            category,
            Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(path);
        return path;
    }

    private static string FindCompiler()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            foreach (string config in new[] { "Release", "Debug" })
            {
                string candidate = Path.Combine(
                    dir.FullName, "out", "bin", config, "Compiler", "gsc.dll");
                if (File.Exists(candidate))
                {
                    return candidate;
                }
            }

            dir = dir.Parent;
        }

        return null;
    }
}
