// <copyright file="Issue4301GeneratedRegexTranslationTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.Linq;
using Cs2Gs.CodeModel.Ast;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Cs2Gs.Tests;

/// <summary>
/// Issue #4301 (ADR-0192 follow-on 3): a C# <c>[GeneratedRegex]</c> partial
/// method translates to a G# declaring part,
/// <c>@GeneratedRegex(...) partial func F() Regex;</c>, whose implementing
/// part gsgen generates at build; the generated C# implementation is dropped,
/// and no <c>__generatedRegex_</c> cache field is minted. Shapes G# cannot
/// pair with a generated implementing part are reported. The real-generator
/// round trip (attribute arguments, escaping, culture, instance methods) is
/// <c>GSharp.GeneratorHost.Tests.GeneratedRegexImplementingPartTests.MigratedGeneratedRegex_*</c>.
/// </summary>
/// <remarks>
/// The fixtures model the generator output as a second
/// <c>// &lt;auto-generated/&gt;</c> document holding the implementation, the
/// shape a real build hands cs2gs: the loader drops that document, and the
/// compilation still sees it.
/// </remarks>
public class Issue4301GeneratedRegexTranslationTests
{
    // gsgen's implementing part for `Digits`, standing in for the build: a
    // lone declaring part is GS0609, so binding needs its partner.
    private const string DigitsImplementingPart = @"package App

import System.Text.RegularExpressions

partial class P {
    shared {
        private partial func Digits() Regex -> Regex(""\\d+"")
    }
}
";

    [Fact]
    public void StaticMethod_TranslatesToASharedDeclaringPart_WithoutACacheField()
    {
        const string source = @"
using System.Text.RegularExpressions;

namespace App;

public partial class P
{
    [GeneratedRegex(@""\d+"")]
    private static partial Regex Digits();

    public static bool Test(string s) => Digits().IsMatch(s);
}";
        const string generated = @"// <auto-generated/>
namespace App;

partial class P
{
    private static partial System.Text.RegularExpressions.Regex Digits() => null!;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("P.cs", source),
            ("P.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.DoesNotContain("__generatedRegex_", printed, StringComparison.Ordinal);
        Assert.Contains(
            "@GeneratedRegex(\"\\\\d+\")" + Environment.NewLine + "        private partial func Digits() Regex;",
            printed,
            StringComparison.Ordinal);
        int shared = printed.IndexOf("shared {", StringComparison.Ordinal);
        Assert.True(shared >= 0 && shared < printed.IndexOf("partial func Digits", StringComparison.Ordinal), printed);
        TranslationTestValidation.AssertBinds(printed, DigitsImplementingPart);
    }

    [Fact]
    public void AliasedAttribute_IsRecognizedByItsResolvedType_AndOtherAttributesStay()
    {
        const string source = @"
using System;
using System.Text.RegularExpressions;
using Rx = System.Text.RegularExpressions.GeneratedRegexAttribute;

namespace App;

public partial class P
{
    private const string Pattern = @""\d+"";

    [Obsolete(""old"")]
    [Rx(Pattern, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant, matchTimeoutMilliseconds: 250)]
    private static partial Regex Digits();
}";
        const string generated = @"// <auto-generated/>
namespace App;

partial class P
{
    private static partial System.Text.RegularExpressions.Regex Digits() => null!;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("P.cs", source),
            ("P.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("@Obsolete(\"old\")", printed, StringComparison.Ordinal);

        // The const pattern is re-spelled as its value, the named timeout is
        // positional (G# binds `name:` arguments as properties), and the
        // flags are spelled as enum members.
        Assert.Contains(
            "(\"\\\\d+\", RegexOptions.CultureInvariant | RegexOptions.IgnoreCase, 250)",
            printed,
            StringComparison.Ordinal);
        Assert.Contains("private partial func Digits() Regex;", printed, StringComparison.Ordinal);
        TranslationTestValidation.AssertBinds(printed, DigitsImplementingPart);
    }

    [Fact]
    public void GeneratedImplementationInATranslatedTree_IsDropped()
    {
        // A committed generator output (a repository migration translates
        // git-tracked `<auto-generated>` files too): gsgen regenerates the
        // implementation, so emitting it would duplicate the implementing part.
        const string source = @"
using System.Text.RegularExpressions;

namespace App;

public partial class P
{
    [GeneratedRegex(@""\d+"")]
    private static partial Regex Digits();
}";
        const string generated = @"// <auto-generated/>
namespace App;

partial class P
{
    private static partial System.Text.RegularExpressions.Regex Digits() => new(""x"");
}";
        LoadedCSharpProject project = CSharpProjectLoader.LoadInMemory(new[] { ("P.cs", source), ("P.g.cs", generated) });
        Assert.True(project.BoundWithoutErrors, string.Join(Environment.NewLine, project.ErrorDiagnostics));
        SyntaxTree generatedTree = project.Compilation.SyntaxTrees.Single(tree => tree.FilePath == "P.g.cs");
        var translator = new CSharpToGSharpTranslator(translatedFilePaths: new[] { "P.cs", "P.g.cs" });
        var model = project.Compilation.GetSemanticModel(generatedTree);
        var context = new TranslationContext(project.Compilation, model, generatedTree.FilePath);
        string printed = GSharpPrinter.Print(
            translator.TranslateDocument(new LoadedDocument(generatedTree.FilePath, generatedTree, model), context));

        Assert.DoesNotContain("func Digits", printed, StringComparison.Ordinal);
    }

    [Fact]
    public void RecordOwner_IsReportedUnsupported()
    {
        const string source = @"
using System.Text.RegularExpressions;

public sealed partial record Url(string Text)
{
    [GeneratedRegex(""^https://"")]
    private static partial Regex Scheme();

    public bool IsHttps() => Scheme().IsMatch(Text);
}";
        const string generated = @"// <auto-generated/>
partial record Url
{
    private static partial System.Text.RegularExpressions.Regex Scheme() => null!;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Url.cs", source),
            ("Url.g.cs", generated));

        TranslationDiagnostic unsupported = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("[GeneratedRegex] method 'Url.Scheme'", unsupported.Message, StringComparison.Ordinal);
        Assert.Contains("data class (a C# record)", unsupported.Message, StringComparison.Ordinal);
        Assert.DoesNotContain("__generatedRegex_", printed, StringComparison.Ordinal);
        Assert.DoesNotContain("func Scheme", printed, StringComparison.Ordinal);
    }

    [Fact]
    public void NestedOwner_IsReportedUnsupported()
    {
        const string source = @"
using System.Text.RegularExpressions;

public partial class Outer
{
    public partial class Inner
    {
        [GeneratedRegex(""\\d+"")]
        private static partial Regex Digits();

        public static bool Test(string s) => Digits().IsMatch(s);
    }
}";
        const string generated = @"// <auto-generated/>
partial class Outer
{
    partial class Inner
    {
        private static partial System.Text.RegularExpressions.Regex Digits() => null!;
    }
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            ("Outer.cs", source),
            ("Outer.g.cs", generated));

        TranslationDiagnostic unsupported = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("[GeneratedRegex] method 'Inner.Digits'", unsupported.Message, StringComparison.Ordinal);
        Assert.Contains("its type is nested", unsupported.Message, StringComparison.Ordinal);
        Assert.DoesNotContain("__generatedRegex_", printed, StringComparison.Ordinal);
        Assert.DoesNotContain("func Digits", printed, StringComparison.Ordinal);
    }

    [Fact]
    public void LegacyMergeMode_IsReportedUnsupported()
    {
        const string source = @"
using System.Text.RegularExpressions;

public partial class P
{
    [GeneratedRegex(""\\d+"")]
    private static partial Regex Digits();
}";
        const string generated = @"// <auto-generated/>
partial class P
{
    private static partial System.Text.RegularExpressions.Regex Digits() => null!;
}";

        (_, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            new CSharpToGSharpTranslator(preservePartialParts: false),
            OutputKind.DynamicallyLinkedLibrary,
            ("P.cs", source),
            ("P.g.cs", generated));

        TranslationDiagnostic unsupported = Assert.Single(
            diagnostics,
            diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("GS0608", unsupported.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void EntryClassWithMain_IsKeptAsAClass_SoTheDeclaringPartHasAnOwner()
    {
        // A private-only entry class is otherwise hoisted to top-level funcs,
        // which cannot be partial.
        const string source = @"
using System;
using System.Text.RegularExpressions;

namespace App;

internal static partial class P
{
    private static void Main()
    {
        Console.WriteLine(Digits().IsMatch(""42""));
    }

    [GeneratedRegex(@""\d+"")]
    private static partial Regex Digits();
}";
        const string generated = @"// <auto-generated/>
namespace App;

partial class P
{
    private static partial System.Text.RegularExpressions.Regex Digits() => null!;
}";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            new CSharpToGSharpTranslator(),
            OutputKind.ConsoleApplication,
            ("P.cs", source),
            ("P.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("partial class P {", printed, StringComparison.Ordinal);
        Assert.Contains("private partial func Digits() Regex;", printed, StringComparison.Ordinal);
        TranslationTestValidation.AssertBinds(printed, DigitsImplementingPart);
    }

    [Fact]
    public void TopLevelStatementsProgram_KeepsItsPartialProgramClass_AndWidensItsPrivateMembers()
    {
        // C# top-level statements are the body of Program's entry point, so
        // they reach its private members. G# top-level statements are not in
        // the kept `Program` class, so its private members become internal
        // (GS0472 otherwise); the hoisted form was no stricter.
        const string source = @"
using System;
using System.Text.RegularExpressions;

Console.WriteLine(Digits().IsMatch(""42""));
Console.WriteLine(Describe(""x""));

internal static partial class Program
{
    [GeneratedRegex(@""\d+"")]
    private static partial Regex Digits();

    private static string Describe(string s) => Digits().IsMatch(s) ? ""digits"" : ""none"";
}";
        const string generated = @"// <auto-generated/>
partial class Program
{
    private static partial System.Text.RegularExpressions.Regex Digits() => null!;
}";
        const string implementingPart = @"import System.Text.RegularExpressions

partial class Program {
    shared {
        internal partial func Digits() Regex -> Regex(""\\d+"")
    }
}
";

        (string printed, IReadOnlyList<TranslationDiagnostic> diagnostics) = Translate(
            new CSharpToGSharpTranslator(),
            OutputKind.ConsoleApplication,
            ("Program.cs", source),
            ("Program.g.cs", generated));

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Severity == TranslationSeverity.Unsupported);
        Assert.Contains("partial class Program {", printed, StringComparison.Ordinal);
        Assert.Contains("internal partial func Digits() Regex;", printed, StringComparison.Ordinal);
        Assert.Contains("internal func Describe(s string) string", printed, StringComparison.Ordinal);
        TranslationTestValidation.AssertBinds(printed, implementingPart);
    }

    private static (string Printed, IReadOnlyList<TranslationDiagnostic> Diagnostics) Translate(
        params (string FileName, string Source)[] files) =>
        Translate(new CSharpToGSharpTranslator(), OutputKind.DynamicallyLinkedLibrary, files);

    private static (string Printed, IReadOnlyList<TranslationDiagnostic> Diagnostics) Translate(
        CSharpToGSharpTranslator translator,
        OutputKind outputKind,
        params (string FileName, string Source)[] files)
    {
        LoadedCSharpProject project = CSharpProjectLoader.LoadInMemory(files, outputKind: outputKind);
        Assert.True(
            project.BoundWithoutErrors,
            "Snippet should bind with no C# errors: " +
                string.Join(Environment.NewLine, project.ErrorDiagnostics));

        LoadedDocument document = Assert.Single(project.Documents);
        var context = new TranslationContext(project.Compilation, document.SemanticModel, document.FilePath);
        CompilationUnit unit = translator.TranslateDocument(document, context);
        return (GSharpPrinter.Print(unit), context.Diagnostics);
    }
}
