// <copyright file="TranslateStageResxTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Cs2Gs.Pipeline;
using Xunit;

namespace Cs2Gs.Tests;

/// <summary>
/// Stage-level tests for issue #2200: <see cref="TranslateStage"/> must generate a
/// <c>Resources.Designer.gs</c> codebehind for each <c>.resx</c> file discovered in
/// the loaded C# project (via <see cref="GSharp.Core.Resx.ResxCodeGenerator"/>)
/// instead of relying solely on skipping a hand-authored
/// <c>Resources.Designer.cs</c> as generated source. Without this, a
/// <c>using R = ...Resources;</c> alias in migrated source cannot resolve
/// (GS0157), cascading into GS0159 errors.
/// </summary>
public class TranslateStageResxTests
{
    private const string SampleResx = """
        <?xml version="1.0" encoding="utf-8"?>
        <root>
          <data name="Greeting" xml:space="preserve">
            <value>Hello, world!</value>
          </data>
        </root>
        """;

    [Fact]
    public async Task TranslateStage_DiscoversResxAndEmitsDesignerCodebehind()
    {
        string compiler = FindCompiler();
        if (compiler is null)
        {
            return;
        }

        string projectDir = NewScratchDir("translate-resx");
        const string DirectoryBuildProps = "<Project><PropertyGroup><SampleProperty>true</SampleProperty></PropertyGroup></Project>";
        File.WriteAllText(Path.Combine(projectDir, "Directory.Build.props"), DirectoryBuildProps);
        string projectPath = Path.Combine(projectDir, "Sample.csproj");
        File.WriteAllText(projectPath, """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <OutputType>Exe</OutputType>
                <RootNamespace>Sample.App</RootNamespace>
              </PropertyGroup>
            </Project>
            """);

        var propertiesDir = Path.Combine(projectDir, "Properties");
        Directory.CreateDirectory(propertiesDir);
        File.WriteAllText(Path.Combine(propertiesDir, "Resources.resx"), SampleResx);
        File.WriteAllText(Path.Combine(propertiesDir, "Resources.Designer.gs"), """
            // <auto-generated>
            //     stale designer from a prior design-time generation pass.
            // </auto-generated>
            package Wrong.Namespace
            internal class Resources { }
            """);

        // A hand-authored Designer.cs carrying the standard auto-generated header
        // must still be skipped from translation (pre-existing behavior); the resx
        // discovery path is what now fills the gap it leaves.
        File.WriteAllText(Path.Combine(propertiesDir, "Resources.Designer.cs"), """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            // </auto-generated>
            //------------------------------------------------------------------------------
            namespace Sample.App.Properties
            {
                internal class Resources
                {
                    internal static string Greeting => "Hello, world!";
                }
            }
            """);

        File.WriteAllText(
            Path.Combine(projectDir, "Program.cs"),
            "public class Program { public static void Main() { } }");
        string viewsDir = Path.Combine(projectDir, "Views");
        Directory.CreateDirectory(viewsDir);
        File.WriteAllText(
            Path.Combine(viewsDir, "MainView.cs"),
            "namespace Sample.App.Views; public class MainView { }");
        File.WriteAllText(Path.Combine(viewsDir, "MainView.axaml"), "<UserControl />");
        string assetsDir = Path.Combine(projectDir, "Assets");
        Directory.CreateDirectory(assetsDir);
        File.WriteAllBytes(Path.Combine(assetsDir, "logo.bin"), new byte[] { 1, 2, 3 });
        Directory.CreateDirectory(Path.Combine(projectDir, "bin"));
        File.WriteAllText(Path.Combine(projectDir, "bin", "ignored.txt"), "ignore");
        Directory.CreateDirectory(Path.Combine(projectDir, "obj"));
        File.WriteAllText(Path.Combine(projectDir, "obj", "ignored.txt"), "ignore");

        string outRoot = NewOutputRoot("translate-resx");
        var options = new PipelineOptions { GscPath = compiler, OutputRoot = outRoot };
        var pipeline = new MigrationPipeline(options, new IMigrationStage[] { new TranslateStage() });

        var app = new CorpusApp("test/ResxApp", projectPath, TargetKind.Exe);

        RunResult result = await pipeline.RunAsync(new[] { app });
        AppResult appResult = Assert.Single(result.Apps);

        Assert.True(appResult.Succeeded, "Translate stage must succeed for a project with a valid resx.");

        string[] designerFiles = Directory.GetFiles(outRoot, "Resources.Designer.gs", SearchOption.AllDirectories);
        string designerFile = Assert.Single(designerFiles);

        string generated = File.ReadAllText(designerFile);
        Assert.Contains("Sample.App.Properties", generated);
        Assert.Contains("Greeting", generated);
        Assert.DoesNotContain("Wrong.Namespace", generated);

        string appOutputDir = Directory.GetParent(Path.GetDirectoryName(designerFile)).FullName;
        Assert.True(File.Exists(Path.Combine(appOutputDir, "Program.gs")));
        Assert.True(File.Exists(Path.Combine(appOutputDir, "Views", "MainView.gs")));
        Assert.Equal(
            "<UserControl />",
            File.ReadAllText(Path.Combine(appOutputDir, "Views", "MainView.axaml")));
        Assert.Equal(
            new byte[] { 1, 2, 3 },
            File.ReadAllBytes(Path.Combine(appOutputDir, "Assets", "logo.bin")));
        Assert.True(File.Exists(Path.Combine(appOutputDir, "Properties", "Resources.resx")));
        Assert.Equal(
            DirectoryBuildProps,
            File.ReadAllText(Path.Combine(appOutputDir, "Directory.Build.props")));
        Assert.False(File.Exists(Path.Combine(appOutputDir, "Sample.csproj")));
        Assert.False(Directory.Exists(Path.Combine(appOutputDir, "bin")));
        Assert.False(Directory.Exists(Path.Combine(appOutputDir, "obj")));

        // The hand-authored Resources.Designer.cs must not itself have been
        // translated into a second competing .gs file.
        string[] allGsFiles = Directory.GetFiles(outRoot, "*.gs", SearchOption.AllDirectories);
        Assert.DoesNotContain(allGsFiles, f => f.Contains("Designer.cs", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(allGsFiles, f => f.EndsWith("Resources.Designer.2.gs", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public async Task TranslateStage_MalformedResx_DoesNotCrashStage()
    {
        string compiler = FindCompiler();
        if (compiler is null)
        {
            return;
        }

        string projectDir = NewScratchDir("translate-resx-malformed");
        File.WriteAllText(Path.Combine(projectDir, "Directory.Build.props"), "<Project></Project>");
        string projectPath = Path.Combine(projectDir, "Sample.csproj");
        File.WriteAllText(projectPath, """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <OutputType>Exe</OutputType>
                <RootNamespace>Sample.App</RootNamespace>
              </PropertyGroup>
            </Project>
            """);

        File.WriteAllText(Path.Combine(projectDir, "Broken.resx"), "<root><data name=\"X\"><value>unterminated");
        File.WriteAllText(
            Path.Combine(projectDir, "Program.cs"),
            "public class Program { public static void Main() { } }");

        string outRoot = NewOutputRoot("translate-resx-malformed");
        var options = new PipelineOptions { GscPath = compiler, OutputRoot = outRoot };
        var pipeline = new MigrationPipeline(options, new IMigrationStage[] { new TranslateStage() });

        var app = new CorpusApp("test/BrokenResx", projectPath, TargetKind.Exe);

        // Must complete (fail gracefully with a triage artifact), never throw.
        RunResult result = await pipeline.RunAsync(new[] { app });
        AppResult appResult = Assert.Single(result.Apps);

        Assert.False(appResult.Succeeded);

        string[] triageFiles = Directory.GetFiles(outRoot, "*.json", SearchOption.AllDirectories)
            .Where(f => !Path.GetFileName(f).Equals("summary.json", StringComparison.OrdinalIgnoreCase))
            .ToArray();
        string match = triageFiles.FirstOrDefault(f => File.ReadAllText(f).Contains("CS2GS0003"));
        Assert.NotNull(match);
    }

    private static string NewOutputRoot(string label)
    {
        string root = Path.Combine(AppContext.BaseDirectory, "pipeline-tests", label, Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        return root;
    }

    private static string NewScratchDir(string label)
    {
        string root = Path.Combine(AppContext.BaseDirectory, "loader-tests", label, Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        return root;
    }

    private static string FindCompiler()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            foreach (string config in new[] { "Release", "Debug" })
            {
                string candidate = Path.Combine(dir.FullName, "out", "bin", config, "Compiler", "gsc.dll");
                if (File.Exists(candidate))
                {
                    return candidate;
                }
            }

            dir = dir.Parent;
        }

        return null;
    }
}
