<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppTargetFramework)</TargetFramework>
    <RootNamespace>GSharp.Formatting</RootNamespace>
    <AssemblyName>GSharp.Formatting</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.csproj" />
  </ItemGroup>

</Project>
