# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  sln: './GSharp.sln'
  lspServerProject: './src/LSP/LSP.csproj'
  lspClientDirectory: './src/LSP-client'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.202'
  inputs:
    version: 2.2.202
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(sln)
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: $(sln)
    arguments: '--configuration $(buildConfiguration)'
- task: NodeTool@0
  displayName: 'Use Node version 10.14.1'
  inputs:
    versionSpec: 10.14.1
- task: DotNetCoreCLI@2
  displayName: 'Publish LSP Server'
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(lspServerProject)
    arguments: '-c Release'
    zipAfterPublish: false
    modifyOutputPath: false
- task: Npm@1
  displayName: 'Install Extension Dependencies'
  inputs:
    workingDir: $(lspClientDirectory)
    verbose: false
- task: CopyFiles@2
  displayName: 'Copy GSharp LSP Client files to output directory'
  inputs:
    SourceFolder: src/LSP-client
    TargetFolder: 'out/bin/Release/LSP-Client'
- task: CopyFiles@2
  displayName: 'Copy GSharp LSP Server files to LSP Client output directory'
  inputs:
    SourceFolder: out/bin/Release/LSP/publish
    TargetFolder: 'out/bin/Release/LSP-Client/out'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: out/bin/Release
