# Build and publish GSharp VSCode extension

pool:
  vmImage: 'Hosted'

variables:
  buildConfiguration: 'Release'
  sln: './GSharp.sln'
  lspServerProject: './src/LSP/LSP.csproj'
  lspClientDirectory: './src/LSP-client'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.202'
  inputs:
    version: 2.2.202
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(sln)
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: $(sln)
    arguments: '--configuration $(buildConfiguration)'
- task: NodeTool@0
  displayName: 'Use Node version 10.14.1'
  inputs:
    versionSpec: 10.14.1
- task: DotNetCoreCLI@2
  displayName: 'Publish LSP Server'
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(lspServerProject)
    arguments: '-c Release'
    zipAfterPublish: false
    modifyOutputPath: false
- task: Npm@1
  displayName: 'Install Extension Dependencies'
  inputs:
    workingDir: $(lspClientDirectory)
    verbose: false
- task: CopyFiles@2
  displayName: 'Copy GSharp LSP Server files to LSP Client directory'
  inputs:
    SourceFolder: out/bin/Release/LSP/publish
    TargetFolder: 'src/LSP-client/out'
#- script: 'npm install -g vsce'
#  displayName: 'Install VSCode Extensions Publisher'
#- script: 'vsce publish -p %VSCEPAT%'
#  workingDirectory: 'src/LSP-client'
#  displayName: 'VSCode Extension Publish'
#  env:
#    VSCEPAT: $(vsce-pat)
steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
