// <copyright file="Issue3704ExplicitInterfacePropertyHidingEmitTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Diagnostics;
using System.IO;
using Xunit;

namespace GSharp.Compiler.Tests.Emit;

/// <summary>
/// Issue #3704: reading a member off a concrete CLR receiver consulted the
/// receiver's interfaces before the receiver's own FIELDS, so an ABSTRACT
/// interface property the class implements EXPLICITLY was surfaced in place of
/// the class's own same-named field.
/// <para>
/// <c>StrongBox&lt;T&gt;</c> is the canonical shape: a public field
/// <c>Value</c> of type <c>T</c> alongside an explicitly implemented
/// <c>IStrongBox.Value</c> of type <c>object?</c>. Every <c>box.Value</c> read
/// therefore typed as <c>object?</c> and failed with
/// <c>GS0156 Cannot convert type 'object?' to 'bool'</c> — the single error
/// that took migrated <c>Cs2Gs.Translator</c>, and the seven apps that compile
/// it, off the #3501 self-migration gate.
/// </para>
/// <para>
/// The repair is an ORDERING one: a member the receiver's own type declares
/// outranks one reached only through an interface. The interface walk itself
/// stays — a receiver with no competing own member must still reach the
/// interface property, which is how <c>[]T.Count</c> resolves at all
/// (<c>System.Array</c> implements <c>ICollection.Count</c> EXPLICITLY). The
/// slice and no-competitor cases below pin that second direction, alongside the
/// <c>Issue572DimDispatchOnConcreteTypeEmitTests</c> and
/// <c>Issue2455CompositeTypeCollisionTests</c> suites.
/// </para>
/// </summary>
public class Issue3704ExplicitInterfacePropertyHidingEmitTests
{
    [Fact]
    public void StrongBoxValueField_BindsToTheFieldNotTheExplicitInterfaceProperty()
    {
        const string Source = """
            package P
            import System
            import System.Runtime.CompilerServices

            var flag = StrongBox[bool](true)
            var text = StrongBox[string]("boxed")

            var readBool bool = flag.Value
            var readString string = text.Value

            Console.WriteLine(readBool)
            Console.WriteLine(readString)
            """;

        Assert.Equal(
            $"True{Environment.NewLine}boxed{Environment.NewLine}",
            CompileAndRun(Source));
    }

    [Fact]
    public void ConditionalWeakTableOfStrongBox_ReadsTheBooleanPayload()
    {
        // The exact shape emitted for `ObliviousNullabilityAnalyzer`'s memoized
        // `HasAutoGeneratedHeader`: a `ConditionalWeakTable` keyed lookup whose
        // `StrongBox[bool]` result is returned straight into a `bool` position.
        const string Source = """
            package P
            import System
            import System.Runtime.CompilerServices

            let table = ConditionalWeakTable[string, StrongBox[bool]]()

            func IsLong(key string) bool {
                return table
                    .GetValue(key, (scanned string) -> StrongBox[bool](scanned.Length > 3))
                    .Value
            }

            Console.WriteLine(IsLong("abcd"))
            Console.WriteLine(IsLong("ab"))
            """;

        Assert.Equal(
            $"True{Environment.NewLine}False{Environment.NewLine}",
            CompileAndRun(Source));
    }

    [Fact]
    public void SliceMembersReachedThroughAnExplicitInterfaceImplementationStillResolve()
    {
        // The other direction of #3704. `System.Array` implements
        // `ICollection.Count`, `IList.IsFixedSize` and `IList.this[int]`
        // EXPLICITLY, so a slice reaches them ONLY through the interface walk —
        // it declares no competing member of its own. Narrowing the walk far
        // enough to take these out breaks `.Count` on every slice in the
        // language (it regressed `Issue2455CompositeTypeCollisionTests` once).
        const string Source = """
            package P
            import System

            var chapters []string = []string{"one", "two", "three"}

            Console.WriteLine(chapters.Count.ToString())
            Console.WriteLine(chapters.Length.ToString())
            Console.WriteLine(chapters.IsFixedSize)
            Console.WriteLine(chapters[1])
            """;

        Assert.Equal(
            $"3{Environment.NewLine}3{Environment.NewLine}True{Environment.NewLine}two{Environment.NewLine}",
            CompileAndRun(Source));
    }

    [Fact]
    public void ExplicitInterfacePropertyWithNoCompetingOwnMemberStillResolves()
    {
        // `List<T>` implements `ICollection<T>.IsReadOnly` explicitly and
        // declares no `IsReadOnly` of its own, so the interface walk is the
        // only way to reach it — the case that must NOT be narrowed away.
        const string Source = """
            package P
            import System
            import System.Collections.Generic

            var names = List[string]()
            names.Add("a")

            Console.WriteLine(names.IsReadOnly)
            Console.WriteLine(names.Count.ToString())
            """;

        Assert.Equal(
            $"False{Environment.NewLine}1{Environment.NewLine}",
            CompileAndRun(Source));
    }

    private static string CompileAndRun(string source)
    {
        var directory = Directory.CreateTempSubdirectory("gs_issue3704_").FullName;
        try
        {
            var sourcePath = Path.Combine(directory, "test.gs");
            var outputPath = Path.Combine(directory, "test.dll");
            File.WriteAllText(sourcePath, source);

            using var stdout = new StringWriter();
            using var stderr = new StringWriter();
            var previousOut = Console.Out;
            var previousError = Console.Error;
            Console.SetOut(stdout);
            Console.SetError(stderr);
            int exitCode;
            try
            {
                exitCode = Program.Main(new[]
                {
                    "/out:" + outputPath,
                    "/target:exe",
                    "/targetframework:net10.0",
                    sourcePath,
                });
            }
            finally
            {
                Console.SetOut(previousOut);
                Console.SetError(previousError);
            }

            Assert.True(exitCode == 0, $"gsc failed:\n{stdout}\n{stderr}");
            IlVerifier.Verify(outputPath);

            var startInfo = new ProcessStartInfo("dotnet")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                WorkingDirectory = directory,
            };
            startInfo.ArgumentList.Add("exec");
            startInfo.ArgumentList.Add("--runtimeconfig");
            startInfo.ArgumentList.Add(Path.ChangeExtension(outputPath, ".runtimeconfig.json"));
            startInfo.ArgumentList.Add(outputPath);

            using var process = Process.Start(startInfo);
            var runtimeOutput = process!.StandardOutput.ReadToEnd();
            var runtimeError = process.StandardError.ReadToEnd();
            Assert.True(process.WaitForExit(30_000), "dotnet exec timed out");
            Assert.True(process.ExitCode == 0, $"runtime failed:\n{runtimeOutput}\n{runtimeError}");
            return runtimeOutput.ReplaceLineEndings(Environment.NewLine);
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }
}
