// <copyright file="Issue1515LoopInSwitchArmEmitTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Diagnostics;
using System.IO;
using GSharp.Compiler;
using Xunit;

namespace GSharp.Compiler.Tests.Emit;

/// <summary>
/// Issue #1515 — a loop (<c>for … in …</c> or C-style <c>for …; …; …</c>) placed
/// inside a <c>switch</c>-statement arm body crashed IL emission with
/// <c>GS9998: KeyNotFoundException</c> for a loop-generated branch label
/// (<c>Label1</c>, <c>check1</c>, …).
/// <para>
/// Root cause: <c>MethodBodyPlanner.CollectStatements</c> — the label/local
/// pre-pass that <c>il.DefineLabel()</c>s every label and allocates nested
/// locals — recursed into <c>scope</c>/<c>fixed</c>/<c>select</c>/<c>try</c>/
/// block bodies but had NO <c>BoundPatternSwitchStatement</c> case, so it never
/// descended into pattern-switch arm bodies. Labels generated by loop lowering
/// inside an arm were therefore never registered, and the later
/// <c>this.labels[target]</c> lookup in <c>EmitPatternSwitchStatement</c> threw.
/// </para>
/// <para>
/// The fix adds a <c>BoundPatternSwitchStatement</c> case to
/// <c>CollectStatements</c> in BOTH passes (mirroring the existing
/// <c>BoundSelectStatement</c>/<c>BoundTryStatement</c> handling) so every arm
/// body is recursed and every nested label/local-generating construct — at any
/// depth — is planned. Because the recursion re-uses <c>CollectStatements</c>,
/// it generalizes to nested switches, arms inside arms, <c>try</c>/<c>finally</c>,
/// <c>while</c>/<c>do-while</c>, <c>scope</c>, <c>fixed</c>, <c>select</c>, etc.
/// </para>
/// Each test uses a UNIQUE package name because the in-process
/// <c>FunctionTypeSymbol</c> cache is name-keyed and shared across the process.
/// </summary>
public class Issue1515LoopInSwitchArmEmitTests
{
    [Fact]
    public void EndToEnd_ForIn_InConstantSwitchArm_VerifiesAndRuns()
    {
        // Repro A from the issue: `for … in` inside a constant `case 1` arm.
        const string source = """
            package Issue1515ForInArm
            import System
            func describe(n int32, xs []int32) {
                switch n {
                    case 1 {
                        for x in xs { Console.WriteLine(x) }
                    }
                }
            }
            func Main() { describe(1, []int32{1, 2, 3}) }
            """;

        var output = CompileAndRun(source);
        Assert.Equal("1\n2\n3\n", output);
    }

    [Fact]
    public void EndToEnd_CStyleFor_InConstantSwitchArm_WithDefault_VerifiesAndRuns()
    {
        // Repro B from the issue: C-style `for` inside a `case 1` arm alongside a
        // `default` arm.
        const string source = """
            package Issue1515ForCArm
            import System
            func describe(n int32) {
                switch n {
                    case 1 {
                        for var i = 0; i < 3; i = i + 1 { Console.WriteLine(i) }
                    }
                    default { Console.WriteLine("other") }
                }
            }
            func Main() { describe(1) }
            """;

        var output = CompileAndRun(source);
        Assert.Equal("0\n1\n2\n", output);
    }

    [Fact]
    public void EndToEnd_ForIn_InPatternSwitchArm_VerifiesAndRuns()
    {
        // Proves the bug is NOT pattern-specific: a loop inside a slice-pattern
        // arm (`case [1, _, 3]`) must also plan its labels.
        const string source = """
            package Issue1515PatternArm
            import System
            func describe(xs []int32) {
                switch xs {
                    case [1, _, 3] {
                        for x in xs { Console.WriteLine(x) }
                    }
                    default { Console.WriteLine("no-match") }
                }
            }
            func Main() { describe([]int32{1, 2, 3}) }
            """;

        var output = CompileAndRun(source);
        Assert.Equal("1\n2\n3\n", output);
    }

    [Fact]
    public void EndToEnd_ForIn_InArmNestedInsideAnotherArm_VerifiesAndRuns()
    {
        // Generalized case: a loop inside an arm that is itself inside another
        // arm — the recursion must descend to arbitrary depth.
        const string source = """
            package Issue1515NestedArm
            import System
            func describe(n int32, m int32, xs []int32) {
                switch n {
                    case 1 {
                        switch m {
                            case 2 {
                                for x in xs { Console.WriteLine(x) }
                            }
                            default { Console.WriteLine("inner-default") }
                        }
                    }
                    default { Console.WriteLine("outer-default") }
                }
            }
            func Main() { describe(1, 2, []int32{7, 8, 9}) }
            """;

        var output = CompileAndRun(source);
        Assert.Equal("7\n8\n9\n", output);
    }

    [Fact]
    public void EndToEnd_TryWhile_InSwitchArm_VerifiesAndRuns()
    {
        // Generalized case: a `while` loop whose body contains a `try`/`finally`
        // inside a switch arm exercises loop labels AND try leave-target labels
        // planned through the arm-body recursion.
        const string source = """
            package Issue1515TryWhileArm
            import System
            func describe(n int32) {
                switch n {
                    case 1 {
                        var i = 0
                        while i < 3 {
                            try {
                                Console.WriteLine(i)
                            } finally {
                                i = i + 1
                            }
                        }
                    }
                }
            }
            func Main() { describe(1) }
            """;

        var output = CompileAndRun(source);
        Assert.Equal("0\n1\n2\n", output);
    }

    private static string CompileAndRun(string source)
    {
        var tempDir = Directory.CreateTempSubdirectory("gs_1515_exe_").FullName;
        try
        {
            var srcPath = Path.Combine(tempDir, "test.gs");
            var dllPath = Path.Combine(tempDir, "test.dll");
            File.WriteAllText(srcPath, source);

            var args = new[]
            {
                "/out:" + dllPath,
                "/target:exe",
                "/targetframework:net10.0",
                srcPath,
            };

            using var stdoutWriter = new StringWriter();
            using var stderrWriter = new StringWriter();
            var prevOut = Console.Out;
            var prevErr = Console.Error;
            Console.SetOut(stdoutWriter);
            Console.SetError(stderrWriter);
            int compileExit;
            try
            {
                compileExit = Program.Main(args);
            }
            finally
            {
                Console.SetOut(prevOut);
                Console.SetError(prevErr);
            }

            Assert.True(
                compileExit == 0,
                $"gsc failed:\nstdout:\n{stdoutWriter}\nstderr:\n{stderrWriter}");

            IlVerifier.Verify(dllPath);

            var rtConfig = Path.ChangeExtension(dllPath, ".runtimeconfig.json");
            if (!File.Exists(rtConfig))
            {
                File.WriteAllText(rtConfig, """
                    {
                      "runtimeOptions": {
                        "tfm": "net10.0",
                        "framework": { "name": "Microsoft.NETCore.App", "version": "10.0.0" }
                      }
                    }
                    """);
            }

            var psi = new ProcessStartInfo("dotnet")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                WorkingDirectory = tempDir,
            };
            psi.ArgumentList.Add("exec");
            psi.ArgumentList.Add("--runtimeconfig");
            psi.ArgumentList.Add(rtConfig);
            psi.ArgumentList.Add(dllPath);

            using var proc = Process.Start(psi)
                ?? throw new InvalidOperationException("Failed to start dotnet exec");
            var stdout = proc.StandardOutput.ReadToEnd();
            var stderr = proc.StandardError.ReadToEnd();
            Assert.True(proc.WaitForExit(30_000), "dotnet exec timed out");
            Assert.True(
                proc.ExitCode == 0,
                $"exited {proc.ExitCode}\nstdout:\n{stdout}\nstderr:\n{stderr}");

            return stdout.Replace("\r\n", "\n");
        }
        finally
        {
            try { Directory.Delete(tempDir, recursive: true); } catch { }
        }
    }
}
