<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppTargetFramework)</TargetFramework>
    <AssemblyName>GSharp.Issue3119.ImportedConstants</AssemblyName>
    <RootNamespace>GSharp.Issue3119.Same</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
