// <copyright file="ResxDesignerGenerator.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System.Collections.Generic;
using System.Text;

namespace GSharp.Core.Resx;

/// <summary>
/// Generates the G# equivalent of a resx codebehind file — the class a C#
/// project gets from <c>ResXFileCodeGenerator</c> / <c>PublicResXFileCodeGenerator</c>
/// (ADR-0142, issue #2200). The generated class exposes the same shape as the
/// CodeDom-produced C# class: a lazily-created <c>ResourceManager</c>, a
/// settable <c>Culture</c>, a private parameterless constructor, and one
/// static property per resx entry — a plain <c>string</c> property reading
/// through <c>GetString</c> for the dominant string-resource case, or a
/// typed property reading through <c>GetObject</c> (downcast with <c>as</c>)
/// for anything else. This is the single generator shared by the G# language
/// server (regenerates on <c>.resx</c> save) and by <c>cs2gs</c> (produces the
/// codebehind for a migrated project's <c>.resx</c> files instead of
/// translating the C# <c>Designer.cs</c>).
/// </summary>
public static class ResxDesignerGenerator
{
    /// <summary>
    /// Generates the full G# source text for a resx's strongly-typed
    /// resource class.
    /// </summary>
    /// <param name="document">The parsed resx document.</param>
    /// <param name="options">The namespace/class-name/visibility inputs.</param>
    /// <returns>The generated G# source (a complete, self-contained compilation unit).</returns>
    public static string Generate(ResxDocument document, ResxDesignerOptions options)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by the GSharp resx code generator, from the");
        sb.AppendLine("//     matching .resx file. Changes to this file may cause incorrect behavior");
        sb.AppendLine("//     and will be lost if the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(options.Namespace))
        {
            sb.Append("package ").AppendLine(options.Namespace);
            sb.AppendLine();
        }

        sb.AppendLine("/// A strongly-typed resource class, for looking up localized strings, etc.");

        string classAccessibility = options.IsPublic ? "public" : "internal";
        sb.Append(classAccessibility).Append(" class ").AppendLine(options.ClassName + " {");

        // Matches the real tool's `internal Resources() { }`: the class only
        // ever surfaces static members, so the constructor stays `internal`
        // regardless of the class's own accessibility, discouraging direct
        // instantiation without preventing static member access.
        sb.Append("    internal init() { }").AppendLine();
        sb.AppendLine();

        sb.AppendLine("    shared {");
        sb.AppendLine("        var resourceMan System.Resources.ResourceManager?");
        sb.AppendLine("        var resourceCulture System.Globalization.CultureInfo?");
        sb.AppendLine();
        sb.AppendLine("        /// Returns the cached ResourceManager instance used by this class.");
        sb.AppendLine("        prop ResourceManager System.Resources.ResourceManager {");
        sb.AppendLine("            get {");
        sb.AppendLine("                if resourceMan == nil {");
        sb.Append("                    var temp = System.Resources.ResourceManager(\"")
            .Append(options.ResourceManifestName)
            .Append("\", typeof(")
            .Append(options.ClassName)
            .AppendLine(").Assembly)");
        sb.AppendLine("                    resourceMan = temp");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                return resourceMan!!");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// Overrides the current thread's CurrentUICulture property for all");
        sb.AppendLine("        /// resource lookups using this strongly typed resource class.");
        sb.AppendLine("        prop Culture System.Globalization.CultureInfo? {");
        sb.AppendLine("            get { return resourceCulture }");
        sb.AppendLine("            set { resourceCulture = value }");
        sb.AppendLine("        }");

        var usedNames = new HashSet<string>(System.StringComparer.Ordinal) { "ResourceManager", "Culture" };
        foreach (var entry in document.Entries)
        {
            sb.AppendLine();
            AppendEntry(sb, entry, usedNames);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendEntry(StringBuilder sb, ResxEntry entry, HashSet<string> usedNames)
    {
        string identifier = ResxIdentifier.ToPropertyIdentifier(entry.Name, usedNames);

        sb.Append("        /// ").AppendLine(SummaryFor(entry));

        if (entry.IsString)
        {
            sb.Append("        prop ")
                .Append(identifier)
                .Append(" string -> ResourceManager.GetString(\"")
                .Append(entry.Name)
                .AppendLine("\", resourceCulture)!!");
            return;
        }

        string gsType = ResxTypeNameMapper.Map(entry.TypeName);
        sb.Append("        prop ").Append(identifier).Append(' ').Append(gsType).AppendLine(" {");
        sb.AppendLine("            get {");
        sb.Append("                return (ResourceManager.GetObject(\"")
            .Append(entry.Name)
            .Append("\", resourceCulture) as ")
            .Append(gsType)
            .AppendLine(")!!");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static string SummaryFor(ResxEntry entry)
    {
        if (!entry.IsString)
        {
            return "Looks up a localized resource of type " + entry.TypeName + ".";
        }

        string value = entry.Value ?? string.Empty;
        int newline = value.IndexOfAny(new[] { '\r', '\n' });
        bool truncated = newline >= 0;
        string firstLine = truncated ? value.Substring(0, newline) : value;

        const int maxLength = 80;
        if (firstLine.Length > maxLength)
        {
            firstLine = firstLine.Substring(0, maxLength);
            truncated = true;
        }

        return "Looks up a localized string similar to " + firstLine + (truncated ? " [...]." : ".");
    }
}
