// <auto-generated/>
// Hand-authored LSP protocol types for GSharp. Marked auto-generated to opt out of
// StyleCop documentation/ordering rules; this is protocol plumbing, not product logic.

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace GSharp.LanguageServer.Protocol;

public sealed class SaveOptions
{
    [JsonPropertyName("includeText")]
    public bool IncludeText { get; set; }
}

public sealed class TextDocumentSyncOptions
{
    [JsonPropertyName("openClose")]
    public bool OpenClose { get; set; }

    [JsonPropertyName("change")]
    public int Change { get; set; }

    [JsonPropertyName("save")]
    public SaveOptions Save { get; set; }
}

public sealed class CompletionOptions
{
    [JsonPropertyName("triggerCharacters")]
    public IReadOnlyList<string> TriggerCharacters { get; set; }

    [JsonPropertyName("resolveProvider")]
    public bool ResolveProvider { get; set; }
}

public sealed class SignatureHelpOptions
{
    [JsonPropertyName("triggerCharacters")]
    public IReadOnlyList<string> TriggerCharacters { get; set; }

    [JsonPropertyName("retriggerCharacters")]
    public IReadOnlyList<string> RetriggerCharacters { get; set; }
}

public sealed class CodeActionOptions
{
    [JsonPropertyName("codeActionKinds")]
    public IReadOnlyList<CodeActionKind> CodeActionKinds { get; set; }
}

public sealed class CodeLensOptions
{
    [JsonPropertyName("resolveProvider")]
    public bool ResolveProvider { get; set; }
}

public sealed class DocumentOnTypeFormattingOptions
{
    [JsonPropertyName("firstTriggerCharacter")]
    public string FirstTriggerCharacter { get; set; }

    [JsonPropertyName("moreTriggerCharacter")]
    public IReadOnlyList<string> MoreTriggerCharacter { get; set; }
}

public sealed class RenameOptions
{
    [JsonPropertyName("prepareProvider")]
    public bool PrepareProvider { get; set; }
}

public sealed class SemanticTokensServerFull
{
    [JsonPropertyName("delta")]
    public bool Delta { get; set; }
}

public sealed class SemanticTokensOptions
{
    [JsonPropertyName("legend")]
    public SemanticTokensLegend Legend { get; set; }

    [JsonPropertyName("full")]
    public SemanticTokensServerFull Full { get; set; }

    [JsonPropertyName("range")]
    public bool Range { get; set; }
}

public sealed class InlayHintOptions
{
    [JsonPropertyName("resolveProvider")]
    public bool ResolveProvider { get; set; }
}

public sealed class DiagnosticOptions
{
    [JsonPropertyName("identifier")]
    public string Identifier { get; set; }

    [JsonPropertyName("interFileDependencies")]
    public bool InterFileDependencies { get; set; }

    [JsonPropertyName("workspaceDiagnostics")]
    public bool WorkspaceDiagnostics { get; set; }
}

public sealed class ServerCapabilities
{
    [JsonPropertyName("textDocumentSync")]
    public TextDocumentSyncOptions TextDocumentSync { get; set; }

    [JsonPropertyName("hoverProvider")]
    public bool HoverProvider { get; set; }

    [JsonPropertyName("definitionProvider")]
    public bool DefinitionProvider { get; set; }

    [JsonPropertyName("typeDefinitionProvider")]
    public bool TypeDefinitionProvider { get; set; }

    [JsonPropertyName("implementationProvider")]
    public bool ImplementationProvider { get; set; }

    [JsonPropertyName("referencesProvider")]
    public bool ReferencesProvider { get; set; }

    [JsonPropertyName("documentHighlightProvider")]
    public bool DocumentHighlightProvider { get; set; }

    [JsonPropertyName("documentSymbolProvider")]
    public bool DocumentSymbolProvider { get; set; }

    [JsonPropertyName("workspaceSymbolProvider")]
    public bool WorkspaceSymbolProvider { get; set; }

    [JsonPropertyName("codeActionProvider")]
    public CodeActionOptions CodeActionProvider { get; set; }

    [JsonPropertyName("codeLensProvider")]
    public CodeLensOptions CodeLensProvider { get; set; }

    [JsonPropertyName("documentFormattingProvider")]
    public bool DocumentFormattingProvider { get; set; }

    [JsonPropertyName("documentRangeFormattingProvider")]
    public bool DocumentRangeFormattingProvider { get; set; }

    [JsonPropertyName("documentOnTypeFormattingProvider")]
    public DocumentOnTypeFormattingOptions DocumentOnTypeFormattingProvider { get; set; }

    [JsonPropertyName("renameProvider")]
    public RenameOptions RenameProvider { get; set; }

    [JsonPropertyName("foldingRangeProvider")]
    public bool FoldingRangeProvider { get; set; }

    [JsonPropertyName("selectionRangeProvider")]
    public bool SelectionRangeProvider { get; set; }

    [JsonPropertyName("semanticTokensProvider")]
    public SemanticTokensOptions SemanticTokensProvider { get; set; }

    [JsonPropertyName("completionProvider")]
    public CompletionOptions CompletionProvider { get; set; }

    [JsonPropertyName("signatureHelpProvider")]
    public SignatureHelpOptions SignatureHelpProvider { get; set; }

    [JsonPropertyName("inlayHintProvider")]
    public InlayHintOptions InlayHintProvider { get; set; }

    [JsonPropertyName("linkedEditingRangeProvider")]
    public bool LinkedEditingRangeProvider { get; set; }

    [JsonPropertyName("diagnosticProvider")]
    public DiagnosticOptions DiagnosticProvider { get; set; }
}
