#nullable disable

// <auto-generated/>
// Hand-authored LSP protocol types for GSharp. Marked auto-generated to opt out of
// StyleCop documentation/ordering rules; this is protocol plumbing, not product logic.

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace GSharp.LanguageServer.Protocol;

/// <summary>
/// Central System.Text.Json configuration for the language server protocol.
/// </summary>
public static class LspJson
{
    public static JsonSerializerOptions Options { get; } = Create();

    private static JsonSerializerOptions Create()
    {
        var options = new JsonSerializerOptions
        {
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        };

        options.Converters.Add(new DocumentUriConverter());
        options.Converters.Add(new MarkupKindConverter());
        options.Converters.Add(new CodeActionKindConverter());
        options.Converters.Add(new FoldingRangeKindConverter());
        options.Converters.Add(new SemanticTokenTypeConverter());
        options.Converters.Add(new SemanticTokenModifierConverter());
        options.Converters.Add(new MarkedStringsOrMarkupContentConverter());
        options.Converters.Add(new SymbolInformationOrDocumentSymbolConverter());
        options.Converters.Add(new CommandOrCodeActionConverter());
        options.Converters.Add(new CommandOrCodeActionContainerConverter());
        options.Converters.Add(new StringOrInlayHintLabelPartsConverter());
        options.Converters.Add(new DiagnosticCodeConverter());
        return options;
    }
}

public sealed class DocumentUriConverter : JsonConverter<DocumentUri>
{
    public override DocumentUri Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => DocumentUri.From(reader.GetString());

    public override void Write(Utf8JsonWriter writer, DocumentUri value, JsonSerializerOptions options)
        => writer.WriteStringValue(value?.ToString());

    public override DocumentUri ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => DocumentUri.From(reader.GetString());

    public override void WriteAsPropertyName(Utf8JsonWriter writer, DocumentUri value, JsonSerializerOptions options)
        => writer.WritePropertyName(value?.ToString() ?? string.Empty);
}

public sealed class MarkupKindConverter : JsonConverter<MarkupKind>
{
    public override MarkupKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new MarkupKind(reader.GetString());

    public override void Write(Utf8JsonWriter writer, MarkupKind value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.Value);
}

public sealed class CodeActionKindConverter : JsonConverter<CodeActionKind>
{
    public override CodeActionKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new CodeActionKind(reader.GetString());

    public override void Write(Utf8JsonWriter writer, CodeActionKind value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.Value);
}

public sealed class FoldingRangeKindConverter : JsonConverter<FoldingRangeKind>
{
    public override FoldingRangeKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new FoldingRangeKind(reader.GetString());

    public override void Write(Utf8JsonWriter writer, FoldingRangeKind value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.Value);
}

public sealed class SemanticTokenTypeConverter : JsonConverter<SemanticTokenType>
{
    public override SemanticTokenType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new SemanticTokenType(reader.GetString());

    public override void Write(Utf8JsonWriter writer, SemanticTokenType value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.Value);
}

public sealed class SemanticTokenModifierConverter : JsonConverter<SemanticTokenModifier>
{
    public override SemanticTokenModifier Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new SemanticTokenModifier(reader.GetString());

    public override void Write(Utf8JsonWriter writer, SemanticTokenModifier value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.Value);
}

public sealed class MarkedStringsOrMarkupContentConverter : JsonConverter<MarkedStringsOrMarkupContent>
{
    public override MarkedStringsOrMarkupContent Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var content = JsonSerializer.Deserialize<MarkupContent>(ref reader, options);
        return new MarkedStringsOrMarkupContent(content);
    }

    public override void Write(Utf8JsonWriter writer, MarkedStringsOrMarkupContent value, JsonSerializerOptions options)
        => JsonSerializer.Serialize(writer, value.MarkupContent, options);
}

public sealed class SymbolInformationOrDocumentSymbolConverter : JsonConverter<SymbolInformationOrDocumentSymbol>
{
    public override SymbolInformationOrDocumentSymbol Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var symbol = JsonSerializer.Deserialize<DocumentSymbol>(ref reader, options);
        return new SymbolInformationOrDocumentSymbol(symbol);
    }

    public override void Write(Utf8JsonWriter writer, SymbolInformationOrDocumentSymbol value, JsonSerializerOptions options)
        => JsonSerializer.Serialize(writer, value.DocumentSymbol, options);
}

public sealed class CommandOrCodeActionConverter : JsonConverter<CommandOrCodeAction>
{
    public override CommandOrCodeAction Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var action = JsonSerializer.Deserialize<CodeAction>(ref reader, options);
        return new CommandOrCodeAction(action);
    }

    public override void Write(Utf8JsonWriter writer, CommandOrCodeAction value, JsonSerializerOptions options)
    {
        if (value.CodeAction != null)
        {
            JsonSerializer.Serialize(writer, value.CodeAction, options);
        }
        else
        {
            JsonSerializer.Serialize(writer, value.Command, options);
        }
    }
}

public sealed class CommandOrCodeActionContainerConverter : JsonConverter<CommandOrCodeActionContainer>
{
    public override CommandOrCodeActionContainer Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var items = JsonSerializer.Deserialize<System.Collections.Generic.List<CommandOrCodeAction>>(ref reader, options);
        return new CommandOrCodeActionContainer(items);
    }

    public override void Write(Utf8JsonWriter writer, CommandOrCodeActionContainer value, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        foreach (var item in value)
        {
            JsonSerializer.Serialize(writer, item, options);
        }

        writer.WriteEndArray();
    }
}

public sealed class StringOrInlayHintLabelPartsConverter : JsonConverter<StringOrInlayHintLabelParts>
{
    public override StringOrInlayHintLabelParts Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new StringOrInlayHintLabelParts(reader.GetString());

    public override void Write(Utf8JsonWriter writer, StringOrInlayHintLabelParts value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.String);
}

public sealed class DiagnosticCodeConverter : JsonConverter<DiagnosticCode>
{
    public override DiagnosticCode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => new DiagnosticCode(reader.GetString());

    public override void Write(Utf8JsonWriter writer, DiagnosticCode value, JsonSerializerOptions options)
        => writer.WriteStringValue(value?.Value);
}
