// <auto-generated/>
// Hand-authored LSP protocol types for GSharp. Marked auto-generated to opt out of
// StyleCop documentation/ordering rules; this is protocol plumbing, not product logic.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;

namespace GSharp.LanguageServer.Protocol;

/// <summary>Represents a document URI; serializes to/from a string.</summary>
public sealed class DocumentUri : IEquatable<DocumentUri>
{
    private readonly string uri;

    private DocumentUri(string uri) => this.uri = uri ?? string.Empty;

    public static DocumentUri From(string value) => value == null ? null : new DocumentUri(value);

    public static DocumentUri FromFileSystemPath(string path)
    {
        if (string.IsNullOrEmpty(path))
        {
            return null;
        }

        var full = System.IO.Path.GetFullPath(path);
        return new DocumentUri(new Uri(full).AbsoluteUri);
    }

    public string GetFileSystemPath()
    {
        if (string.IsNullOrEmpty(this.uri))
        {
            return null;
        }

        if (this.uri.StartsWith("file:", StringComparison.OrdinalIgnoreCase))
        {
            try
            {
                return new Uri(this.uri).LocalPath;
            }
            catch (UriFormatException)
            {
                return this.uri;
            }
        }

        return this.uri;
    }

    public bool Equals(DocumentUri other) => other != null && string.Equals(this.uri, other.uri, StringComparison.Ordinal);

    public override bool Equals(object obj) => this.Equals(obj as DocumentUri);

    public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(this.uri);

    public override string ToString() => this.uri;

    public static implicit operator DocumentUri(string value) => From(value);
}

public sealed class TextDocumentIdentifier
{
    [JsonPropertyName("uri")]
    public DocumentUri Uri { get; set; }
}

public sealed class VersionedTextDocumentIdentifier
{
    [JsonPropertyName("uri")]
    public DocumentUri Uri { get; set; }

    [JsonPropertyName("version")]
    public int? Version { get; set; }
}

public sealed class TextDocumentItem
{
    [JsonPropertyName("uri")]
    public DocumentUri Uri { get; set; }

    [JsonPropertyName("languageId")]
    public string LanguageId { get; set; }

    [JsonPropertyName("version")]
    public int Version { get; set; }

    [JsonPropertyName("text")]
    public string Text { get; set; }
}

public sealed class Position
{
    public Position()
    {
    }

    public Position(int line, int character)
    {
        this.Line = line;
        this.Character = character;
    }

    [JsonPropertyName("line")]
    public int Line { get; set; }

    [JsonPropertyName("character")]
    public int Character { get; set; }
}

public sealed class Range
{
    public Range()
    {
    }

    public Range(Position start, Position end)
    {
        this.Start = start;
        this.End = end;
    }

    [JsonPropertyName("start")]
    public Position Start { get; set; }

    [JsonPropertyName("end")]
    public Position End { get; set; }
}

public sealed class Location
{
    [JsonPropertyName("uri")]
    public DocumentUri Uri { get; set; }

    [JsonPropertyName("range")]
    public Range Range { get; set; }
}

public sealed class TextEdit
{
    [JsonPropertyName("range")]
    public Range Range { get; set; }

    [JsonPropertyName("newText")]
    public string NewText { get; set; }
}

public readonly struct MarkupKind : IEquatable<MarkupKind>
{
    public MarkupKind(string value) => this.Value = value;

    public static MarkupKind PlainText => new MarkupKind("plaintext");

    public static MarkupKind Markdown => new MarkupKind("markdown");

    public string Value { get; }

    public bool Equals(MarkupKind other) => string.Equals(this.Value, other.Value, StringComparison.Ordinal);

    public override bool Equals(object obj) => obj is MarkupKind other && this.Equals(other);

    public override int GetHashCode() => this.Value == null ? 0 : StringComparer.Ordinal.GetHashCode(this.Value);

    public override string ToString() => this.Value;

    public static bool operator ==(MarkupKind left, MarkupKind right) => left.Equals(right);

    public static bool operator !=(MarkupKind left, MarkupKind right) => !left.Equals(right);
}

public sealed class MarkupContent
{
    [JsonPropertyName("kind")]
    public MarkupKind Kind { get; set; }

    [JsonPropertyName("value")]
    public string Value { get; set; }

    public override string ToString() => this.Value;
}

[JsonConverter(typeof(MarkedStringsOrMarkupContentConverter))]
public sealed class MarkedStringsOrMarkupContent
{
    public MarkedStringsOrMarkupContent(MarkupContent markupContent) => this.MarkupContent = markupContent;

    public MarkupContent MarkupContent { get; }

    public override string ToString() => this.MarkupContent?.Value ?? string.Empty;
}

public sealed class Hover
{
    [JsonPropertyName("contents")]
    public MarkedStringsOrMarkupContent Contents { get; set; }

    [JsonPropertyName("range")]
    public Range Range { get; set; }
}

public enum CompletionItemKind
{
    Text = 1,
    Method = 2,
    Function = 3,
    Constructor = 4,
    Field = 5,
    Variable = 6,
    Class = 7,
    Interface = 8,
    Module = 9,
    Property = 10,
    Unit = 11,
    Value = 12,
    Enum = 13,
    Keyword = 14,
    Snippet = 15,
    Color = 16,
    File = 17,
    Reference = 18,
    Folder = 19,
    EnumMember = 20,
    Constant = 21,
    Struct = 22,
    Event = 23,
    Operator = 24,
    TypeParameter = 25,
}

public sealed class CompletionItem
{
    [JsonPropertyName("label")]
    public string Label { get; set; }

    [JsonPropertyName("kind")]
    public CompletionItemKind Kind { get; set; }

    [JsonPropertyName("detail")]
    public string Detail { get; set; }
}

public sealed class CompletionList
{
    public CompletionList()
    {
    }

    public CompletionList(IEnumerable<CompletionItem> items) => this.Items = items?.ToList() ?? new List<CompletionItem>();

    [JsonPropertyName("isIncomplete")]
    public bool IsIncomplete { get; set; }

    [JsonPropertyName("items")]
    public List<CompletionItem> Items { get; set; } = new List<CompletionItem>();
}

public enum SymbolKind
{
    File = 1,
    Module = 2,
    Namespace = 3,
    Package = 4,
    Class = 5,
    Method = 6,
    Property = 7,
    Field = 8,
    Constructor = 9,
    Enum = 10,
    Interface = 11,
    Function = 12,
    Variable = 13,
    Constant = 14,
    String = 15,
    Number = 16,
    Boolean = 17,
    Array = 18,
    Object = 19,
    Key = 20,
    Null = 21,
    EnumMember = 22,
    Struct = 23,
    Event = 24,
    Operator = 25,
    TypeParameter = 26,
}

public sealed class DocumentSymbol
{
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("detail")]
    public string Detail { get; set; }

    [JsonPropertyName("kind")]
    public SymbolKind Kind { get; set; }

    [JsonPropertyName("range")]
    public Range Range { get; set; }

    [JsonPropertyName("selectionRange")]
    public Range SelectionRange { get; set; }

    [JsonPropertyName("children")]
    public IEnumerable<DocumentSymbol> Children { get; set; }
}

[JsonConverter(typeof(SymbolInformationOrDocumentSymbolConverter))]
public sealed class SymbolInformationOrDocumentSymbol
{
    public SymbolInformationOrDocumentSymbol(DocumentSymbol documentSymbol) => this.DocumentSymbol = documentSymbol;

    public DocumentSymbol DocumentSymbol { get; }
}

public sealed class WorkspaceSymbol
{
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("kind")]
    public SymbolKind Kind { get; set; }

    [JsonPropertyName("location")]
    public Location Location { get; set; }
}

public sealed class ParameterInformation
{
    [JsonPropertyName("label")]
    public string Label { get; set; }
}

public sealed class SignatureInformation
{
    [JsonPropertyName("label")]
    public string Label { get; set; }

    [JsonPropertyName("parameters")]
    public IEnumerable<ParameterInformation> Parameters { get; set; }
}

public sealed class SignatureHelp
{
    [JsonPropertyName("signatures")]
    public IEnumerable<SignatureInformation> Signatures { get; set; }

    [JsonPropertyName("activeSignature")]
    public int ActiveSignature { get; set; }

    [JsonPropertyName("activeParameter")]
    public int ActiveParameter { get; set; }
}

public enum DocumentHighlightKind
{
    Text = 1,
    Read = 2,
    Write = 3,
}

public sealed class DocumentHighlight
{
    [JsonPropertyName("range")]
    public Range Range { get; set; }

    [JsonPropertyName("kind")]
    public DocumentHighlightKind Kind { get; set; }
}

public sealed class WorkspaceEdit
{
    [JsonPropertyName("changes")]
    public Dictionary<DocumentUri, IEnumerable<TextEdit>> Changes { get; set; }
}

public sealed class Command
{
    [JsonPropertyName("title")]
    public string Title { get; set; }

    [JsonPropertyName("command")]
    public string Name { get; set; }
}

public readonly struct CodeActionKind : IEquatable<CodeActionKind>
{
    public CodeActionKind(string value) => this.Value = value;

    public static CodeActionKind QuickFix => new CodeActionKind("quickfix");

    public static CodeActionKind Refactor => new CodeActionKind("refactor");

    public static CodeActionKind RefactorRewrite => new CodeActionKind("refactor.rewrite");

    public static CodeActionKind Source => new CodeActionKind("source");

    public string Value { get; }

    public bool Equals(CodeActionKind other) => string.Equals(this.Value, other.Value, StringComparison.Ordinal);

    public override bool Equals(object obj) => obj is CodeActionKind other && this.Equals(other);

    public override int GetHashCode() => this.Value == null ? 0 : StringComparer.Ordinal.GetHashCode(this.Value);

    public override string ToString() => this.Value;

    public static bool operator ==(CodeActionKind left, CodeActionKind right) => left.Equals(right);

    public static bool operator !=(CodeActionKind left, CodeActionKind right) => !left.Equals(right);
}

public sealed class CodeAction
{
    [JsonPropertyName("title")]
    public string Title { get; set; }

    [JsonPropertyName("kind")]
    public CodeActionKind Kind { get; set; }

    [JsonPropertyName("edit")]
    public WorkspaceEdit Edit { get; set; }
}

[JsonConverter(typeof(CommandOrCodeActionConverter))]
public sealed class CommandOrCodeAction
{
    public CommandOrCodeAction(CodeAction codeAction) => this.CodeAction = codeAction;

    public CommandOrCodeAction(Command command) => this.Command = command;

    public CodeAction CodeAction { get; }

    public Command Command { get; }
}

[JsonConverter(typeof(CommandOrCodeActionContainerConverter))]
public sealed class CommandOrCodeActionContainer : IEnumerable<CommandOrCodeAction>
{
    private readonly List<CommandOrCodeAction> items;

    public CommandOrCodeActionContainer() => this.items = new List<CommandOrCodeAction>();

    public CommandOrCodeActionContainer(IEnumerable<CommandOrCodeAction> items)
        => this.items = items?.ToList() ?? new List<CommandOrCodeAction>();

    public IEnumerator<CommandOrCodeAction> GetEnumerator() => this.items.GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => this.items.GetEnumerator();
}

public sealed class CodeLens
{
    [JsonPropertyName("range")]
    public Range Range { get; set; }

    [JsonPropertyName("command")]
    public Command Command { get; set; }
}

public readonly struct FoldingRangeKind : IEquatable<FoldingRangeKind>
{
    public FoldingRangeKind(string value) => this.Value = value;

    public static FoldingRangeKind Comment => new FoldingRangeKind("comment");

    public static FoldingRangeKind Imports => new FoldingRangeKind("imports");

    public static FoldingRangeKind Region => new FoldingRangeKind("region");

    public string Value { get; }

    public bool Equals(FoldingRangeKind other) => string.Equals(this.Value, other.Value, StringComparison.Ordinal);

    public override bool Equals(object obj) => obj is FoldingRangeKind other && this.Equals(other);

    public override int GetHashCode() => this.Value == null ? 0 : StringComparer.Ordinal.GetHashCode(this.Value);

    public override string ToString() => this.Value;

    public static bool operator ==(FoldingRangeKind left, FoldingRangeKind right) => left.Equals(right);

    public static bool operator !=(FoldingRangeKind left, FoldingRangeKind right) => !left.Equals(right);
}

public sealed class FoldingRange
{
    [JsonPropertyName("startLine")]
    public int StartLine { get; set; }

    [JsonPropertyName("startCharacter")]
    public int? StartCharacter { get; set; }

    [JsonPropertyName("endLine")]
    public int EndLine { get; set; }

    [JsonPropertyName("endCharacter")]
    public int? EndCharacter { get; set; }

    [JsonPropertyName("kind")]
    public FoldingRangeKind Kind { get; set; }
}

public sealed class SelectionRange
{
    [JsonPropertyName("range")]
    public Range Range { get; set; }

    [JsonPropertyName("parent")]
    public SelectionRange Parent { get; set; }
}

public enum InlayHintKind
{
    Type = 1,
    Parameter = 2,
}

[JsonConverter(typeof(StringOrInlayHintLabelPartsConverter))]
public sealed class StringOrInlayHintLabelParts
{
    public StringOrInlayHintLabelParts(string value) => this.String = value;

    public string String { get; }
}

public sealed class InlayHint
{
    [JsonPropertyName("position")]
    public Position Position { get; set; }

    [JsonPropertyName("label")]
    public StringOrInlayHintLabelParts Label { get; set; }

    [JsonPropertyName("kind")]
    public InlayHintKind Kind { get; set; }

    [JsonPropertyName("paddingLeft")]
    public bool PaddingLeft { get; set; }

    [JsonPropertyName("paddingRight")]
    public bool PaddingRight { get; set; }
}

public sealed class LinkedEditingRanges
{
    [JsonPropertyName("ranges")]
    public IEnumerable<Range> Ranges { get; set; }

    [JsonPropertyName("wordPattern")]
    public string WordPattern { get; set; }
}

public enum DiagnosticSeverity
{
    Error = 1,
    Warning = 2,
    Information = 3,
    Hint = 4,
}

public sealed class DiagnosticCode
{
    public DiagnosticCode(string value) => this.Value = value;

    public string Value { get; }

    public override string ToString() => this.Value;
}

public sealed class Diagnostic
{
    [JsonPropertyName("range")]
    public Range Range { get; set; }

    [JsonPropertyName("severity")]
    public DiagnosticSeverity Severity { get; set; }

    [JsonPropertyName("code")]
    public DiagnosticCode Code { get; set; }

    [JsonPropertyName("source")]
    public string Source { get; set; }

    [JsonPropertyName("message")]
    public string Message { get; set; }
}

public sealed class PublishDiagnosticsParams
{
    [JsonPropertyName("uri")]
    public DocumentUri Uri { get; set; }

    [JsonPropertyName("diagnostics")]
    public IEnumerable<Diagnostic> Diagnostics { get; set; }
}
