// <auto-generated/>
// Hand-authored LSP protocol types for GSharp. Marked auto-generated to opt out of
// StyleCop documentation/ordering rules; this is protocol plumbing, not product logic.

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace GSharp.LanguageServer.Protocol;

public class TextDocumentPositionParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("position")]
    public Position Position { get; set; }
}

public sealed class HoverParams : TextDocumentPositionParams
{
}

public sealed class DefinitionParams : TextDocumentPositionParams
{
}

public sealed class TypeDefinitionParams : TextDocumentPositionParams
{
}

public sealed class ImplementationParams : TextDocumentPositionParams
{
}

public sealed class DocumentHighlightParams : TextDocumentPositionParams
{
}

public sealed class CompletionParams : TextDocumentPositionParams
{
}

public sealed class SignatureHelpParams : TextDocumentPositionParams
{
}

public sealed class PrepareRenameParams : TextDocumentPositionParams
{
}

public sealed class LinkedEditingRangeParams : TextDocumentPositionParams
{
}

public sealed class ReferenceContext
{
    [JsonPropertyName("includeDeclaration")]
    public bool IncludeDeclaration { get; set; }
}

public sealed class ReferenceParams : TextDocumentPositionParams
{
    [JsonPropertyName("context")]
    public ReferenceContext Context { get; set; }
}

public sealed class RenameParams : TextDocumentPositionParams
{
    [JsonPropertyName("newName")]
    public string NewName { get; set; }
}

public sealed class DocumentSymbolParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }
}

public sealed class CodeActionParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("range")]
    public Range Range { get; set; }
}

public sealed class FormattingOptions
{
    [JsonPropertyName("tabSize")]
    public int TabSize { get; set; }

    [JsonPropertyName("insertSpaces")]
    public bool InsertSpaces { get; set; }
}

public sealed class DocumentFormattingParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("options")]
    public FormattingOptions Options { get; set; }
}

public sealed class DocumentRangeFormattingParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("range")]
    public Range Range { get; set; }

    [JsonPropertyName("options")]
    public FormattingOptions Options { get; set; }
}

public sealed class DocumentOnTypeFormattingParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("position")]
    public Position Position { get; set; }

    [JsonPropertyName("ch")]
    public string Ch { get; set; }

    [JsonPropertyName("options")]
    public FormattingOptions Options { get; set; }
}

public sealed class SelectionRangeParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("positions")]
    public List<Position> Positions { get; set; }
}

public sealed class FoldingRangeParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }
}

public sealed class SemanticTokensParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }
}

public sealed class SemanticTokensRangeParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("range")]
    public Range Range { get; set; }
}

public sealed class InlayHintParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("range")]
    public Range Range { get; set; }
}

public sealed class CodeLensParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }
}

public sealed class WorkspaceSymbolParams
{
    [JsonPropertyName("query")]
    public string Query { get; set; }
}

public sealed class TextDocumentContentChangeEvent
{
    [JsonPropertyName("text")]
    public string Text { get; set; }
}

public sealed class DidOpenTextDocumentParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentItem TextDocument { get; set; }
}

public sealed class DidChangeTextDocumentParams
{
    [JsonPropertyName("textDocument")]
    public VersionedTextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("contentChanges")]
    public List<TextDocumentContentChangeEvent> ContentChanges { get; set; }
}

public sealed class DidSaveTextDocumentParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }

    [JsonPropertyName("text")]
    public string Text { get; set; }
}

public sealed class DidCloseTextDocumentParams
{
    [JsonPropertyName("textDocument")]
    public TextDocumentIdentifier TextDocument { get; set; }
}

public enum FileChangeType
{
    Created = 1,
    Changed = 2,
    Deleted = 3,
}

public sealed class FileEvent
{
    [JsonPropertyName("uri")]
    public DocumentUri Uri { get; set; }

    [JsonPropertyName("type")]
    public FileChangeType Type { get; set; }
}

public sealed class DidChangeWatchedFilesParams
{
    [JsonPropertyName("changes")]
    public List<FileEvent> Changes { get; set; }
}

public sealed class InitializeParams
{
    [JsonPropertyName("processId")]
    public int? ProcessId { get; set; }

    [JsonPropertyName("rootPath")]
    public string RootPath { get; set; }

    [JsonPropertyName("rootUri")]
    public DocumentUri RootUri { get; set; }

    [JsonPropertyName("capabilities")]
    public JsonElement Capabilities { get; set; }
}

public sealed class ServerInfo
{
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("version")]
    public string Version { get; set; }
}

public sealed class InitializeResult
{
    [JsonPropertyName("capabilities")]
    public ServerCapabilities Capabilities { get; set; }

    [JsonPropertyName("serverInfo")]
    public ServerInfo ServerInfo { get; set; }
}
