#nullable disable

// <auto-generated/>
// Hand-authored LSP protocol types for GSharp. Marked auto-generated to opt out of
// StyleCop documentation/ordering rules; this is protocol plumbing, not product logic.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text.Json.Serialization;

namespace GSharp.LanguageServer.Protocol;

public readonly struct SemanticTokenType : IEquatable<SemanticTokenType>
{
    public SemanticTokenType(string value) => this.Value = value;

    public static SemanticTokenType Namespace => new SemanticTokenType("namespace");

    public static SemanticTokenType Type => new SemanticTokenType("type");

    public static SemanticTokenType Struct => new SemanticTokenType("struct");

    public static SemanticTokenType Interface => new SemanticTokenType("interface");

    public static SemanticTokenType Enum => new SemanticTokenType("enum");

    public static SemanticTokenType EnumMember => new SemanticTokenType("enumMember");

    public static SemanticTokenType TypeParameter => new SemanticTokenType("typeParameter");

    public static SemanticTokenType Parameter => new SemanticTokenType("parameter");

    public static SemanticTokenType Variable => new SemanticTokenType("variable");

    public static SemanticTokenType Property => new SemanticTokenType("property");

    public static SemanticTokenType Function => new SemanticTokenType("function");

    public static SemanticTokenType Method => new SemanticTokenType("method");

    public static SemanticTokenType Keyword => new SemanticTokenType("keyword");

    public static SemanticTokenType String => new SemanticTokenType("string");

    public static SemanticTokenType Number => new SemanticTokenType("number");

    public static SemanticTokenType Operator => new SemanticTokenType("operator");

    public static SemanticTokenType Comment => new SemanticTokenType("comment");

    public static SemanticTokenType Event => new SemanticTokenType("event");

    public string Value { get; }

    public bool Equals(SemanticTokenType other) => string.Equals(this.Value, other.Value, StringComparison.Ordinal);

    public override bool Equals(object obj) => obj is SemanticTokenType other && this.Equals(other);

    public override int GetHashCode() => this.Value == null ? 0 : StringComparer.Ordinal.GetHashCode(this.Value);

    public override string ToString() => this.Value;

    public static bool operator ==(SemanticTokenType left, SemanticTokenType right) => left.Equals(right);

    public static bool operator !=(SemanticTokenType left, SemanticTokenType right) => !left.Equals(right);
}

public readonly struct SemanticTokenModifier : IEquatable<SemanticTokenModifier>
{
    public SemanticTokenModifier(string value) => this.Value = value;

    public static SemanticTokenModifier Declaration => new SemanticTokenModifier("declaration");

    public static SemanticTokenModifier Definition => new SemanticTokenModifier("definition");

    public static SemanticTokenModifier Readonly => new SemanticTokenModifier("readonly");

    public static SemanticTokenModifier Static => new SemanticTokenModifier("static");

    public static SemanticTokenModifier Async => new SemanticTokenModifier("async");

    public static SemanticTokenModifier Deprecated => new SemanticTokenModifier("deprecated");

    public string Value { get; }

    public bool Equals(SemanticTokenModifier other) => string.Equals(this.Value, other.Value, StringComparison.Ordinal);

    public override bool Equals(object obj) => obj is SemanticTokenModifier other && this.Equals(other);

    public override int GetHashCode() => this.Value == null ? 0 : StringComparer.Ordinal.GetHashCode(this.Value);

    public override string ToString() => this.Value;

    public static bool operator ==(SemanticTokenModifier left, SemanticTokenModifier right) => left.Equals(right);

    public static bool operator !=(SemanticTokenModifier left, SemanticTokenModifier right) => !left.Equals(right);
}

public sealed class SemanticTokensLegend
{
    [JsonPropertyName("tokenTypes")]
    public IReadOnlyList<SemanticTokenType> TokenTypes { get; set; }

    [JsonPropertyName("tokenModifiers")]
    public IReadOnlyList<SemanticTokenModifier> TokenModifiers { get; set; }
}

public sealed class SemanticTokens
{
    [JsonPropertyName("resultId")]
    public string ResultId { get; set; }

    [JsonPropertyName("data")]
    public ImmutableArray<int> Data { get; set; }
}

/// <summary>Accumulates pushed tokens and delta-encodes them per the LSP wire format.</summary>
public sealed class SemanticTokensBuilder
{
    private readonly SemanticTokensDocument document;
    private readonly SemanticTokensLegend legend;
    private readonly List<(int Line, int Character, int Length, int Type, int Modifiers)> tokens = new();

    public SemanticTokensBuilder(SemanticTokensDocument document, SemanticTokensLegend legend)
    {
        this.document = document;
        this.legend = legend;
    }

    public void Push(int line, int character, int length, SemanticTokenType type, SemanticTokenModifier[] modifiers)
    {
        var typeIndex = -1;
        for (var i = 0; i < this.legend.TokenTypes.Count; i++)
        {
            if (this.legend.TokenTypes[i] == type)
            {
                typeIndex = i;
                break;
            }
        }

        if (typeIndex < 0)
        {
            return;
        }

        var modifierBits = 0;
        if (modifiers != null)
        {
            foreach (var modifier in modifiers)
            {
                for (var i = 0; i < this.legend.TokenModifiers.Count; i++)
                {
                    if (this.legend.TokenModifiers[i] == modifier)
                    {
                        modifierBits |= 1 << i;
                        break;
                    }
                }
            }
        }

        this.tokens.Add((line, character, length, typeIndex, modifierBits));
    }

    public void Commit()
    {
        var ordered = this.tokens.OrderBy(t => t.Line).ThenBy(t => t.Character).ToList();
        var data = ImmutableArray.CreateBuilder<int>(ordered.Count * 5);
        var previousLine = 0;
        var previousCharacter = 0;

        foreach (var token in ordered)
        {
            var deltaLine = token.Line - previousLine;
            var deltaCharacter = deltaLine == 0 ? token.Character - previousCharacter : token.Character;
            data.Add(deltaLine);
            data.Add(deltaCharacter);
            data.Add(token.Length);
            data.Add(token.Type);
            data.Add(token.Modifiers);
            previousLine = token.Line;
            previousCharacter = token.Character;
        }

        this.document.SetData(data.ToImmutable());
    }
}

/// <summary>Holds the encoded token data produced by a <see cref="SemanticTokensBuilder"/>.</summary>
public sealed class SemanticTokensDocument
{
    private readonly SemanticTokensLegend legend;
    private ImmutableArray<int> data = ImmutableArray<int>.Empty;

    public SemanticTokensDocument(SemanticTokensLegend legend) => this.legend = legend;

    public SemanticTokensBuilder Create() => new SemanticTokensBuilder(this, this.legend);

    public SemanticTokens GetSemanticTokens() => new SemanticTokens { Data = this.data };

    public void SetData(ImmutableArray<int> value) => this.data = value;
}
