#nullable disable

// <auto-generated/>
// Hand-authored LSP protocol types for GSharp. Marked auto-generated to opt out of
// StyleCop documentation/ordering rules; this is protocol plumbing, not product logic.

using System.Text.Json.Serialization;

namespace GSharp.LanguageServer.Protocol;

/// <summary>
/// A discovered test returned by the custom <c>gsharp/discoverTests</c> request.
/// Mirrors the <c>TestItem</c> shape consumed by the VS Code extension.
/// </summary>
public sealed class TestDiscoveryItem
{
    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("label")]
    public string Label { get; set; }

    [JsonPropertyName("uri")]
    public string Uri { get; set; }

    [JsonPropertyName("line")]
    public int Line { get; set; }

    /// <summary>
    /// For a project grouping node, the absolute path to the owning <c>.gsproj</c>
    /// so the client can run <c>dotnet test</c> against the correct project. Null on
    /// the test/class items nested beneath the group (they inherit it from the group).
    /// </summary>
    [JsonPropertyName("projectFile")]
    public string ProjectFile { get; set; }

    /// <summary>
    /// A <c>dotnet test --filter "FullyQualifiedName~&lt;value&gt;"</c> token uniquely
    /// (or near-uniquely) identifying this test, e.g. <c>MyTestClass.MyTest</c> for a
    /// method or <c>MyTest</c> for a top-level test function. Null for grouping nodes.
    /// </summary>
    [JsonPropertyName("filter")]
    public string Filter { get; set; }

    [JsonPropertyName("children")]
    public TestDiscoveryItem[] Children { get; set; }
}
