// <copyright file="GeneratedSourceDetection.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cs2Gs.Translator.Loading;

/// <summary>
/// The content half of cs2gs's "is this C# file build-generated?" rule (OD-T4,
/// issue #1742). <c>CSharpProjectLoader</c> drops a file from the documents it
/// hands to the translator when it lives under the project's <c>obj/</c> or
/// <c>bin/</c> directory or when it carries this header; the translator uses
/// the same header test to recognize a dropped part of a partial method pair
/// (ADR-0143 2026-09-23 amendment), so the two can never disagree about the
/// header.
/// </summary>
public static class GeneratedSourceDetection
{
    /// <summary>
    /// Sniffs the leading comment lines of a source file for the standard
    /// <c>// &lt;auto-generated&gt;</c> marker (the convention emitted by T4,
    /// resx code-gen, source generators, and the SDK's own generated files).
    /// </summary>
    /// <param name="tree">The C# syntax tree to inspect.</param>
    /// <returns><see langword="true"/> when the file carries the marker.</returns>
    public static bool HasAutoGeneratedHeader(SyntaxTree tree)
    {
        SourceText text = tree.GetText();
        int linesToCheck = Math.Min(text.Lines.Count, 5);
        for (int i = 0; i < linesToCheck; i++)
        {
            string line = text.Lines[i].ToString().Trim();
            if (line.Length == 0)
            {
                continue;
            }

            if (!line.StartsWith("//", StringComparison.Ordinal))
            {
                break;
            }

            if (line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
