// <copyright file="GeneratedSourceDetection.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cs2Gs.Translator.Loading;

/// <summary>
/// cs2gs's "is this C# file build-generated?" rule (OD-T4, issue #1742): a file
/// is generated when it lives under the project's own <c>obj/</c> or
/// <c>bin/</c> output directory, or when its text carries the standard
/// <c>&lt;auto-generated&gt;</c> header — never by file name alone.
/// <c>CSharpProjectLoader</c> drops such files from the documents it hands to
/// the translator; the translator applies the same rule to recognize a dropped
/// part of a partial method pair (ADR-0143 2026-09-23 amendment), so the two
/// can never disagree.
/// </summary>
public static class GeneratedSourceDetection
{
    /// <summary>
    /// Whether <paramref name="tree"/> is build-generated: under the project's
    /// <c>obj/</c>/<c>bin/</c> directory (<see cref="IsUnderBuildOutputDirectory"/>)
    /// or carrying the <c>&lt;auto-generated&gt;</c> header
    /// (<see cref="HasAutoGeneratedHeader"/>).
    /// </summary>
    /// <param name="tree">The C# syntax tree to inspect.</param>
    /// <param name="projectDirectory">The owning project's directory, or <see langword="null"/> when unknown (in-memory sources), which disables the path rule.</param>
    /// <returns><see langword="true"/> when the file is build-generated.</returns>
    public static bool IsGeneratedSource(SyntaxTree tree, string projectDirectory) =>
        IsUnderBuildOutputDirectory(tree.FilePath, projectDirectory) || HasAutoGeneratedHeader(tree);

    /// <summary>
    /// Whether <paramref name="filePath"/> lies under
    /// <paramref name="projectDirectory"/>'s own <c>obj/</c> or <c>bin/</c>
    /// output directory.
    /// </summary>
    /// <param name="filePath">The source file path.</param>
    /// <param name="projectDirectory">The owning project's directory, or <see langword="null"/> when unknown.</param>
    /// <returns><see langword="true"/> for a build-output path.</returns>
    public static bool IsUnderBuildOutputDirectory(string filePath, string projectDirectory)
    {
        if (string.IsNullOrEmpty(filePath) || string.IsNullOrEmpty(projectDirectory))
        {
            return false;
        }

        string normalized = filePath.Replace('\\', '/');
        string objPrefix = Path.Combine(projectDirectory, "obj").Replace('\\', '/').TrimEnd('/') + "/";
        string binPrefix = Path.Combine(projectDirectory, "bin").Replace('\\', '/').TrimEnd('/') + "/";
        return normalized.StartsWith(objPrefix, StringComparison.OrdinalIgnoreCase) ||
            normalized.StartsWith(binPrefix, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Sniffs the leading comment lines of a source file for the standard
    /// <c>// &lt;auto-generated&gt;</c> marker (the convention emitted by T4,
    /// resx code-gen, source generators, and the SDK's own generated files).
    /// </summary>
    /// <param name="tree">The C# syntax tree to inspect.</param>
    /// <returns><see langword="true"/> when the file carries the marker.</returns>
    public static bool HasAutoGeneratedHeader(SyntaxTree tree)
    {
        SourceText text = tree.GetText();
        int linesToCheck = Math.Min(text.Lines.Count, 5);
        for (int i = 0; i < linesToCheck; i++)
        {
            string line = text.Lines[i].ToString().Trim();
            if (line.Length == 0)
            {
                continue;
            }

            if (!line.StartsWith("//", StringComparison.Ordinal))
            {
                break;
            }

            if (line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
