// <copyright file="GeneratedDocTranslatorStubIdentityTests.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Linq;
using Cs2Gs.Translator.Loading;
using GSharp.Core.CodeAnalysis.Text;
using Microsoft.CodeAnalysis;
using Xunit;
using Compilation = GSharp.Core.CodeAnalysis.Compilation.Compilation;
using GsSyntaxTree = GSharp.Core.CodeAnalysis.Syntax.SyntaxTree;

namespace GSharp.GeneratorHost.Tests;

/// <summary>
/// ADR-0192 follow-on 2: the back-translation tells the stub (the user's G#
/// declaring parts) from generator output by tree path, so no generator hint
/// name may collide with the stub's path.
/// </summary>
public class GeneratedDocTranslatorStubIdentityTests
{
    private const string UserSource = @"package App

partial class P {
    private partial func Compute(x int32) int32;

    public func Use() int32 -> Compute(1)
}
";

    [Fact]
    public void GeneratorOutputNamedLikeTheOldStubPath_IsStillAnImplementingPart()
    {
        var user = new Compilation(GsSyntaxTree.Parse(SourceText.From(UserSource, "User.gs")));

        GeneratorHostResult result = GeneratorHostRunner.Run(
            user,
            CSharpProjectLoader.RuntimeReferences(),
            new IIncrementalGenerator[] { new FixedHintGenerator("GsgenStubs.cs") });

        Assert.Empty(result.Failures);
        (string hintName, string generated) = Assert.Single(result.GeneratedGsFiles);
        Assert.Equal("GsgenStubs.cs", hintName);
        Assert.Contains("private partial func Compute(x int32) int32 {", generated, StringComparison.Ordinal);
    }

    [Fact]
    public void StubPath_IsRejectedAsAGeneratorHintName()
    {
        var user = new Compilation(GsSyntaxTree.Parse(SourceText.From(UserSource, "User.gs")));

        GeneratorHostResult result = GeneratorHostRunner.Run(
            user,
            CSharpProjectLoader.RuntimeReferences(),
            new IIncrementalGenerator[] { new FixedHintGenerator(GeneratedDocTranslator.StubPath) });

        Assert.Empty(result.GeneratedGsFiles);
        GeneratorFailure failure = Assert.Single(result.Failures);
        Assert.IsAssignableFrom<ArgumentException>(failure.Exception);
    }

    /// <summary>Implements the stub's <c>Compute</c> under a fixed hint name.</summary>
    private sealed class FixedHintGenerator : IIncrementalGenerator
    {
        private readonly string hintName;

        public FixedHintGenerator(string hintName)
        {
            this.hintName = hintName;
        }

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            string hint = this.hintName;
            context.RegisterSourceOutput(context.CompilationProvider, (spc, _) => spc.AddSource(
                hint,
                "// <auto-generated/>\nnamespace App\n{\n    partial class P\n    {\n" +
                    "        private partial int Compute(int x)\n        {\n            return x + 1;\n        }\n" +
                    "    }\n}\n"));
        }
    }
}
