// <copyright file="TranslateStage.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Cs2Gs.CodeModel.Ast;
using Cs2Gs.CodeModel.Printing;
using Cs2Gs.CodeModel.RoundTrip;
using Cs2Gs.Translator;
using Cs2Gs.Translator.Loading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Cs2Gs.Pipeline;

/// <summary>
/// Stage 1 (ADR-0115 §C): load the C# project, translate each document to
/// canonical G#, write the <c>.gs</c> set, and round-trip-parse every emitted
/// file with the real G# parser. Pass gate: every file parses AND zero
/// <see cref="TranslationSeverity.Unsupported"/> diagnostics. On failure the
/// category is <c>translation-unsupported</c> and the app short-circuits.
/// </summary>
public sealed class TranslateStage : IMigrationStage
{
    /// <inheritdoc/>
    public MigrationStageKind Kind => MigrationStageKind.Translate;

    /// <inheritdoc/>
    public async Task<StageOutcome> ExecuteAsync(
        StageExecutionContext context,
        CancellationToken cancellationToken = default)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        // Issue #2412 (reopened): this must stay the ORIGINAL CompileViaSdk-gated
        // loader choice for `projects`/`project` — the values every other part of
        // this method (PE reference capture, document translation, the generated
        // `.gsproj`'s <Reference>/<ProjectReference> sets) depends on. `LoadProjectAsync`
        // sets `LoadMetadataForReferencedProjects = true`, which is why a sibling
        // ProjectReference shows up in `project.Compilation.References` as a
        // `PortableExecutableReference` pointing at the sibling's own prebuilt ref
        // assembly (e.g. `obj/Debug/net10.0/ref/Sibling.dll`) — exactly what the SDK-
        // backed compile stage needs to resolve sibling types via CLR reference
        // assemblies (Refs #914) without re-emitting the sibling's own G#.
        // `LoadProjectWithReferencesAsync` deliberately does NOT set that flag (a
        // sibling ProjectReference instead becomes a same-workspace `CompilationReference`
        // to a separately loaded source `Project`), so swapping it in here — as a
        // prior version of this fix did — silently emptied `project.Compilation`'s
        // own `PortableExecutableReference` set for every sibling, breaking every
        // downstream reference/type resolution the app's OWN generated `.gsproj` and
        // gsc compile depend on (a regression caught by re-running the real Oahu
        // corpus, not by any in-memory test). Cross-project taint analysis needs only
        // read-only sibling `CSharpCompilation`s matched by metadata identity (see
        // `ObliviousNullabilityAnalyzer.RemapToCompilation`), never object/reference
        // identity with `project.Compilation` — so it is loaded independently below,
        // via its own isolated `LoadProjectWithReferencesAsync` call/workspace, and
        // never touches `projects`/`project` or anything derived from them.
        string projectPath = Path.GetFullPath(context.App.ProjectPath);
        IReadOnlyList<LoadedCSharpProject> projects =
            context.Options.RepositoryLoadedProjects is not null
            && context.Options.RepositoryLoadedProjects.TryGetValue(projectPath, out LoadedCSharpProject repositoryProject)
            ? new[] { repositoryProject }
            : context.Options.CompileViaSdk
            ? new[]
            {
                await CSharpProjectLoader.LoadProjectAsync(
                    projectPath,
                    cancellationToken,
                    includeAutoGenerated: context.Options.OutputLayout == MigrationOutputLayout.Repository,
                    includedAutoGeneratedPaths: context.Options.RepositorySourceFiles)
                    .ConfigureAwait(false),
            }
            : await CSharpProjectLoader
                .LoadProjectWithReferencesAsync(
                    context.App.ProjectPath,
                    cancellationToken,
                    includeAutoGenerated: context.Options.OutputLayout == MigrationOutputLayout.Repository,
                    includedAutoGeneratedPaths: context.Options.RepositorySourceFiles)
                .ConfigureAwait(false);
        LoadedCSharpProject project = projects[0];
        context.IsTestProject = project.IsTestProject;

        var artifacts = new List<TriageArtifact>();
        Directory.CreateDirectory(context.ProjectOutputDir);
        Directory.CreateDirectory(context.ArtifactDir);

        // Issue #1742: a project that does not even bind in C# (missing SDK/
        // targets, an unresolved project reference, an unsupported TFM, ...)
        // must stop here — proceeding to translate produces only confusing
        // downstream binding errors instead of the real load failure. This is
        // scoped to the MSBuild workspace load failure signal specifically
        // (not every C# semantic error), since some corpus fixtures carry a
        // deliberate C# error to exercise a later stage (e.g. CompileGap-Library).
        if (project.WorkspaceLoadFailed)
        {
            artifacts.Add(context.Triage.ProjectLoadFailure(
                MigrationStageKind.Translate,
                TriageCategory.TranslationUnsupported,
                project.WorkspaceLoadErrors));
            return StageOutcome.Failed(artifacts);
        }

        // Issue #2321: a benign NuGet audit vulnerability advisory (CS2GS0003)
        // does not fail the workspace load above, but must not be dropped
        // silently either — record it in the per-app translate.log, the same
        // best-effort append-only text log TestParityStage's Note already
        // uses for non-fatal, informational events (test-parity.log).
        NoteNuGetAuditAdvisories(context, project);

        var usedOutputPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (context.Options.OutputLayout == MigrationOutputLayout.DiagnosticRun)
        {
            CopyProjectFiles(project.ProjectDirectory, context.ProjectOutputDir, usedOutputPaths);
            CopyCentralPackageManagementFile(project.ProjectDirectory, context.ProjectOutputDir, context);
        }

        context.PackageReferences.AddRange(
            DeclaredProjectItems.BumpNerdbankGitVersioningVersion(
                DeclaredProjectItems.Read(context.App.ProjectPath, "PackageReference")));
        context.ProjectReferences.AddRange(
            DeclaredProjectItems.Read(context.App.ProjectPath, "ProjectReference"));

        // Issue #2412: every project's own `Compilation` in this run (app +
        // every transitively-referenced sibling), so `TranslationContext.
        // ResolveDeclaringCompilation` can redirect a whole-program fact query
        // (e.g. `ObliviousNullabilityAnalyzer`'s oblivious-taint fixpoint) for a
        // symbol declared in a REFERENCED sibling project back to that
        // sibling's OWN compilation — the one whose syntax trees actually
        // contain the tainting evidence — instead of always the current
        // document's own project compilation, which never sees it.
        //
        // Issue #2412 (reopened): under the default SDK-backed path `projects`
        // above is deliberately kept to the app's own project only (see the
        // loader comment), so it can no longer double as the sibling list here.
        // Load the transitive sibling projects a SECOND time, independently,
        // purely to bind their own compilations for this taint lookup — this
        // extra MSBuild workspace load only ever feeds `IsTainted`'s read-only,
        // metadata-identity-based cross-compilation symbol remap (see
        // `ObliviousNullabilityAnalyzer.RemapToCompilation`), so it is safe for
        // it to be a wholly separate `Compilation` graph than `project`'s own —
        // and it never touches `projects`/`project`, PE reference capture, or
        // anything the generated `.gsproj` depends on.
        IReadOnlyList<CSharpCompilation> siblingCompilations;
        if (context.Options.CompileViaSdk)
        {
            IReadOnlyList<LoadedCSharpProject> taintOnlyProjects = await CSharpProjectLoader
                .LoadProjectWithReferencesAsync(
                    context.App.ProjectPath,
                    cancellationToken,
                    includeAutoGenerated: context.Options.OutputLayout == MigrationOutputLayout.Repository,
                    includedAutoGeneratedPaths: context.Options.RepositorySourceFiles)
                .ConfigureAwait(false);
            siblingCompilations = taintOnlyProjects.Select(p => p.Compilation).ToList();
        }
        else
        {
            siblingCompilations = projects.Select(p => p.Compilation).ToList();
        }

        IReadOnlyList<CSharpCompilation> repositoryCompilations =
            context.Options.RepositoryLoadedProjects?.Values
                .Select(p => p.Compilation)
                .ToList();

        // Translate the app itself (index 0) plus, in the no-via-sdk path,
        // its transitively referenced sibling projects (Refs #914); under the
        // default SDK-backed path `projects` above contains only the app
        // itself, so this loop's `projectIndex > 0` branch never runs there —
        // a referenced sibling is migrated and compiled as its own,
        // independent app, linked back in by the Compile stage's rewritten
        // ProjectReference/prebuilt CLR reference assembly (Refs #914), and
        // its `Compilation` is already available above via
        // `siblingCompilations` for cross-project taint resolution. Sibling
        // G# is emitted here only in the no-via-sdk path, so the app's uses
        // of sibling types resolve at the gsc compile stage; those files are
        // flagged IsFromReferencedProject so the Compile stage attributes errors
        // only to the app's own files (a sibling's own gaps are measured in its
        // own run, not charged against every dependent).
        for (int projectIndex = 0; projectIndex < projects.Count; projectIndex++)
        {
            LoadedCSharpProject currentProject = projects[projectIndex];
            bool isReferencedProject = projectIndex > 0;

            // Capture the external (NuGet package) assemblies each project
            // resolved against so the Compile stage can add them to gsc's
            // reference set. Only on-disk file-backed references are recorded
            // here; the Compile stage further excludes any whose file name
            // collides with a framework assembly (ref-pack / runtime
            // double-identity) and stripped sibling outputs are already absent
            // from disk (Refs #914).
            foreach (PortableExecutableReference peReference in currentProject.Compilation.References
                .OfType<PortableExecutableReference>())
            {
                string referencePath = peReference.FilePath;
                if (!string.IsNullOrEmpty(referencePath) && File.Exists(referencePath))
                {
                    context.ExternalReferencePaths.Add(referencePath);
                }
            }

            // Issue #2215: only the app's OWN analyzer/generator references
            // (not a referenced sibling project's) drive gsc's /analyzer: —
            // a sibling's generators already ran in that sibling's own
            // migration run, so re-running them here would just duplicate
            // (or, worse, collide with) output that belongs to the sibling.
            if (!isReferencedProject)
            {
                context.RootNamespace = currentProject.RootNamespace;

                foreach (string analyzerPath in currentProject.AnalyzerReferencePaths)
                {
                    context.AnalyzerReferencePaths.Add(analyzerPath);
                }

                // Issue #2223: forward the app's non-source generator inputs
                // (.axaml) and project options so gsc's gsgen run materializes
                // file-driven generator output (e.g. Avalonia's InitializeComponent).
                foreach (string additionalFile in currentProject.AdditionalFiles)
                {
                    string copiedPath = MirroredPath(
                        additionalFile,
                        currentProject.ProjectDirectory,
                        context.ProjectOutputDir);
                    string spec = File.Exists(copiedPath) ? copiedPath : additionalFile;
                    string ext = Path.GetExtension(additionalFile);
                    if (ext.Equals(".axaml", StringComparison.OrdinalIgnoreCase) ||
                        ext.Equals(".xaml", StringComparison.OrdinalIgnoreCase) ||
                        ext.Equals(".paml", StringComparison.OrdinalIgnoreCase))
                    {
                        spec += ";SourceItemGroup=AvaloniaXaml";
                    }

                    context.AdditionalGeneratorFiles.Add(spec);
                }

                if (context.AdditionalGeneratorFiles.Count > 0)
                {
                    if (!string.IsNullOrEmpty(currentProject.RootNamespace))
                    {
                        context.GeneratorGlobalOptions.Add("RootNamespace=" + currentProject.RootNamespace);
                    }

                    if (!string.IsNullOrEmpty(currentProject.ProjectDirectory))
                    {
                        context.GeneratorGlobalOptions.Add("ProjectDir=" + context.ProjectOutputDir);
                    }
                }
            }

            // Issue #2215: a project with analyzer references may have had a
            // generator-produced partial part excluded from `Documents` (it is
            // recognized as generated, per `CSharpProjectLoader.
            // IsGeneratedSource`, so BuildDocuments never translates it on its
            // own) — so the translator must (a) keep the merged type `partial`
            // (gsc's own gsgen run adds the missing part back) and (b) NOT
            // merge that excluded part's members in here too (that would just
            // duplicate what gsgen produces, causing a GS0102 collision). Every
            // project with no analyzer references gets the exact prior
            // (unfiltered, non-partial-marking) translator behavior.
            bool hasAnalyzerReferences = currentProject.AnalyzerReferencePaths.Count > 0;
            List<string> retainedFilePaths = hasAnalyzerReferences
                ? currentProject.Documents.Select(d => d.FilePath).ToList()
                : null;
            var translator = new CSharpToGSharpTranslator(
                markMergedTypePartial: hasAnalyzerReferences,
                retainedFilePaths: retainedFilePaths);

            EmitFriendAssemblyAnnotations(
                context,
                currentProject,
                isReferencedProject,
                usedOutputPaths);

            foreach (LoadedDocument document in currentProject.Documents)
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (IsResxDesignerCodebehind(document.FilePath))
                {
                    continue;
                }

                IReadOnlyList<string> packages =
                    context.Options.OutputLayout == MigrationOutputLayout.Repository
                        ? CSharpToGSharpTranslator.GetDeclaredPackages(document)
                            .OrderBy(package => package.Count(c => c == '.'))
                            .ToList()
                        : Array.Empty<string>();
                int unitCount = Math.Max(1, packages.Count);
                string primaryGsRelativePath = null;
                for (int unitIndex = 0; unitIndex < unitCount; unitIndex++)
                {
                    string package = packages.Count > 1 ? packages[unitIndex] : null;
                    var translationContext = new TranslationContext(
                        currentProject.Compilation,
                        document.SemanticModel,
                        document.FilePath,
                        siblingCompilations,
                        repositoryCompilations);
                    CSharpToGSharpTranslator unitTranslator = package is null
                        ? translator
                        : new CSharpToGSharpTranslator(
                            markMergedTypePartial: hasAnalyzerReferences,
                            retainedFilePaths: retainedFilePaths,
                            packageFilter: package);
                    string printed = GSharpPrinter.Print(
                        unitTranslator.TranslateDocument(document, translationContext));

                    string gsRelativePath;
                    if (unitIndex == 0)
                    {
                        gsRelativePath =
                            context.Options.OutputLayout == MigrationOutputLayout.Repository
                                ? RepositoryOutputPathForSource(
                                    document.FilePath, context, usedOutputPaths)
                                : OutputPathForSource(
                                    document.FilePath,
                                    currentProject,
                                    isReferencedProject,
                                    usedOutputPaths);
                        primaryGsRelativePath = gsRelativePath;
                        if (context.Options.OutputLayout == MigrationOutputLayout.Repository)
                        {
                            RegisterRepositoryTranslation(context.Options, document.FilePath, printed);
                        }
                    }
                    else
                    {
                        gsRelativePath = NamespaceSplitOutputPath(
                            primaryGsRelativePath,
                            package,
                            packages[0],
                            usedOutputPaths);
                        context.Options.RepositoryAdditionalFiles.Add(
                            Path.GetRelativePath(
                                Path.GetFullPath(context.Options.OutputRoot),
                                Path.Combine(context.ProjectOutputDir, gsRelativePath)));
                    }

                    string gsPath = Path.Combine(context.ProjectOutputDir, gsRelativePath);
                    Directory.CreateDirectory(Path.GetDirectoryName(gsPath));
                    File.WriteAllText(gsPath, printed);

                    string relativeGsPath = MigrationPipeline.SanitizeAppId(context.App.Id) + "/" +
                        gsRelativePath.Replace(Path.DirectorySeparatorChar, '/');
                    var emitted = new EmittedGsFile(
                        gsPath,
                        relativeGsPath,
                        document.FilePath,
                        printed)
                    {
                        IsFromReferencedProject = isReferencedProject,
                    };
                    context.EmittedFiles.Add(emitted);

                    if (isReferencedProject)
                    {
                        continue;
                    }

                    foreach (TranslationDiagnostic diagnostic in translationContext.Diagnostics
                        .Where(d => d.Severity == TranslationSeverity.Unsupported))
                    {
                        artifacts.Add(context.Triage.TranslationUnsupported(diagnostic));
                    }

                    RoundTripResult roundTrip = GSharpRoundTrip.Validate(printed);
                    if (!roundTrip.Success)
                    {
                        artifacts.Add(context.Triage.RoundTripFailure(
                            emitted,
                            roundTrip.Errors.FirstOrDefault() ?? "unknown parse error"));
                    }
                }
            }

            // Issue #2200: generate each .resx's strongly-typed codebehind via the
            // shared GSharp.Core.Resx generator instead of translating a
            // hand-authored Resources.Designer.cs (which BuildDocuments already
            // skips above as generated source, via its <auto-generated> header).
            // Without this, a `using R = ...Resources;` alias in the migrated
            // source cannot resolve (GS0157), cascading into GS0159 errors.
            foreach (string resxPath in currentProject.ResxFiles)
            {
                cancellationToken.ThrowIfCancellationRequested();

                string generated;
                try
                {
                    generated = GSharp.Core.Resx.ResxCodeGenerator.GenerateFromFile(
                        resxPath,
                        currentProject.ProjectDirectory,
                        currentProject.RootNamespace);
                }
                catch (Exception ex) when (ex is IOException or System.Xml.XmlException or UnauthorizedAccessException)
                {
                    // A malformed/unreadable .resx must not crash the whole
                    // Translate stage; report it (for the app's own project
                    // only, mirroring the translation-diagnostics gate below)
                    // and move on to the remaining files.
                    if (!isReferencedProject)
                    {
                        artifacts.Add(context.Triage.StageCrash(
                            MigrationStageKind.Translate, TriageCategory.TranslationUnsupported, "CS2GS0003", ex));
                    }

                    continue;
                }

                string gsRelativePath = OutputPathForResx(
                    resxPath,
                    currentProject,
                    isReferencedProject,
                    usedOutputPaths);
                string gsPath = Path.Combine(context.ProjectOutputDir, gsRelativePath);
                Directory.CreateDirectory(Path.GetDirectoryName(gsPath));
                File.WriteAllText(gsPath, generated);

                string relativeGsPath = MigrationPipeline.SanitizeAppId(context.App.Id) + "/" +
                    gsRelativePath.Replace(Path.DirectorySeparatorChar, '/');
                var emittedResx = new EmittedGsFile(
                    gsPath,
                    relativeGsPath,
                    resxPath,
                    generated)
                {
                    IsFromReferencedProject = isReferencedProject,
                };
                context.EmittedFiles.Add(emittedResx);

                if (isReferencedProject)
                {
                    continue;
                }

                RoundTripResult resxRoundTrip = GSharpRoundTrip.Validate(generated);
                if (!resxRoundTrip.Success)
                {
                    artifacts.Add(context.Triage.RoundTripFailure(
                        emittedResx,
                        resxRoundTrip.Errors.FirstOrDefault() ?? "unknown parse error"));
                }
            }
        }

        // Issue #2225: nbgv only generates the `ThisAssembly` source for the
        // languages its MSBuild `<Language>` switch supports; G# first shipped in
        // 3.11.13-beta. If the migrated project references an older nbgv it would
        // silently drop `ThisAssembly`. Emit a bumped copy of whichever project /
        // props file pins a below-floor nbgv literal (source is never mutated).
        EmitNerdbankGitVersioningBumps(context);

        return artifacts.Count == 0 ? StageOutcome.Passed() : StageOutcome.Failed(artifacts);
    }

    private static void EmitFriendAssemblyAnnotations(
        StageExecutionContext context,
        LoadedCSharpProject project,
        bool isReferencedProject,
        ISet<string> usedOutputPaths)
    {
        const string attributeName = "System.Runtime.CompilerServices.InternalsVisibleToAttribute";
        List<string> friendAssemblies = project.Compilation.Assembly.GetAttributes()
            .Where(attribute =>
                attribute.AttributeClass?.ToDisplayString() == attributeName &&
                attribute.ConstructorArguments.Length == 1 &&
                attribute.ConstructorArguments[0].Value is string)
            .Select(attribute => (string)attribute.ConstructorArguments[0].Value)
            .Distinct(StringComparer.Ordinal)
            .ToList();
        if (friendAssemblies.Count == 0)
        {
            return;
        }

        string source = string.Join(
            Environment.NewLine,
            friendAssemblies.Select(name =>
                "@assembly:InternalsVisibleTo(" +
                Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(name, quote: true) +
                ")")) + Environment.NewLine;
        string relativePath = UniqueOutputPath(
            PrefixReferencedProject("AssemblyInfo.gs", project, isReferencedProject),
            usedOutputPaths);
        string path = Path.Combine(context.ProjectOutputDir, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path));
        File.WriteAllText(path, source);

        string emittedRelativePath = MigrationPipeline.SanitizeAppId(context.App.Id) + "/" +
            relativePath.Replace(Path.DirectorySeparatorChar, '/');
        context.EmittedFiles.Add(new EmittedGsFile(
            path,
            emittedRelativePath,
            context.App.ProjectPath,
            source)
        {
            IsFromReferencedProject = isReferencedProject,
        });
    }

    /// <summary>
    /// Issue #2321: records any benign NuGet audit vulnerability advisory
    /// (<see cref="CSharpProjectLoader.NuGetAuditAdvisoryDiagnosticId"/>,
    /// CS2GS0003) MSBuildWorkspace reported while opening <paramref name="project"/>
    /// into the per-app <c>translate.log</c>. The advisory never fails this
    /// stage — <see cref="CSharpProjectLoader"/> already excludes it from
    /// <see cref="LoadedCSharpProject.ErrorDiagnostics"/> — this only keeps it
    /// from being silently dropped once <see cref="LoadedCSharpProject.LoadDiagnostics"/>
    /// is no longer inspected past the <see cref="LoadedCSharpProject.WorkspaceLoadFailed"/>
    /// gate above.
    /// </summary>
    private static void NoteNuGetAuditAdvisories(StageExecutionContext context, LoadedCSharpProject project)
    {
        foreach (Diagnostic advisory in project.LoadDiagnostics
            .Where(d => d.Id == CSharpProjectLoader.NuGetAuditAdvisoryDiagnosticId))
        {
            Note(context, "NuGet audit advisory (CS2GS0003, non-fatal): " + advisory.GetMessage());
        }
    }

    /// <summary>
    /// A best-effort, append-only per-app text log — the Translate-stage
    /// counterpart of <see cref="TestParityStage"/>'s identical <c>Note</c>
    /// helper (which writes <c>test-parity.log</c>). Never fails the stage on
    /// a log write.
    /// </summary>
    private static void Note(StageExecutionContext context, string message)
    {
        try
        {
            File.AppendAllText(
                Path.Combine(context.ArtifactDir, "translate.log"),
                message + Environment.NewLine);
        }
        catch (IOException)
        {
            // A best-effort diagnostic log; never fail the stage on a log write.
        }
    }

    private static void CopyProjectFiles(
        string projectDirectory,
        string outputDirectory,
        ISet<string> usedOutputPaths)
    {
        if (string.IsNullOrEmpty(projectDirectory) || !Directory.Exists(projectDirectory))
        {
            return;
        }

        foreach (string sourcePath in Directory.EnumerateFiles(projectDirectory, "*", SearchOption.AllDirectories))
        {
            string relativePath = Path.GetRelativePath(projectDirectory, sourcePath);
            if (HasExcludedDirectory(relativePath) ||
                Path.GetExtension(sourcePath).Equals(".cs", StringComparison.OrdinalIgnoreCase) ||
                IsResxDesignerCodebehind(sourcePath) ||
                Path.GetExtension(sourcePath).Equals(".csproj", StringComparison.OrdinalIgnoreCase) ||
                IsUnderDirectory(sourcePath, outputDirectory))
            {
                continue;
            }

            string destinationPath = Path.Combine(outputDirectory, relativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(destinationPath));
            File.Copy(sourcePath, destinationPath, overwrite: true);
            usedOutputPaths.Add(relativePath);
        }
    }

    private static bool IsResxDesignerCodebehind(string sourcePath)
    {
        string fileName = Path.GetFileName(sourcePath);
        string suffix = fileName.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase)
            ? ".Designer.cs"
            : fileName.EndsWith(
                GSharp.Core.Resx.ResxCodeGenerator.DesignerFileSuffix,
                StringComparison.OrdinalIgnoreCase)
                ? GSharp.Core.Resx.ResxCodeGenerator.DesignerFileSuffix
                : null;
        if (suffix is null)
        {
            return false;
        }

        string resxPath = Path.Combine(
            Path.GetDirectoryName(sourcePath) ?? string.Empty,
            fileName[..^suffix.Length] + ".resx");
        return File.Exists(resxPath);
    }

    /// <summary>
    /// Locates the ancestor <c>Directory.Packages.props</c> that governs the
    /// source project (Central Package Management) and writes it into the
    /// generated app root — the file NuGet actually restores the generated
    /// <c>.gsproj</c> against. Issue #2319: a below-floor literal nbgv
    /// <c>PackageVersion</c> is bumped here, in this copy, using the same
    /// <see cref="NerdbankGitVersioningPolicy.TryBumpProjectXml"/> the
    /// project-file bump path already uses — the previous behavior copied the
    /// file verbatim and wrote the bumped text to an inert
    /// <c>nbgv-bump/Directory.Packages.props</c> that nothing ever restored
    /// against, so NuGet still saw the below-floor version while
    /// <see cref="SdkCompileRunner"/> independently emitted a bumped
    /// <c>Version=</c> attribute on the generated NBGV <c>PackageReference</c> —
    /// a combination Central Package Management rejects outright (NU1008).
    /// Also records on <paramref name="context"/> whether the copied file
    /// actually enables CPM (<c>ManagePackageVersionsCentrally</c>), so the
    /// <c>--via-sdk</c> compile path knows to omit <c>Version=</c> from any
    /// <c>PackageReference</c> it synthesizes rather than reconstructs
    /// verbatim from the source project.
    /// </summary>
    private static void CopyCentralPackageManagementFile(
        string projectDirectory,
        string outputDirectory,
        StageExecutionContext context)
    {
        string directory = projectDirectory;
        while (!string.IsNullOrEmpty(directory))
        {
            string sourcePath = Path.Combine(directory, "Directory.Packages.props");
            if (File.Exists(sourcePath))
            {
                string original;
                try
                {
                    original = File.ReadAllText(sourcePath);
                }
                catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
                {
                    return;
                }

                string content = NerdbankGitVersioningPolicy.TryBumpProjectXml(original, out string bumped)
                    ? bumped
                    : original;
                File.WriteAllText(Path.Combine(outputDirectory, "Directory.Packages.props"), content);
                context.UsesCentralPackageManagement =
                    CentralPackageManagementPolicy.IsEnabled(projectDirectory, directory, content);
                return;
            }

            directory = Directory.GetParent(directory)?.FullName;
        }
    }

    private static string OutputPathForSource(
        string sourcePath,
        LoadedCSharpProject project,
        bool isReferencedProject,
        ISet<string> usedOutputPaths)
    {
        string relativePath = RelativeSourcePath(sourcePath, project.ProjectDirectory);
        relativePath = Path.ChangeExtension(relativePath, ".gs");
        return UniqueOutputPath(PrefixReferencedProject(relativePath, project, isReferencedProject), usedOutputPaths);
    }

    private static string RepositoryOutputPathForSource(
        string sourcePath,
        StageExecutionContext context,
        ISet<string> usedOutputPaths)
    {
        string sourceRelativePath = Path.GetRelativePath(context.Options.SourceRoot, sourcePath);
        if (IsOutsideDirectory(sourceRelativePath))
        {
            throw new InvalidOperationException(
                $"Source file '{sourcePath}' is outside repository root '{context.Options.SourceRoot}'.");
        }

        string destinationPath = Path.Combine(
            Path.GetFullPath(context.Options.OutputRoot),
            Path.ChangeExtension(sourceRelativePath, ".gs"));
        string relativeToProject = Path.GetRelativePath(context.ProjectOutputDir, destinationPath);
        if (!usedOutputPaths.Add(relativeToProject))
        {
            throw new InvalidOperationException(
                $"Multiple C# documents map to repository output '{destinationPath}'.");
        }

        return relativeToProject;
    }

    private static string NamespaceSplitOutputPath(
        string primaryPath,
        string package,
        string primaryPackage,
        ISet<string> usedOutputPaths)
    {
        string suffix = package.StartsWith(primaryPackage + ".", StringComparison.Ordinal)
            ? package[(primaryPackage.Length + 1)..]
            : package;
        suffix = suffix.Replace('.', '_');
        string splitPath = Path.Combine(
            Path.GetDirectoryName(primaryPath) ?? string.Empty,
            Path.GetFileNameWithoutExtension(primaryPath) + "." + suffix + ".gs");
        if (!usedOutputPaths.Add(splitPath))
        {
            throw new InvalidOperationException(
                $"Multiple namespace outputs map to repository output '{splitPath}'.");
        }

        return splitPath;
    }

    private static void RegisterRepositoryTranslation(
        PipelineOptions options,
        string sourcePath,
        string generated)
    {
        string canonicalSourcePath = Path.GetFullPath(sourcePath);
        options.RepositoryTranslations ??=
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (options.RepositoryTranslations.TryGetValue(
            canonicalSourcePath, out string priorGenerated))
        {
            if (!string.Equals(priorGenerated, generated, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    $"Linked source '{sourcePath}' translates differently in multiple projects.");
            }

            return;
        }

        options.RepositoryTranslations[canonicalSourcePath] = generated;
    }

    private static string OutputPathForResx(
        string sourcePath,
        LoadedCSharpProject project,
        bool isReferencedProject,
        ISet<string> usedOutputPaths)
    {
        string relativePath = RelativeSourcePath(sourcePath, project.ProjectDirectory);
        string directory = Path.GetDirectoryName(relativePath);
        string fileName = Path.GetFileNameWithoutExtension(relativePath) +
            GSharp.Core.Resx.ResxCodeGenerator.DesignerFileSuffix;
        relativePath = string.IsNullOrEmpty(directory) ? fileName : Path.Combine(directory, fileName);
        return UniqueOutputPath(PrefixReferencedProject(relativePath, project, isReferencedProject), usedOutputPaths);
    }

    private static string PrefixReferencedProject(
        string relativePath,
        LoadedCSharpProject project,
        bool isReferencedProject)
    {
        if (!isReferencedProject)
        {
            return relativePath;
        }

        string projectName = project.Compilation.AssemblyName ?? "ReferencedProject";
        foreach (char invalid in Path.GetInvalidFileNameChars())
        {
            projectName = projectName.Replace(invalid, '_');
        }

        return Path.Combine(".references", projectName, relativePath);
    }

    private static string RelativeSourcePath(string sourcePath, string projectDirectory)
    {
        string relativePath = Path.GetRelativePath(projectDirectory, sourcePath);
        return IsOutsideDirectory(relativePath) ? Path.GetFileName(sourcePath) : relativePath;
    }

    private static string UniqueOutputPath(string relativePath, ISet<string> usedOutputPaths)
    {
        if (usedOutputPaths.Add(relativePath))
        {
            return relativePath;
        }

        string directory = Path.GetDirectoryName(relativePath);
        string extension = Path.GetExtension(relativePath);
        string baseName = Path.GetFileNameWithoutExtension(relativePath);
        for (int suffix = 2; ; suffix++)
        {
            string fileName = baseName + "." + suffix + extension;
            string candidate = string.IsNullOrEmpty(directory) ? fileName : Path.Combine(directory, fileName);
            if (usedOutputPaths.Add(candidate))
            {
                return candidate;
            }
        }
    }

    private static string MirroredPath(string sourcePath, string projectDirectory, string outputDirectory)
    {
        string relativePath = Path.GetRelativePath(projectDirectory, sourcePath);
        return IsOutsideDirectory(relativePath) ? sourcePath : Path.Combine(outputDirectory, relativePath);
    }

    private static bool HasExcludedDirectory(string relativePath)
    {
        string[] segments = relativePath.Split(
            new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar },
            StringSplitOptions.RemoveEmptyEntries);
        return segments.Any(s =>
            s.Equals("bin", StringComparison.OrdinalIgnoreCase) ||
            s.Equals("obj", StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsOutsideDirectory(string relativePath) =>
        Path.IsPathRooted(relativePath) ||
        relativePath.Equals("..", StringComparison.Ordinal) ||
        relativePath.StartsWith(".." + Path.DirectorySeparatorChar, StringComparison.Ordinal) ||
        relativePath.StartsWith(".." + Path.AltDirectorySeparatorChar, StringComparison.Ordinal);

    private static bool IsUnderDirectory(string path, string directory)
    {
        string relativePath = Path.GetRelativePath(directory, path);
        return !IsOutsideDirectory(relativePath);
    }

    /// <summary>
    /// Scans the app's own <c>.csproj</c> plus every ancestor
    /// <c>Directory.Packages.props</c>/<c>Directory.Build.props</c> for a literal
    /// <c>Nerdbank.GitVersioning</c> version below
    /// <see cref="NerdbankGitVersioningPolicy.MinimumGSharpVersion"/> and, when
    /// found, writes a bumped copy into <c>&lt;AppRunDir&gt;/nbgv-bump/</c> alongside
    /// a manifest recording the source path. The original files are never touched
    /// (the corpus tree is read-only); the migrated project can adopt the bumped
    /// file so nbgv produces the G# <c>ThisAssembly</c> source (issue #2225).
    /// Also resolves, across the same candidate set, the nbgv package's effective
    /// id/version/<c>PrivateAssets</c>/<c>IncludeAssets</c> declaration and — when
    /// found — records it on <see cref="StageExecutionContext.BuildOnlyPackageReferences"/>
    /// so the <c>--via-sdk</c> compile path can re-declare it in the isolated
    /// gsproj (issue #2267): nbgv is a build/dev-only dependency that contributes
    /// no compile-time reference DLL, so it would otherwise be silently dropped
    /// and its <c>ThisAssembly</c> source generator would never run.
    /// </summary>
    private static void EmitNerdbankGitVersioningBumps(StageExecutionContext context)
    {
        var candidates = new List<string>();
        string projectPath = context.App.ProjectPath;
        if (!string.IsNullOrEmpty(projectPath) && File.Exists(projectPath))
        {
            candidates.Add(projectPath);
        }

        string dir = Path.GetDirectoryName(projectPath);
        while (!string.IsNullOrEmpty(dir))
        {
            foreach (string name in new[] { "Directory.Packages.props", "Directory.Build.props" })
            {
                string candidate = Path.Combine(dir, name);
                if (File.Exists(candidate))
                {
                    candidates.Add(candidate);
                }
            }

            DirectoryInfo parent = Directory.GetParent(dir);
            dir = parent?.FullName;
        }

        string outputDir = null;
        var manifest = new List<string>();
        var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        bool nbgvFound = false;
        string rawVersion = null;
        string privateAssets = null;
        string includeAssets = null;
        foreach (string candidate in candidates)
        {
            string original;
            try
            {
                original = File.ReadAllText(candidate);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                continue;
            }

            // Issue #2267: combine the nbgv declaration across every candidate
            // file — CPM commonly splits it between a versionless
            // <PackageReference PrivateAssets="all"> (project/Directory.Build.props)
            // and the actual <PackageVersion Version="..."> (Directory.Packages.props).
            if (NerdbankGitVersioningPolicy.TryFindDeclaration(
                original, out string candidateVersion, out string candidatePrivateAssets, out string candidateIncludeAssets))
            {
                nbgvFound = true;
                rawVersion ??= candidateVersion;
                privateAssets ??= candidatePrivateAssets;
                includeAssets ??= candidateIncludeAssets;
            }

            if (!NerdbankGitVersioningPolicy.TryBumpProjectXml(original, out string bumped))
            {
                continue;
            }

            if (outputDir is null)
            {
                outputDir = Path.Combine(context.ArtifactDir, "nbgv-bump");
                Directory.CreateDirectory(outputDir);
            }

            string baseName = Path.GetFileName(candidate);
            string outName = baseName;
            int suffix = 1;
            while (!usedNames.Add(outName))
            {
                outName = Path.GetFileNameWithoutExtension(baseName) + "." + suffix + Path.GetExtension(baseName);
                suffix++;
            }

            File.WriteAllText(Path.Combine(outputDir, outName), bumped);
            manifest.Add(outName + " <- " + candidate);
        }

        if (outputDir is not null && manifest.Count > 0)
        {
            string manifestText =
                "# Nerdbank.GitVersioning bumped to " + NerdbankGitVersioningPolicy.MinimumGSharpVersion
                + " for G# ThisAssembly support (issue #2225)." + Environment.NewLine
                + "# Each line: <emitted file> <- <original source file>." + Environment.NewLine
                + string.Join(Environment.NewLine, manifest) + Environment.NewLine;
            File.WriteAllText(Path.Combine(outputDir, "manifest.txt"), manifestText);
        }

        if (nbgvFound)
        {
            context.BuildOnlyPackageReferences.Add(new DeclaredPackageReference(
                NerdbankGitVersioningPolicy.PackageId,
                NerdbankGitVersioningPolicy.ResolveEffectiveVersion(rawVersion),
                privateAssets ?? "all",
                includeAssets));
        }
    }
}
