// <copyright file="WriteGsharpAssemblyInfoTask.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.Build.Framework;

namespace Gsharp.NET.Sdk.Tools;

/// <summary>
/// Issue #2814 / ADR-0143 §D: renders the .NET SDK's <c>@(AssemblyAttribute)</c>
/// item group as a G# source file of file-level <c>@assembly:</c> annotations.
/// </summary>
/// <remarks>
/// <para>
/// The SDK's own <c>CoreGenerateAssemblyInfo</c> target is gated on
/// <c>Condition="'$(Language)'=='VB' or '$(Language)'=='C#'"</c>, so a project
/// that sets <c>&lt;Language&gt;Gsharp&lt;/Language&gt;</c> never runs it and the
/// resulting assembly silently loses <c>AssemblyTitle</c>,
/// <c>AssemblyProduct</c>, <c>AssemblyCompany</c>, <c>AssemblyConfiguration</c>
/// and peers. Its <c>WriteCodeFragment</c> task cannot simply be re-invoked
/// here: that task is CodeDom-based and only knows C# and VB.
/// </para>
/// <para>
/// This task reproduces the same contract natively. It honors the same item
/// metadata conventions <c>WriteCodeFragment</c> defines — positional
/// <c>_Parameter1</c>…<c>_ParameterN</c> constructor arguments, any other
/// metadata as a named argument, and a <c>&lt;name&gt;_IsLiteral</c> sibling that
/// emits the value as raw code instead of a string literal — so a project that
/// already hand-authors <c>&lt;AssemblyAttribute&gt;</c> items for a C# build
/// keeps working unchanged after migration.
/// </para>
/// </remarks>
public class WriteGsharpAssemblyInfoTask : Microsoft.Build.Utilities.Task
{
    private const string ParameterPrefix = "_Parameter";
    private const string LiteralSuffix = "_IsLiteral";

    /// <summary>
    /// Gets or sets the <c>@(AssemblyAttribute)</c> items to render. Each item's
    /// identity is the attribute type name; its metadata supplies the arguments.
    /// </summary>
    [Required]
    public ITaskItem[] AssemblyAttributes { get; set; } = Array.Empty<ITaskItem>();

    /// <summary>
    /// Gets or sets the <c>.gs</c> file to write. The file is only touched when
    /// its content changes so MSBuild incrementality (and gsc's own
    /// <c>Inputs</c>/<c>Outputs</c> check) does not see a spurious edit.
    /// </summary>
    [Required]
    public string OutputFile { get; set; }

    /// <summary>
    /// Renders <paramref name="attributes"/> as a G# compilation unit of
    /// file-level <c>@assembly:</c> annotations. Exposed for testing.
    /// </summary>
    /// <param name="attributes">The assembly attribute items to render.</param>
    /// <returns>The complete G# source text.</returns>
    public static string Render(IEnumerable<ITaskItem> attributes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by the Gsharp.NET.Sdk WriteGsharpAssemblyInfo task.");
        sb.AppendLine("//     Changes to this file will be lost when it is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        foreach (ITaskItem attribute in attributes ?? Enumerable.Empty<ITaskItem>())
        {
            if (attribute == null || string.IsNullOrWhiteSpace(attribute.ItemSpec))
            {
                continue;
            }

            sb.AppendLine("@assembly: " + RenderOne(attribute));
        }

        return sb.ToString();
    }

    /// <summary>
    /// Escapes <paramref name="value"/> as a G# interpreted string literal,
    /// including the literal-<c>$</c> escape (<c>$$</c>) that G# interpolation
    /// requires but C# does not.
    /// </summary>
    /// <param name="value">The raw string value.</param>
    /// <returns>The quoted, escaped G# literal.</returns>
    public static string QuoteGsharpString(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (char c in value)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;

                // G# interpolates '$ident' and '${expr}' in every interpreted
                // string; '$$' is the literal-'$' escape (docs/lexical.md).
                case '$': sb.Append("$$"); break;
                case '\0': sb.Append("\\0"); break;
                case '\a': sb.Append("\\a"); break;
                case '\b': sb.Append("\\b"); break;
                case '\f': sb.Append("\\f"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\v': sb.Append("\\v"); break;
                default:
                    if (char.IsControl(c))
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }

    /// <inheritdoc />
    public override bool Execute()
    {
        if (string.IsNullOrEmpty(this.OutputFile))
        {
            this.Log.LogError("WriteGsharpAssemblyInfo: OutputFile is required.");
            return false;
        }

        string content;
        try
        {
            content = Render(this.AssemblyAttributes);
        }
        catch (ArgumentException ex)
        {
            this.Log.LogError("WriteGsharpAssemblyInfo: " + ex.Message);
            return false;
        }

        string directory = Path.GetDirectoryName(Path.GetFullPath(this.OutputFile));
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        if (!File.Exists(this.OutputFile) ||
            !string.Equals(File.ReadAllText(this.OutputFile), content, StringComparison.Ordinal))
        {
            File.WriteAllText(this.OutputFile, content);
        }

        this.Log.LogMessage(
            MessageImportance.Low,
            "WriteGsharpAssemblyInfo: wrote {0} assembly attribute(s) to {1}.",
            this.AssemblyAttributes?.Length ?? 0,
            this.OutputFile);

        return !this.Log.HasLoggedErrors;
    }

    private static string RenderOne(ITaskItem attribute)
    {
        var positional = new SortedDictionary<int, string>();
        var named = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var metadata = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        foreach (DictionaryEntry entry in attribute.CloneCustomMetadata())
        {
            metadata[(string)entry.Key] = (string)entry.Value ?? string.Empty;
        }

        foreach (KeyValuePair<string, string> entry in metadata)
        {
            // '<name>_IsLiteral' is a modifier on '<name>', never an argument.
            if (entry.Key.EndsWith(LiteralSuffix, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            bool isLiteral = metadata.TryGetValue(entry.Key + LiteralSuffix, out string literalFlag) &&
                string.Equals(literalFlag, "true", StringComparison.OrdinalIgnoreCase);
            string rendered = isLiteral ? entry.Value : QuoteGsharpString(entry.Value);

            if (entry.Key.StartsWith(ParameterPrefix, StringComparison.OrdinalIgnoreCase) &&
                int.TryParse(
                    entry.Key.Substring(ParameterPrefix.Length),
                    NumberStyles.None,
                    CultureInfo.InvariantCulture,
                    out int index))
            {
                positional[index] = rendered;
            }
            else
            {
                named[entry.Key] = rendered;
            }
        }

        // WriteCodeFragment treats a gap in the positional sequence as an error;
        // matching it here keeps a malformed item from silently shifting args.
        int expected = 1;
        foreach (int index in positional.Keys)
        {
            if (index != expected++)
            {
                throw new ArgumentException(
                    "Assembly attribute '" + attribute.ItemSpec + "' skips constructor argument " +
                    expected.ToString(CultureInfo.InvariantCulture) +
                    "; positional '_ParameterN' metadata must be contiguous from 1.");
            }
        }

        IEnumerable<string> arguments = positional.Values
            .Concat(named.Select(pair => pair.Key + ": " + pair.Value));

        // A parameterless attribute is written bare, matching how G# source
        // spells '@assembly: DisableRuntimeMarshalling'.
        string argumentList = string.Join(", ", arguments.ToArray());
        return argumentList.Length == 0
            ? attribute.ItemSpec
            : attribute.ItemSpec + "(" + argumentList + ")";
    }
}
