// <copyright file="SyntaxKind.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

// Disabling some warnings temporarily for fast iterations.
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable SA1602 // Enumeration items should be documented

namespace GSharp.Core.CodeAnalysis.Syntax;

/// <summary>
/// Represents a kind of syntax token in the language.
/// </summary>
public enum SyntaxKind
{
    // Punctuation tokens
    BadToken,
    WhitespaceToken,
    CommentToken,
    EndOfFileToken,

    // Language tokens
    PlusToken,
    PlusEqualsToken,
    PlusPlusToken,
    MinusToken,
    MinusEqualsToken,
    MinusMinusToken,
    StarToken,
    StarEqualsToken,
    SlashToken,
    SlashEqualsToken,
    PercentToken,
    PercentEqualsToken,
    OpenParenthesisToken,
    CloseParenthesisToken,
    OpenSquareBracketToken,
    CloseSquareBracketToken,
    OpenBraceToken,
    CloseBraceToken,
    ColonToken,
    ColonEqualsToken,
    SemicolonToken,
    CommaToken,
    DotToken,
    EllipsisToken,
    HatToken,
    HatEqualsToken,
    AmpersandToken,
    AmpersandAmpersandToken,
    AmpersandEqualsToken,
    AmpersandHatToken,
    AmpersandHatEqualsToken,
    PipeToken,
    PipeEqualsToken,
    PipePipeToken,
    EqualsToken,
    EqualsEqualsToken,
    BangToken,
    BangEqualsToken,
    BangBangToken,
    QuestionToken,
    QuestionDotToken,
    QuestionColonToken,
    LessToken,
    LessOrEqualsToken,
    LeftArrowToken,
    RightArrowToken,
    ShiftLeftToken,
    ShiftLeftEqualsToken,
    GreaterToken,
    GreaterOrEqualsToken,
    ShiftRightToken,
    ShiftRightEqualsToken,

    // ADR-0047: annotation lead-in token
    AtToken,

    // Built-in type tokens
    StringToken,
    InterpolatedStringToken,
    NumberToken,
    CharacterToken,

    // Identifier tokens
    IdentifierToken,

    // Reserved keywords
    AsyncKeyword,
    AwaitKeyword,
    BreakKeyword,
    CaseKeyword,
    ChanKeyword,
    ClassKeyword,
    ConstKeyword,
    ContinueKeyword,
    DefaultKeyword,
    DeferKeyword,
    ElseKeyword,
    EnumKeyword,
    FalseKeyword,
    FallthroughKeyword,
    ForKeyword,
    FuncKeyword,
    GoKeyword,
    GotoKeyword,
    IfKeyword,
    ImportKeyword,
    InterfaceKeyword,
    InternalKeyword,
    IsKeyword,
    LetKeyword,
    MapKeyword,
    NilKeyword,
    OpenKeyword,
    OperatorKeyword,
    OverrideKeyword,
    PackageKeyword,
    PrivateKeyword,
    PublicKeyword,
    RangeKeyword,
    ReturnKeyword,
    SealedKeyword,
    SelectKeyword,
    ScopeKeyword,
    SequenceKeyword,
    StructKeyword,
    SwitchKeyword,
    ThrowKeyword,
    TrueKeyword,
    TryKeyword,
    TypeKeyword,
    UsingKeyword,
    VarKeyword,

    // compilation
    CompilationUnit,
    GlobalStatement,
    ExpressionStatement,
    AssignmentExpression,
    UnaryExpression,
    BinaryExpression,
    ParenthesizedExpression,
    LiteralExpression,
    InterpolatedStringExpression,
    NameExpression,
    CallExpression,
    AccessorExpression,
    ArrayCreationExpression,
    MapCreationExpression,
    MapEntry,
    IndexExpression,
    IndexAssignmentExpression,
    PackageDeclaration,
    ImportDeclaration,
    FunctionDeclaration,
    TypeAliasDeclaration,
    EnumDeclaration,
    EnumMember,
    Parameter,
    TypeClause,
    TypeParameter,
    TypeParameterList,
    TypeArgumentList,
    BlockStatement,
    VariableDeclaration,
    IfStatement,
    ElseClause,
    ForInfiniteStatement,
    ForEllipsisStatement,
    ForConditionStatement,
    ForClauseStatement,
    ForRangeStatement,
    BreakStatement,
    ContinueStatement,
    ReturnStatement,
    MultiAssignmentStatement,
    SwitchStatement,
    SwitchCase,
    SwitchExpression,
    SwitchExpressionArm,

    // Pattern syntax
    ConstantPattern,
    DiscardPattern,
    TypePattern,
    PropertyPattern,
    PropertyPatternField,
    RelationalPattern,
    ListPattern,
    TryStatement,
    CatchClause,
    FinallyClause,
    ThrowStatement,
    UsingStatement,
    DeferStatement,
    CatchKeyword,
    FinallyKeyword,
    StructDeclaration,
    InterfaceDeclaration,
    FieldDeclaration,
    StructLiteralExpression,
    FieldInitializer,
    FieldAccessExpression,
    FieldAssignmentExpression,
    TupleLiteralExpression,
    TupleDeconstructionStatement,
    NamedDeconstructionStatement,
    NamedDeconstructionField,
    NamedArgumentExpression,
    WithExpression,
    FunctionLiteralExpression,
    AwaitExpression,
    GoStatement,
    MakeChannelExpression,
    ChannelReceiveExpression,
    ChannelSendStatement,
    SelectStatement,
    SelectCase,
    ScopeStatement,
    AwaitForRangeStatement,
    EventSubscriptionExpression,
    YieldStatement,

    // Issue #143: typeof / nameof contextual operators
    TypeOfExpression,
    NameOfExpression,

    // Issue #141 / ADR-0047: attribute (annotation) syntax
    Annotation,
    AnnotationTarget,

    // ADR-0051: property declarations
    PropertyDeclaration,
    EventDeclaration,
    PropertyAccessor,
    EventAccessor,

    // ADR-0053: static (shared) members
    SharedBlock,
}

#pragma warning restore SA1602 // Enumeration items should be documented
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
