// <copyright file="SyntaxKind.cs" company="GSharp">
// Copyright (C) GSharp Authors. All rights reserved.
// </copyright>

// Disabling some warnings temporarily for fast iterations.
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable SA1602 // Enumeration items should be documented

namespace GSharp.Core.CodeAnalysis.Syntax;

/// <summary>
/// Represents a kind of syntax token in the language.
/// </summary>
public enum SyntaxKind
{
    // Punctuation tokens
    BadToken,
    WhitespaceToken,
    CommentToken,
    EndOfFileToken,

    // Language tokens
    PlusToken,
    PlusEqualsToken,
    PlusPlusToken,
    MinusToken,
    MinusEqualsToken,
    MinusMinusToken,
    StarToken,
    StarEqualsToken,
    SlashToken,
    SlashEqualsToken,
    PercentToken,
    PercentEqualsToken,
    OpenParenthesisToken,
    CloseParenthesisToken,
    OpenSquareBracketToken,
    CloseSquareBracketToken,
    OpenBraceToken,
    CloseBraceToken,
    ColonToken,
    ColonEqualsToken,
    SemicolonToken,
    CommaToken,
    DotToken,
    EllipsisToken,
    HatToken,
    HatEqualsToken,
    AmpersandToken,
    AmpersandAmpersandToken,
    AmpersandEqualsToken,
    AmpersandHatToken,
    AmpersandHatEqualsToken,
    PipeToken,
    PipeEqualsToken,
    PipePipeToken,
    EqualsToken,
    EqualsEqualsToken,
    BangToken,
    BangEqualsToken,
    BangBangToken,
    QuestionToken,
    QuestionDotToken,
    QuestionColonToken,
    LessToken,
    LessOrEqualsToken,
    LeftArrowToken,
    ShiftLeftToken,
    ShiftLeftEqualsToken,
    GreaterToken,
    GreaterOrEqualsToken,
    ShiftRightToken,
    ShiftRightEqualsToken,

    // Built-in type tokens
    StringToken,
    InterpolatedStringToken,
    NumberToken,

    // Identifier tokens
    IdentifierToken,

    // Reserved keywords
    BreakKeyword,
    CaseKeyword,
    ChanKeyword,
    ClassKeyword,
    ConstKeyword,
    ContinueKeyword,
    DefaultKeyword,
    DeferKeyword,
    ElseKeyword,
    FalseKeyword,
    FallthroughKeyword,
    ForKeyword,
    FuncKeyword,
    GoKeyword,
    GotoKeyword,
    IfKeyword,
    ImportKeyword,
    InterfaceKeyword,
    InternalKeyword,
    LetKeyword,
    MapKeyword,
    NilKeyword,
    OpenKeyword,
    OverrideKeyword,
    PackageKeyword,
    PrivateKeyword,
    PublicKeyword,
    RangeKeyword,
    ReturnKeyword,
    SealedKeyword,
    SelectKeyword,
    StructKeyword,
    SwitchKeyword,
    ThrowKeyword,
    TrueKeyword,
    TryKeyword,
    TypeKeyword,
    UsingKeyword,
    VarKeyword,

    // compilation
    CompilationUnit,
    GlobalStatement,
    ExpressionStatement,
    AssignmentExpression,
    UnaryExpression,
    BinaryExpression,
    ParenthesizedExpression,
    LiteralExpression,
    InterpolatedStringExpression,
    NameExpression,
    CallExpression,
    AccessorExpression,
    ArrayCreationExpression,
    IndexExpression,
    IndexAssignmentExpression,
    PackageDeclaration,
    ImportDeclaration,
    FunctionDeclaration,
    TypeAliasDeclaration,
    Parameter,
    TypeClause,
    TypeParameter,
    TypeParameterList,
    TypeArgumentList,
    BlockStatement,
    VariableDeclaration,
    IfStatement,
    ElseClause,
    ForInfiniteStatement,
    ForEllipsisStatement,
    ForConditionStatement,
    ForClauseStatement,
    BreakStatement,
    ContinueStatement,
    ReturnStatement,
    MultiAssignmentStatement,
    SwitchStatement,
    SwitchCase,
    TryStatement,
    CatchClause,
    FinallyClause,
    ThrowStatement,
    UsingStatement,
    CatchKeyword,
    FinallyKeyword,
    StructDeclaration,
    InterfaceDeclaration,
    FieldDeclaration,
    StructLiteralExpression,
    FieldInitializer,
    FieldAccessExpression,
    FieldAssignmentExpression,
}

#pragma warning restore SA1602 // Enumeration items should be documented
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
